"""The random-goals experiment: tables and the registered decision rule, from results.json here, the maze10
experiment's results.json, the interior-goals experiment's results_single.json and the additive ceiling's results.json.

    .venv/bin/python studies/7_information_seeking/random_goals/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np
from scipy.stats import mannwhitneyu

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
REFS = (("oracle", "oracle"), ("qmdp2", "QMDP + lookahead"), ("qmdp", "QMDP"), ("mls", "most likely cell"), ("random", "random moves"))
p_less = lambda a, b: float(mannwhitneyu(a, b, alternative="less", method="exact").pvalue)


def arm(R):
    seeds = sorted(R["runs"], key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(R["runs"][s], p)) is None else x for s in seeds], dtype=float)
    return v, len(seeds)


def recovery(v):
    nat, blind = v("natural", "ret"), v("online", "goal_blind", "ret")
    return (v("online", "additive", "ret") - blind) / (nat - blind)


def main():
    C4 = json.load(open(OUT.parent / "maze10" / "results.json"))
    S = json.load(open(OUT.parent / "interior_goals" / "results_single.json"))
    R = json.load(open(OUT / "results.json"))
    ceil_path = OUT.parent / "additive_ceiling" / "results.json"
    ceil = json.load(open(ceil_path)) if ceil_path.exists() else {}
    vc, _ = arm(C4); vs, _ = arm(S); vr, n = arm(R)
    const = lambda x: np.full(n, x)
    arms = (("maze10 (4 spread goals)", vc, C4), ("single junction goal (6)", vs, S), ("**random goals (55)**", vr, R))
    L = ["# The random-goals experiment tables", "",
         "Generated by `studies/7_information_seeking/random_goals/tables.py`. Six reward-trained models; the maze10 maze with every cell a possible goal, one per "
         "episode. 8 192 fixed evaluation episodes. Median (range) over models. maze10 and the single junction arm: those experiments' models.", "",
         "## Behaviour", ""]
    L += head("", *[a[0] for a in arms])
    L.append(row("**models: return**", *[mr(v("natural", "ret")) for _, v, _ in arms]))
    L.append(row("models: success", *[mr(v("natural", "success")) for _, v, _ in arms]))
    L.append(row("models: moves", *[mr(v("natural", "length"), 1) for _, v, _ in arms]))
    for k, kl in REFS:
        L.append(row(f"{kl}: return (success)", *[f"{f(X['references'][k]['ret'])} ({f(X['references'][k]['success'], 2)})" for _, _, X in arms]))
    L += ["", "## The additive policy, run in the environment", ""]
    L += head("", *[a[0] for a in arms])
    for k, kl in (("additive", "**additive: argmax H + G**"), ("goal_blind", "goal-blind: argmax H"), ("history_blind", "history-blind: argmax G")):
        L.append(row(f"{kl}, return", *[mr(v("online", k, "ret")) for _, v, _ in arms]))
    rc, rs, rr = recovery(vc), recovery(vs), recovery(vr)
    L.append(row("**recovery** (additive − goal-blind) / (natural − goal-blind)", mr(rc, 2), mr(rs, 2), mr(rr, 2)))
    L.append(row("additive policy: success", *[mr(v("online", "additive", "success"), 2) for _, v, _ in arms]))
    for k, kl in (("goal_matters_share", "the model's move depends on the goal: share of decisions"), ("same_action_goal_matters", "there: the additive choice is the model's move"),
                  ("same_action_goal_blind", "there: the goal-blind choice is the model's move"), ("additive_share", "additive share of the logits' goal dependence")):
        L.append(row(kl, *[mr(v("additive_offline", k)) for _, v, _ in arms]))
    if ceil:
        L += ["", "The additive ceiling (no network; the agent knows its cell): share of (cell, goal) decisions where the best rule picks a shortest-path move:", ""]
        L += head("maze and goals", "best additive rule argmax H(cell) + G(goal)", "best goal-blind rule argmax H(cell)")
        for k, d in ceil.items():
            L.append(row(k, f(d["additive"]), f(d["goal_blind"])))
    L += ["", "## Removals at the decision token, online", ""]
    L += head("at the decision token", *[a[0] for a in arms])
    for k, kl in (("natural", "nothing"), ("noI", "**interaction removed: history part + goal part**"), ("noH", "history part removed, interaction kept"),
                  ("noG", "goal part removed, interaction kept"), ("goal_blind", "reference: goal-blind policy")):
        L.append(row(kl, *[mr(v("removal", k, "ret")) for _, v, _ in arms]))
    recI = lambda v: (v("removal", "noI", "ret") - v("removal", "goal_blind", "ret")) / (v("removal", "natural", "ret") - v("removal", "goal_blind", "ret"))
    L.append(row("**recovery**, interaction removed", *[mr(recI(v), 2) for _, v, _ in arms]))
    L += ["", "## Information seeking", ""]
    L += head("", "deviates from QMDP", "information gain of its move − QMDP's, at deviations", "a random other move in the same states", "registered null: QMDP with random moves",
              "its move is the more informative", "posterior entropy: mean; steps 0, 5, 10, 20")
    for name, v, X in arms:
        e = [np.median([(X["runs"][s]["natural"]["entropy_by_step"][i] or np.nan) for s in X["runs"]]) for i in range(4)]
        q = X["references"]["qmdp"]
        L.append(row(f"models, {name}", mr(v("natural", "deviation_rate")), mr(v("natural", "ig_advantage"), 4), mr(v("natural", "ig_advantage_random_same_state"), 4),
                     mr(v("noisy_qmdp", "ig_advantage"), 4), mr(v("natural", "more_informative"), 2), f"{mr(v('natural', 'entropy_mean'), 2)}; " + ", ".join(f(x, 2) for x in e)))
        L.append(row(f"QMDP, {name}", "0", "—", "—", "—", "—", f"{f(q['entropy_mean'], 2)}; " + ", ".join(f(x, 2) for x in q["entropy_by_step"][:4])))
    L += ["", "## Decoders", ""]
    L += head("", *[a[0] for a in arms])
    for k, kl in (("posterior_r2", "exact posterior, R²"), ("cell_accuracy_decoded", "true cell from the decoded posterior"), ("cell_accuracy_posterior", "true cell from the exact posterior")):
        L.append(row(kl, *[mr(v("decoders", k)) for _, v, _ in arms]))
    L += ["", "## The fixed bias per goal (random goals; descriptive)", ""]
    L += head("", "value")
    L.append(row("the share of cells from which G(goal)'s preferred move is a shortest-path move", mr(vr("bias_field", "bias_move_optimal_share"))))
    L.append(row("the best single move per goal: that share", mr(vr("bias_field", "best_single_move_share"))))
    L.append(row("G(goal)'s preferred move is the best single move: share of goals", mr(vr("bias_field", "bias_is_best_single_move"))))
    L.append(row("(goal, step) bins that fell back to the goal's all-step mean", mr(vr("G_fit", "bins_sparse"))))
    L.append(row("fit decisions × goals (every decision gives a deviation for every goal)", mr(vr("G_fit", "fit_decisions"), 0)))
    yes = lambda b: "**yes**" if b else "no"
    nat, mls_ = vr("natural", "ret"), R["references"]["mls"]["ret"]
    ig, ign = vr("natural", "ig_advantage"), vr("noisy_qmdp", "ig_advantage")
    pS = max(p_gt(ig, const(0.0)), p_gt(ig, ign))
    pD = p_less(rr, rs - 0.15)
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**LEARN**", "return ≥ the most-likely-cell policy's", f"{f(np.median(nat))} against {f(mls_)}; p {fp(p_gt(nat, const(mls_)))}", yes(np.median(nat) >= mls_ and p_gt(nat, const(mls_)) < 0.05)))
    L.append(row("**SEEK-B**", "deviations from QMDP are more informative than its move, and more than the random-deviation null",
                 f"{f(np.median(ig), 4)} against {f(np.median(ign), 4)}; p {fp(pS)}", yes(np.median(ig) > 0 and np.median(ig) > np.median(ign) and pS < 0.05)))
    L.append(row("**AD**", "additive policy: recovery ≥ 0.9", f(np.median(rr), 2), yes(np.median(rr) >= 0.9)))
    L.append(row("**DROP**", "recovery lower than the single junction arm's by ≥ 0.15", f"{f(np.median(rr), 2)} against {f(np.median(rs), 2)}; p {fp(pD)}",
                 yes(np.median(rs) - np.median(rr) >= 0.15 and pD < 0.05)))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
