"""The residual-trace experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/5_goal_belief_mechanism/residual_trace/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
STRATA = (("margin", "margin to the donor's action (quartile, low → high)", ("Q1", "Q2", "Q3", "Q4")),
          ("unsolvable", "posterior additively solvable / unsolvable", ("solvable", "unsolvable")),
          ("interaction", "natural action = additive decision / differs", ("same", "differs")),
          ("goal", "goal", ("G1", "G2", "G3")),
          ("entropy", "posterior entropy (tercile)", ("low", "mid", "high")),
          ("H_error", "H's deviation from its posterior mean (quartile)", ("Q1", "Q2", "Q3", "Q4")),
          ("r_norm", "size of the swapped residual (quartile)", ("Q1", "Q2", "Q3", "Q4")))
COEF = ("margin", "unsolvable", "interaction", "goal_G2", "goal_G3", "entropy", "H_error", "r_norm")


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(runs[s], p)) is None else x for s in seeds], dtype=float)
    L = ["# The residual-trace experiment tables", "",
         "Generated by `studies/5_goal_belief_mechanism/residual_trace/tables.py`. The observation-prediction experiment's ten reward models; informative pairs "
         f"{mr(v('pairs'), 0)} per model. Real arm: r(h′) − r(h) at the goal token's four attention outputs; rot: the same vectors rotated. "
         "Excess = real − rot. Concentration = a bin's share of the total excess flip / its share of pairs. Median (range).", "",
         f"Overall: flip real {mr(v('overall', 'flip_real'))}, rot {mr(v('overall', 'flip_rot'))}; shift toward the donor's action real "
         f"{mr(v('overall', 'shift_real'))}, rot {mr(v('overall', 'shift_rot'))}.", ""]
    conc = {}
    for key, label, names in STRATA:
        L += [f"## {label}", ""]
        L += head("bin", "share of pairs", "flip real", "flip rot", "excess flip", "concentration", "excess shift")
        for i, nm in enumerate(names):
            b = lambda m: v("strata", key, str(i), m)
            c = b("share_of_excess") / b("share")
            conc[(key, i)] = c
            L.append(row(nm, mr(b("share")), mr(b("flip_real")), mr(b("flip_rot")), mr(b("excess_flip")), mr(c, 2), mr(b("excess_shift"))))
        L.append("")
    L += ["## Joint fit of the excess shift (standardized coefficients)", ""]
    L += head("", *COEF)
    L.append(row("excess shift", *[mr(v("joint", k)) for k in COEF]))
    L.append(row("excess flip", *[mr(v("joint_flip", k)) for k in COEF]))
    # rule
    sx = lambda key, i: v("strata", key, str(i), "share_of_excess")
    es = lambda key, i: v("strata", key, str(i), "excess_shift")
    low_half = sx("margin", 0) + sx("margin", 1)
    ratio_shift = es("margin", 3) / es("margin", 0)
    bnd = np.median(low_half) >= 0.75 and np.median(ratio_shift) >= 0.5
    pI = p_gt(es("unsolvable", 1), es("unsolvable", 0))
    imp = np.median(conc[("unsolvable", 1)]) >= 2 and pI < 0.05
    intc = np.median(conc[("interaction", 1)]) >= 2
    err = np.median(conc[("H_error", 3)]) >= 2
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**BND**", "lower half of margin holds ≥ 0.75 of the excess flip, and top-quartile excess shift ≥ 0.5 × bottom's",
                 f"{f(np.median(low_half), 2)}; {f(np.median(ratio_shift), 2)} ×", yes(bnd)))
    L.append(row("**IMP**", "unsolvable concentration ≥ 2, and excess shift there > solvable's",
                 f"{f(np.median(conc[('unsolvable', 1)]), 2)}; shift {f(np.median(es('unsolvable', 1)))} against {f(np.median(es('unsolvable', 0)))}, p {fp(pI)}", yes(imp)))
    L.append(row("**INT**", "interaction-used concentration ≥ 2", f(np.median(conc[("interaction", 1)]), 2), yes(intc)))
    L.append(row("**ERR**", "top H-error quartile concentration ≥ 2", f(np.median(conc[("H_error", 3)]), 2), yes(err)))
    reading = ("fine-grained correction" if bnd and not (imp or intc) else "interaction route" if (imp or intc) else "a separate, localized signal")
    L += ["", f"**Registered reading: {reading}.**", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
