"""Round 34: tables and the registered decision rule from results.json.

    .venv/bin/python rounds/r34_nonlinear_belief_edit/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "r32_direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
KINDS = (("none", "none"), ("whole", "whole replacement"), ("linear", "linear E Δb (round 33)"), ("mlp", "**MLP f(b), shared**"), ("mlp_goal", "MLP f(b, g)"),
         ("table", "**table μ(b), shared (ceiling)**"), ("table_goal", "table μ_g(b)"), ("rotated", "rotated MLP edit"), ("pca", "PCA-13 patch"),
         ("residual", "residual: whole minus μ part"), ("hybrid", "hybrid"))


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(runs[s], p)) is None else x for s in seeds], dtype=float)
    c = R["counts"]
    L = ["# Round 34 tables", "", "Generated by `rounds/r34_nonlinear_belief_edit/tables.py`. Round 23's ten reward models; the goal token before block 0's MLP "
         f"(round 33's site). Main pairs {c['main_pairs']}, one-step agreeing {c['onestep_pairs']}, equivalent-recipient pairs {c['equivalent_pairs']}. "
         "Median (range) over the ten models of rates pooled over each model's cells.", ""]
    L += ["## Encoding fit (held-out)", ""]
    L += head("encoding", "R²", "R² within (goal, length)")
    for k, kl in (("linear", "linear, shared"), ("goal_specific_linear", "linear, goal-specific"), ("mlp", "MLP f(b), shared"), ("mlp_goal", "MLP f(b, g)"),
                  ("table", "table μ(b), shared"), ("table_goal", "table μ_g(b)")):
        L.append(row(kl, mr(v("fit", k, "r2")), mr(v("fit", k, "r2_within_goal_length"))))
    L += ["", f"Distinct posteriors {int(v('fit', 'posteriors')[0])}, of which {int(v('fit', 'posteriors_unseen')[0])} absent from the fit side.", ""]
    L += head("edit vector against the actual difference", "norm ratio", "cosine", "residual share")
    for k in ("linear", "mlp", "mlp_goal", "table", "table_goal"):
        L.append(row(k, mr(v("edit_stats", k, "norm_ratio")), mr(v("edit_stats", k, "cosine")), mr(v("edit_stats", k, "residual_share"))))
    ch = lambda k, m: v("main", "change", k, m)
    L += ["", "## Main pairs, change cells", ""]
    L += head("edit", "donor-optimal", "gain over none", "as hybrid", "S (of whole)", "pooled logit projection")
    for k, kl in KINDS:
        L.append(row(kl, mr(ch(k, "donor_optimal")), mr(ch(k, "donor_optimal") - ch("none", "donor_optimal")), mr(ch(k, "as_hybrid")),
                     mr(ch(k, "share_of_whole"), 2) if k != "hybrid" else "—", mr(ch(k, "projection"), 2) if k != "hybrid" else "1"))
    gd = lambda k, m="right_every_change_goal": v("main", "goal_dependent", k, m)
    L += ["", "## Goal-dependent pairs", "", f"Pairs: {int(np.median(v('main', 'goal_dependent', 'n')))}.", ""]
    L += head("edit", "donor-optimal under every change goal", "/ whole", "right under two goals with different actions")
    for k, kl in KINDS:
        L.append(row(kl, mr(gd(k)), mr(gd(k) / gd("whole"), 2), mr(gd(k, "right_distinct_actions"))))
    pr = lambda k, m: v("main", "preserve", k, m)
    L += ["", "## Preserve cells", ""]
    L += head("edit", "still optimal", "harm")
    for k, kl in KINDS:
        L.append(row(kl, mr(pr(k, "optimal")), mr(pr(k, "harm")) if k != "hybrid" else "—"))
    os_ = lambda k, m: v("onestep", "change", k, m)
    L += ["", "## One-step agreeing pairs, change cells", ""]
    L += head("edit", "donor-optimal", "gain over none", "S (of whole)")
    for k, kl in KINDS:
        L.append(row(kl, mr(os_(k, "donor_optimal")), mr(os_(k, "donor_optimal") - os_("none", "donor_optimal")), mr(os_(k, "share_of_whole"), 2) if k != "hybrid" else "—"))
    eq = lambda k, m: v("equivalent", "change", k, m)
    L += ["", "## Equivalent recipients (four histories with the recipient's posterior)", ""]
    L += head("edit", "all four donor-optimal", "/ whole", "pairwise agreement", "variance between belief changes")
    for k, kl in KINDS:
        L.append(row(kl, mr(eq(k, "all_donor_optimal")), mr(eq(k, "all_donor_optimal") / eq("whole", "all_donor_optimal"), 2), mr(eq(k, "agreement")), mr(eq(k, "between_share"), 2)))
    # decision rule
    D = lambda k: ch(k, "donor_optimal")
    gain = lambda k: D(k) - D("none")
    crit = []
    rP = np.median(gd("mlp") / gd("whole"))
    pPr, pPl = p_gt(gd("mlp"), gd("rotated")), p_gt(gd("mlp"), gd("linear"))
    crit.append(("**P** (primary)", "goal-dependent: mlp ≥ 0.75 × whole; above rotated; above linear", f"{f(rP, 2)} ×; p {fp(pPr)}; p {fp(pPl)} (Δ {f(np.median(gd('mlp') - gd('linear')))})",
                 rP >= 0.75 and pPr < 0.05 and pPl < 0.05))
    N = np.median(v("fit", "mlp", "r2_within_goal_length") - v("fit", "linear", "r2_within_goal_length"))
    crit.append(("N fit", "mlp R² within ≥ linear + 0.05", f"+{f(N)}", N >= 0.05))
    S = np.median(ch("mlp", "share_of_whole"))
    crit.append(("C1", "S(mlp) ≥ 0.75, gain ≥ 0.25", f"S {f(S, 2)}; gain {f(np.median(gain('mlp')))}", S >= 0.75 and np.median(gain("mlp")) >= 0.25))
    h = np.median(pr("mlp", "harm"))
    crit.append(("C3", "harm(mlp) ≤ 0.05", f(h), h <= 0.05))
    og = lambda k: os_(k, "donor_optimal") - os_("none", "donor_optimal")
    r4, p4 = np.median(og("mlp") / og("whole")), p_gt(os_("mlp", "donor_optimal"), os_("rotated", "donor_optimal"))
    crit.append(("C4", "one-step agreeing ≥ 0.5 × whole, above rotated", f"{f(r4, 2)} ×; p {fp(p4)}", r4 >= 0.5 and p4 < 0.05))
    d5 = np.median(D("pca") - D("mlp"))
    crit.append(("C5b", "D(pca) − D(mlp) ≤ 0.05", f(d5), d5 <= 0.05))
    r6 = np.median(eq("mlp", "all_donor_optimal") / eq("whole", "all_donor_optimal"))
    crit.append(("C6", "all four donor-optimal: mlp ≥ 0.75 × whole", f"{f(r6, 2)} ×", r6 >= 0.75))
    d7, d7g = np.median(D("mlp") - D("mlp_goal")), np.median(gd("mlp") - gd("mlp_goal"))
    crit.append(("C7", "D(mlp) ≥ D(mlp_goal) − 0.05; goal-dependent mlp ≥ mlp_goal − 0.03", f"{f(d7)}; {f(d7g)}", d7 >= -0.05 and d7g >= -0.03))
    rT = np.median(gd("table") / gd("whole"))
    crit.append(("**T** (ceiling)", "goal-dependent: table ≥ 0.75 × whole", f"{f(rT, 2)} ×", rT >= 0.75))
    rR = np.median(gd("residual") / gd("whole"))
    crit.append(("R (descriptive)", "residual's goal-dependent rate / whole's", f"{f(rR, 2)} × (none: {f(np.median(gd('none') / gd('whole')), 2)} ×)", None))
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    for a, b, cv, ok in crit:
        L.append(row(a, b, cv, "" if ok is None else ("**yes**" if ok else "no")))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
