"""The goal-swap-components experiment: tables from results.json (and posthoc.json if present).

    .venv/bin/python studies/5_goal_belief_mechanism/goal_swap_components/tables.py            # writes tables.md
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
f = lambda x, d=2: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
mr = lambda xs, d=2: "—" if len(xs) == 0 or np.all(np.isnan(xs)) else f"{f(np.nanmedian(xs), d)} ({f(np.nanmin(xs), d)} to {f(np.nanmax(xs), d)})"
COMPS = [f"L{l}.H{h}" for l in range(4) for h in range(4)] + [f"L{l}.mlp" for l in range(4)]
GROUPS = ("selected", "complement", "all_blocks_1_3", "attention_1_3", "mlp_1_3")


def main():
    res = json.load(open(OUT / "results.json"))
    R = res["runs"]
    seeds = sorted(R, key=lambda s: int(s[4:]))
    g = lambda side, key, m: np.array([R[s][side].get(key, {}).get(m, np.nan) for s in seeds], dtype=float)
    L = ["# The goal-swap-components experiment tables", "", f"Generated by `studies/5_goal_belief_mechanism/goal_swap_components/tables.py`. The observation-prediction experiment's ten reward models. Cells: (history, goal, other goal) with disjoint optimal sets; "
         f"discovery {res['cells']['discovery']} (fit side), test {res['cells']['test']} (held out). All patches at the goal token. patch: 1 − TV(patched, donor) / TV(recipient, donor), "
         "mean over cells (registered); restore: the same toward the recipient; DLA: share of the logit difference written directly. Median (range) over the ten models.", ""]
    base = lambda k: np.array([R[s]["test"]["_base"][k] for s in seeds])
    L += [f"Unpatched: donor-goal-optimal greedy actions {mr(base('donor_optimal_unpatched'))} in the recipient's run, {mr(base('donor_optimal_donor'))} in the donor's; "
          f"TV(recipient, donor) {mr(base('tv'))}.", ""]
    L += ["## Single components (discovery)", ""]
    L += head("component", "patch", "restore", "donor-optimal after patch", "DLA share")
    for c in COMPS:
        L.append(row(c, mr(g("discovery", c, "patch")), mr(g("discovery", c, "restore")), mr(g("discovery", c, "donor_optimal")), mr(g("discovery", c, "dla"))))
    L.append(row("goal embedding", "", "", "", mr(g("discovery", "goal_embedding", "dla"))))
    sel = Counter(c for s in seeds for c in R[s]["selected"])
    L += ["", "## Selected components (discovery patch ≥ 0.3)", "", "Per model: " + "; ".join(f"{s}: {', '.join(R[s]['selected']) or 'none'}" for s in seeds) + ".", "",
          "Times selected over the ten models: " + ", ".join(f"{c} {n}" for c, n in sel.most_common()) + ".", ""]
    L += ["## Groups", ""]
    L += head("group", "discovery patch", "test patch", "test / discovery", "test restore", "test donor-optimal after patch")
    for k in GROUPS:
        d, t = g("discovery", k, "patch"), g("test", k, "patch")
        L.append(row(k, mr(d), mr(t), mr(t / d), mr(g("test", k, "restore")), mr(g("test", k, "donor_optimal"))))
    L += ["", "### Selected group's test patch by goal pair", ""]
    pairs = sorted({p for s in seeds for p in R[s]["test"].get("selected", {}).get("by_goal_pair", {})})
    L += head("", *pairs)
    L.append(row("selected", *[mr(np.array([R[s]["test"].get("selected", {}).get("by_goal_pair", {}).get(p, np.nan) for s in seeds])) for p in pairs]))
    # decision rule
    d1 = sum(1 for s in seeds if R[s]["selected"])
    t, d = g("test", "selected", "patch"), g("discovery", "selected", "patch")
    nsel = np.array([len(R[s]["selected"]) for s in seeds])
    comp = g("test", "complement", "patch")
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("D1", "a component with discovery patch ≥ 0.3 in ≥ 8 of 10 models", f"{d1} of 10", "yes" if d1 >= 8 else "no"))
    L.append(row("D2", "selected group: test patch median ≥ 0.5 and ≥ 0.8 × discovery", f"{f(np.nanmedian(t))}; {f(np.nanmedian(t / d))}", "yes" if np.nanmedian(t) >= 0.5 and np.nanmedian(t / d) >= 0.8 else "no"))
    L.append(row("D3", "≤ 4 selected and complement's test patch ≤ 0.25", f"{f(np.median(nsel), 0)}; {f(np.nanmedian(comp))}", "yes" if np.median(nsel) <= 4 and np.nanmedian(comp) <= 0.25 else "no"))
    ph = OUT / "posthoc.json"
    if ph.exists():
        P = json.load(open(ph))
        L += ["", "## Post hoc: ratio-of-means transfer (1 − mean TV(patched, donor) / mean TV(recipient, donor)), test cells", ""]
        L += head("component or group", "patch", "restore")
        for k in [c for c in COMPS if int(c[1]) >= 1] + list(GROUPS):
            pv = np.array([P[s].get(k, {}).get("patch", np.nan) for s in seeds]); rv = np.array([P[s].get(k, {}).get("restore", np.nan) for s in seeds])
            L.append(row(k, mr(pv), mr(rv)))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
