"""maze20: the design probe (no network). The hand-drawn 20 x 20 maze with its goals: the additive ceiling with the
cell known (the design criterion), the goal-blind ceiling, the 2 x 2 state-goal reversals, the per-cell error map of
the best additive rule, the aliasing of the structural symbols, and the reference policies on the partially observed
task (oracle, QMDP, QMDP with lookahead, most likely cell, random).

    .venv/bin/python studies/7_information_seeking/maze20/design.py              # writes design.md, design.json
    .venv/bin/python studies/7_information_seeking/maze20/design.py --search     # also: the hardest goal placement
                                                                                   search from scratch (minutes, GPU)
"""

from __future__ import annotations

import argparse, json
from pathlib import Path

import numpy as np
import torch

from goalgeo import bigmaze as BM, maze20 as M
from goalgeo.maze20 import GOAL_LETTERS as GL

HERE = Path(__file__).resolve().parent
N_EPISODES = 20000


def references(maze, dev="cuda"):
    t = BM.Sim(maze, dev)
    out = {}
    for name in ("oracle", "qmdp2", "qmdp", "mls", "random"):
        gen = torch.Generator(device=dev); gen.manual_seed(7)
        beh = BM.uniform(gen) if name == "random" else getattr(BM, name)
        b = BM.rollout(None, t, N_EPISODES, gen, behaviour=beh, record=name == "qmdp")
        out[name] = BM.summarize(b, t)[0]
        if name == "qmdp":
            e = BM.entropy(b.belief)
            out["entropy_start"], out["entropy_mean"] = float(e[:, 0].mean()), float(e[b.alive].mean())
            out["pmax_mean"] = float(b.belief.max(-1).values[b.alive].mean())
    out["dist_mean"] = float(t.dist[:, t.starts].mean()); out["dist_max"] = float(t.dist[:, t.starts].max())
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--search", action="store_true")
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--milp-seconds", type=float, default=1800)
    args = ap.parse_args()
    maze = M.the_maze()
    goals = list(maze.goals)
    D = M.all_distances(maze)
    res = dict(rows=maze.rows, n=maze.n, goals=goals, landmarks=list(maze.landmarks))

    ex = M.ceiling_exact(maze, goals, D, time_limit=args.milp_seconds)
    fit, _ = M.ceiling(maze, [goals], D, restarts=8, steps=3000, device=args.device)
    ref, err_fit = M.ceiling(maze, [goals], D, restarts=8, steps=3000, device=args.device, refine_rounds=8)
    err = ex["errors"] if ex["incumbent"] is not None and ex["incumbent"] >= ref[0] else err_fit[0]
    add = max(ex["incumbent"] or 0, float(ref[0]))
    blind, _ = M.ceiling(maze, [goals], D, restarts=2, steps=3000, additive=False, device=args.device, refine_rounds=0)
    blind_ex = M.ceiling_exact_blind(maze, goals, D)
    rev, rev_cells = M.reversals(maze, goals, D)
    rev_examples = M.reversal_examples(maze, goals, D)
    deg = np.array([len({int(x) for x in maze.nxt[s] if x != s}) for s in range(maze.n)])
    opt, keep = M.optimal_moves(maze, goals, D)
    unique = float((opt.sum(-1) == 1)[keep].mean())
    res.update(additive=add, additive_exact=ex["exact"], additive_upper=ex["upper"], additive_gradient_fit=float(fit[0]), additive_refined_fit=float(ref[0]),
               milp_seconds=ex["seconds"], goal_blind=blind_ex, reversals=rev, reversal_cells=rev_cells, unique_optimal=unique,
               reversal_examples=rev_examples,
               errors_by_degree={int(d): float(err[deg == d].mean() / len(goals)) for d in np.unique(deg)},
               degree_counts={int(d): int((deg == d).sum()) for d in np.unique(deg)})
    # the ceiling of the existing mazes, for the same table
    big = BM.make(pairs=1, eps=0.4)
    bx = M.ceiling_exact(big, list(big.goals))
    res["maze10_additive"], res["maze10_goal_blind"] = bx["incumbent"], M.ceiling_exact_blind(big, list(big.goals))
    res["maze10_reversals"] = M.reversals(big, list(big.goals))
    # aliasing: cells per symbol
    res["cells_per_symbol"] = {int(s): int((maze.sym == s).sum()) for s in np.unique(maze.sym)}
    res["references"] = references(maze, args.device)
    if args.search:
        g, a, seen = M.hardest_goals(maze, len(goals), rounds=8, pop=384, D=D, verbose=True, device=args.device)
        res["search"] = dict(hardest=g, ceiling=float(a), evaluated=len(seen))

    r = res["references"]; c = lambda k: f"{r[k]['ret']:.3f} ({r[k]['success']:.2f})"
    L = ["# maze20: design probe", "",
         f"Generated by `design.py`. The hand-drawn maze, {maze.n} open cells in a 20 x 20 box (letters: goals, `*`: landmarks, `#`: walls):", "",
         "```", M.draw(maze).replace("0", ".").replace("1", ".").replace("2", ".").replace("3", "."), "```", "",
         "Structural symbols (0 N-S corridor, 1 E-W corridor, 2 corner or dead end, 3 junction; `*` landmarks, noiseless):", "",
         "```", M.draw(maze), "```", "",
         "## The additive ceiling (the cell known)", "",
         "The share of (cell, goal) decisions where the best rule of each form picks a shortest-path move. The additive ceiling is solved exactly by "
         "mixed-integer programming where the solver finishes; otherwise its incumbent is a lower bound and its dual bound an upper bound. The "
         "additive-ceiling experiment's gradient fit, and that fit followed by exact-count coordinate ascent, are given for comparison: both are lower bounds "
         f"(for maze10 the gradient fit gave 0.926 against the exact 0.963).", "",
         "| maze and goals | additive ceiling argmax H(cell) + G(goal) | goal-blind ceiling argmax H(cell) | decisions with a unique shortest-path move | 2 x 2 reversals (cells in one) | gradient fit / refined fit |", "|---|---|---|---|---|---|",
         f"| **maze20, its {len(goals)} goals** | **{res['additive']:.3f}**" + ("" if ex["exact"] else f" (upper bound {ex['upper']:.3f}, {ex['seconds']:.0f} s)") +
         f" | {res['goal_blind']:.3f} | {unique:.2f} | {rev} ({rev_cells}/{maze.n}) | {res['additive_gradient_fit']:.3f} / {res['additive_refined_fit']:.3f} |",
         f"| maze10, its 4 goals (the additive-ceiling experiment) | {res['maze10_additive']:.3f} | {res['maze10_goal_blind']:.3f} | | {res['maze10_reversals'][0]} ({res['maze10_reversals'][1]}/{big.n}) | 0.926 / |", "",
         "## Paired state-goal reversals", "",
         "Pairs of cells s1, s2 and goals g1, g2 where the uniquely optimal move is a at (s1, g1) and (s2, g2) but b at (s1, g2) and (s2, g1): no "
         "additive rule satisfies all four. Every move below is the unique shortest-path move (ties excluded). Each row is one such pattern, with the "
         "number of cells on either side that take part with every cell on the other side:", "",
         "| goals | cells needing (a, b) | example | cells needing (b, a) | example |", "|---|---|---|---|---|"] + [
         f"| {GL[e['g1']]}, {GL[e['g2']]}: ({e['a']}, {e['b']}) | {e['n_ab']} | {e['cell_ab']} | {e['n_ba']} | {e['cell_ba']} |" for e in rev_examples[:12]] + ["",
         "Errors of the best additive rule per decision, by the cell's number of exits: " +
         ", ".join(f"{d} exits ({res['degree_counts'][d]} cells): {res['errors_by_degree'][d]:.2f}" for d in res["degree_counts"]) + ".", "",
         "Where the best additive rule fails (digit: goals, of " + str(len(goals)) + ", whose shortest-path move it misses at that cell):", "",
         "```", M.draw(maze, err[0]), "```", ""]
    if args.search:
        s = res["search"]
        L += [f"Hardest goal placement found by local search over {s['evaluated']} goal sets: ceiling {s['ceiling']:.3f} at cells {s['hardest']} "
              f"({[maze.cells[i] for i in s['hardest']]}).", ""]
    L += ["## The partially observed task (references on " + str(N_EPISODES) + " episodes)", "",
          "Cells per symbol: " + ", ".join(f"{k}: {v}" for k, v in res["cells_per_symbol"].items()) + f"; noise {maze.eps}; {maze.H} moves, discount {maze.gamma}.", "",
          "| oracle return (success) | QMDP + lookahead | QMDP | most likely cell | random | posterior entropy: start / mean under QMDP | most likely cell's probability | path to the goal: mean / longest |", "|---|---|---|---|---|---|---|---|",
          f"| {c('oracle')} | {c('qmdp2')} | {c('qmdp')} | {c('mls')} | {c('random')} | {r['entropy_start']:.2f} / {r['entropy_mean']:.2f} | {r['pmax_mean']:.2f} | {r['dist_mean']:.1f} / {r['dist_max']:.0f} |", ""]
    (HERE / "design.md").write_text("\n".join(L))
    (HERE / "design.json").write_text(json.dumps(res, indent=1))
    print("\n".join(L))


if __name__ == "__main__":
    main()
