"""Round 32: tables and the registered decision rule from results.json.

    .venv/bin/python rounds/r32_direct_belief_edit/tables.py            # writes tables.md
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from scipy.stats import wilcoxon

OUT = Path(__file__).resolve().parent
f = lambda x, d=3: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
mr = lambda xs, d=3: f"{f(np.median(xs), d)} ({f(np.min(xs), d)}–{f(np.max(xs), d)})"
p_gt = lambda a, b: float(wilcoxon(a, b, alternative="greater", method="exact").pvalue)
fp = lambda p: "< 0.001" if p < 0.001 else f"{p:.3f}"
KINDS = (("none", "none"), ("whole", "whole direct-route replacement"), ("encoding", "**encoding (shared E)**"), ("enc_brief", "encoding, brief's offset form"),
         ("enc_goal", "encoding, goal-specific E_g"), ("rotated", "rotated encoding"), ("pca", "PCA-13 patch"), ("random", "random rank-13 patch"), ("hybrid", "hybrid (B under g, natural)"))


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(runs[s], p)) is None else x for s in seeds], dtype=float)
    c = R["counts"]
    L = ["# Round 32 tables", "", "Generated by `rounds/r32_direct_belief_edit/tables.py`. Round 23's ten reward models; the goal token's state entering "
         f"block 1. Main pairs {c['main_pairs']}, one-step agreeing {c['onestep_pairs']}, main pairs with four equivalent recipients {c['equivalent_pairs']}. "
         "Median (range) over the ten models of rates pooled over each model's cells.", ""]
    L += ["## Encoding fit (held-out)", ""]
    L += head("encoding", "R²", "R² within (goal, length)")
    for k, kl in (("shared", "shared: c_{g,L} + E b"), ("brief_offset", "brief's form: c_g + E b"), ("goal_specific", "goal-specific: c_{g,L} + E_g b"), ("offsets_only", "offsets c_{g,L} only")):
        L.append(row(kl, mr(v("fit", k, "r2")), mr(v("fit", k, "r2_within_goal_length")) if k != "offsets_only" else "0 by construction"))
    L += ["", "Goal-specific maps against the shared one, ‖C(E_g − E)‖² / ‖C E‖² (C: sum-zero belief directions): " +
          ", ".join(f"G{g + 1} {mr(np.array([runs[s]['fit']['goal_map_distance'][g] for s in seeds]))}" for g in range(3)), ""]
    es = lambda *p: v("edit_stats", *p)
    L += ["Edit against the actual direct-route difference (main pairs, all goals): shared E: norm ratio " + mr(es("encoding", "norm_ratio")) + ", cosine " + mr(es("encoding", "cosine")) +
          ", residual share " + mr(es("encoding", "residual_share")) + "; goal-specific: norm ratio " + mr(es("enc_goal", "norm_ratio")) + ", cosine " + mr(es("enc_goal", "cosine")) +
          ", residual share " + mr(es("enc_goal", "residual_share")) + ". PCA-13 holds " + mr(es("pca_share")) + " of the squared difference, a random rank-13 subspace " + mr(es("random_share")) + ".", ""]
    # main change cells
    L += ["## Main pairs, change cells", ""]
    L += head("edit", "donor-optimal", "gain over none", "as hybrid", "recipient-optimal", "regret at B", "T (of hybrid)", "S (of whole)", "pooled logit projection")
    ch = lambda k, m: v("main", "change", k, m)
    for k, kl in KINDS:
        L.append(row(kl, mr(ch(k, "donor_optimal")), mr(ch(k, "donor_optimal") - ch("none", "donor_optimal")), mr(ch(k, "as_hybrid")), mr(ch(k, "recipient_optimal")),
                     mr(ch(k, "regret_donor")), mr(ch(k, "transfer_hybrid"), 2) if k != "hybrid" else "1", mr(ch(k, "share_of_whole"), 2) if k != "hybrid" else "—",
                     mr(ch(k, "projection"), 2) if k != "hybrid" else "1"))
    L += ["", "### Per goal (change cells): donor-optimal", ""]
    L += head("edit", "G1", "G2", "G3")
    for k, kl in KINDS:
        L.append(row(kl, *[mr(v("main", "by_goal", f"G{g + 1}", k, "donor_optimal")) for g in range(3)]))
    L += ["", f"Change cells per goal (seed 0): " + ", ".join(f"G{g + 1} {runs[seeds[0]]['main']['by_goal'][f'G{g + 1}']['n']}" for g in range(3)), ""]
    # goal-dependent pairs
    gd = lambda k, m: v("main", "goal_dependent", k, m)
    L += ["## Goal-dependent pairs (B needs different actions under two goals where the change matters)", "", f"Pairs: {int(np.median(v('main', 'goal_dependent', 'n')))}.", ""]
    L += head("edit", "donor-optimal under every change goal", "donor-optimal under two goals with different actions")
    for k, kl in KINDS:
        L.append(row(kl, mr(gd(k, "right_every_change_goal")), mr(gd(k, "right_distinct_actions"))))
    # preserve
    pr = lambda k, m: v("main", "preserve", k, m)
    L += ["", "## Preserve cells (posteriors differ, optimal sets identical)", "", f"Cells: {int(np.median(v('main', 'preserve', 'n')))}.", ""]
    L += head("edit", "still optimal", "harm (none − edit)")
    for k, kl in KINDS:
        L.append(row(kl, mr(pr(k, "optimal")), mr(pr(k, "harm")) if k != "hybrid" else "—"))
    # one-step agreeing
    os_ = lambda k, m: v("onestep", "change", k, m)
    L += ["", "## One-step agreeing pairs, change cells", "", f"Cells: {int(np.median(v('onestep', 'change', 'n')))}.", ""]
    L += head("edit", "donor-optimal", "gain over none", "as hybrid", "T (of hybrid)", "S (of whole)")
    for k, kl in KINDS:
        L.append(row(kl, mr(os_(k, "donor_optimal")), mr(os_(k, "donor_optimal") - os_("none", "donor_optimal")), mr(os_(k, "as_hybrid")),
                     mr(os_(k, "transfer_hybrid"), 2) if k != "hybrid" else "1", mr(os_(k, "share_of_whole"), 2) if k != "hybrid" else "—"))
    # equivalent recipients
    eq = lambda k, m: v("equivalent", "change", k, m)
    L += ["", "## Equivalent recipients: the same belief change on four histories with the recipient's posterior", "", f"Pairs: {int(np.median(v('equivalent', 'n_pairs')))}; change cells.", ""]
    L += head("edit", "all four donor-optimal", "mean donor-optimal", "pairwise agreement", "variance between belief changes")
    for k, kl in KINDS:
        L.append(row(kl, mr(eq(k, "all_donor_optimal")), mr(eq(k, "donor_optimal")), mr(eq(k, "agreement")), mr(eq(k, "between_share"), 2)))
    # decision rule
    D = lambda k: ch(k, "donor_optimal")
    gain = lambda k: D(k) - D("none")
    S_enc = ch("encoding", "share_of_whole")
    ratio_gd = gd("encoding", "right_every_change_goal") / gd("whole", "right_every_change_goal")
    og = lambda k: os_(k, "donor_optimal") - os_("none", "donor_optimal")
    ratio_eq = eq("encoding", "all_donor_optimal") / eq("whole", "all_donor_optimal")
    crit = []
    Fv = np.median(v("fit", "shared", "r2_within_goal_length"))
    crit.append(("F", "shared R² within (goal, length) ≥ 0.5", f(Fv), Fv >= 0.5))
    c1 = np.median(S_enc) >= 0.75 and np.median(gain("encoding")) >= 0.25
    crit.append(("C1 transfer", "S(encoding) ≥ 0.75 and gain ≥ 0.25", f"S {f(np.median(S_enc), 2)}; gain {f(np.median(gain('encoding')))}", c1))
    p2 = p_gt(gd("encoding", "right_every_change_goal"), gd("rotated", "right_every_change_goal"))
    c2 = np.median(ratio_gd) >= 0.75 and p2 < 0.05
    crit.append(("C2 goal-dependent", "every change goal right: encoding ≥ 0.75 × whole, above rotated",
                 f"{f(np.median(gd('encoding', 'right_every_change_goal')))} / {f(np.median(gd('whole', 'right_every_change_goal')))} = {f(np.median(ratio_gd), 2)} ×; p {fp(p2)}", c2))
    h = np.median(pr("encoding", "harm"))
    crit.append(("C3 preservation", "harm(encoding) ≤ 0.05", f(h), h <= 0.05))
    p4 = p_gt(os_("encoding", "donor_optimal"), os_("rotated", "donor_optimal"))
    r4 = np.median(og("encoding") / og("whole"))
    crit.append(("C4 beyond one-step", "one-step agreeing gain ≥ 0.5 × whole's, above rotated", f"{f(r4, 2)} ×; p {fp(p4)}", r4 >= 0.5 and p4 < 0.05))
    p5r, p5q = p_gt(D("encoding"), D("rotated")), p_gt(D("encoding"), D("random"))
    rot_half = np.median(gain("rotated")) <= 0.5 * np.median(gain("encoding"))
    pca_d = np.median(D("pca") - D("encoding"))
    c5a = p5r < 0.05 and p5q < 0.05 and rot_half
    crit.append(("C5 specificity (a)", "encoding above rotated and random; rotated's gain ≤ half", f"p {fp(p5r)}, {fp(p5q)}; rotated gain {f(np.median(gain('rotated')))}", c5a))
    crit.append(("C5 specificity (b)", "D(pca) − D(encoding) ≤ 0.05", f(pca_d), pca_d <= 0.05))
    agr = np.median(eq("encoding", "agreement") - eq("none", "agreement"))
    c6 = np.median(ratio_eq) >= 0.75 and agr >= -0.05
    crit.append(("C6 equivalent histories", "all four donor-optimal ≥ 0.75 × whole; agreement ≥ none − 0.05", f"{f(np.median(ratio_eq), 2)} ×; agreement − none {f(agr)}", c6))
    c7d = np.median(D("encoding") - D("enc_goal"))
    crit.append(("C7 shared map suffices", "D(encoding) ≥ D(enc_goal) − 0.05", f(c7d), c7d >= -0.05))
    S_goal = np.median(ch("enc_goal", "share_of_whole"))
    crit.append(("(reading) enc_goal meets C1", "S(enc_goal) ≥ 0.75 and gain ≥ 0.25", f"S {f(S_goal, 2)}; gain {f(np.median(gain('enc_goal')))}",
                 S_goal >= 0.75 and np.median(gain("enc_goal")) >= 0.25))
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    for a, b, cv, ok in crit:
        L.append(row(a, b, cv, "**yes**" if ok else "no"))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


def _get(d, p):
    for k in p:
        d = d[k]
    return d


if __name__ == "__main__":
    main()
