"""The additive-code experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/5_goal_belief_mechanism/additive_code/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
ACTIONS = ("a0", "a1", "a2", "a3")


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(runs[s], p)) is None else x for s in seeds], dtype=float)
    c = R["cells"]
    L = ["# The additive-code experiment tables", "", "Generated by `studies/5_goal_belief_mechanism/additive_code/tables.py`. The observation-prediction experiment's ten reward models; logits at the goal token; held-out histories "
         f"({c['histories']}) under each goal; goal-dependent cells {c['goal_dependent']} of {c['all']}. Median (range) over the ten models.", ""]
    L += ["## Additive code: logits ≈ H(h) + G(g, L)", ""]
    L += head("", "value")
    L.append(row("additive share of the logits' goal dependence", mr(v("additive_share_of_goal_dependence"))))
    L.append(row("all cells: optimal, natural / additive", f"{mr(v('all_cells', 'natural'))} / {mr(v('all_cells', 'additive'))}"))
    L.append(row("**goal-dependent cells: optimal, natural / additive**", f"{mr(v('goal_dependent', 'natural'))} / {mr(v('goal_dependent', 'additive'))}"))
    L.append(row("goal-dependent cells: additive / natural", mr(v("goal_dependent", "additive") / v("goal_dependent", "natural"))))
    L.append(row("goal-dependent cells: same action, natural and additive", mr(v("goal_dependent", "agree"))))
    L.append(row("need (natural optimal, additive not) / spoil (the reverse)", f"{mr(v('need', 'share'))} / {mr(v('need', 'spoil'))}"))
    L += ["", "## Additive solvability (solver and G): which cells need the interaction?", ""]
    L += head("", "value")
    L.append(row("histories whose posterior is additively solvable", mr(v("solvable_share_histories"))))
    L.append(row("goal-dependent cells in unsolvable posteriors", mr(v("need", "unsolvable_share_of_dep_cells"))))
    L.append(row("P(need | unsolvable) / P(need | solvable)", f"{mr(v('need', 'p_need_given_unsolvable'))} / {mr(v('need', 'p_need_given_solvable'))}"))
    L.append(row("share of all need cells in unsolvable posteriors", mr(v("need", "share_of_need_in_unsolvable"))))
    L.append(row("unsolvable: optimal, natural / additive", f"{mr(v('need', 'natural_given_unsolvable'))} / {mr(v('need', 'additive_given_unsolvable'))}"))
    L.append(row("solvable: optimal, natural / additive", f"{mr(v('need', 'natural_given_solvable'))} / {mr(v('need', 'additive_given_solvable'))}"))
    L += ["", "## What H holds", ""]
    L.append(f"H ranks the union of the three goals' optimal actions on top in {mr(v('H', 'union_on_top'))} of histories (union size {mr(v('H', 'union_size_mean'), 2)} of 4).")
    L += ["", "Goal bias G(g, L) for L = 2, seed 0 (centred logits; actions in the model's order):", ""]
    G = np.array(runs[seeds[0]]["G"])
    L += head("goal", *ACTIONS)
    for g in range(3):
        L.append(row(f"G{g + 1}", *[f(x, 2) for x in G[g, 2]]))
    # decision rule
    ad = np.median(v("goal_dependent", "additive") / v("goal_dependent", "natural"))
    pu, ps = v("need", "p_need_given_unsolvable"), v("need", "p_need_given_solvable")
    pEX = p_gt(pu, ps)
    ex = np.median(pu / ps)
    U = np.median(v("H", "union_on_top"))
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**AD**", "goal-dependent: additive ≥ 0.9 × natural", f(ad), yes(ad >= 0.9)))
    L.append(row("**EX**", "P(need | unsolvable) ≥ 3 × P(need | solvable), above it", f"{f(ex, 2)} ×; p {fp(pEX)}", yes(ex >= 3 and pEX < 0.05)))
    L.append(row("**U**", "H's top actions are the goals' optimal actions ≥ 0.7", f(U), yes(U >= 0.7)))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
