"""The self-value-interaction experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/5_goal_belief_mechanism/self_value_interaction/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
SITES = (("u", "u = ln2(m): MLP input"), ("m", "m: before the layer norm"), ("z", "z: after block 0's MLP"))
SWAPS = (("selfv", "own value from g₂"), ("query", "query from g₂"), ("goal", "natural under g₂ (full change)"))


def main():
    runs = json.load(open(OUT / "results.json"))["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    L = ["# The self-value-interaction experiment tables", "", "Generated by `studies/5_goal_belief_mechanism/self_value_interaction/tables.py`. The observation-prediction experiment's ten reward models; held-out histories × six ordered goal pairs. "
         "Median (range) over the ten models.", ""]
    L += ["## Size of the goal's main effect and of the goal × belief part, per site", ""]
    L += head("site", "|dJ|² / |dM|²", "decoder R² (b from the state)", "decoded difference of main pairs (L1)")
    for x, xl in SITES:
        L.append(row(xl, mr(v("sites", x, "interaction_over_main")), mr(v("decoder_r2", x)), mr(v("sites", x, "decoded_pair_difference"))))
    for x, xl in SITES:
        L += ["", f"## {xl}", ""]
        L += head("swap", "α_M", "α_J", "ρ_M (of full)", "ρ_J (of full)", "share of D explained", "decoded posterior change (L1)", "change in shared-code subspace / full's")
        ga, gj, gs = v("sites", x, "goal", "alpha_M"), v("sites", x, "goal", "alpha_J"), v("sites", x, "goal", "shared_subspace_size")
        for k, kl in SWAPS:
            g = lambda m: v("sites", x, k, m)
            L.append(row(kl, mr(g("alpha_M"), 2), mr(g("alpha_J"), 2), mr(g("alpha_M") / ga, 2), mr(g("alpha_J") / gj, 2), mr(g("explained"), 2),
                         mr(g("decoded_change")), mr(g("shared_subspace_size") / gs, 2)))
    # decision rule
    rho = lambda x, k, c: v("sites", x, k, f"alpha_{c}") / v("sites", x, "goal", f"alpha_{c}")
    rJ, rM, rZ, rQ = rho("u", "selfv", "J"), rho("u", "selfv", "M"), rho("z", "selfv", "J"), rho("u", "query", "J")
    Fv = (v("sites", "u", "selfv", "decoded_change") - v("sites", "u", "goal", "decoded_change")) / v("sites", "u", "decoded_pair_difference")
    pQ = p_gt(rQ, rJ)
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**J** (at u)", "ρ_J(selfv) ≥ 0.5", f(np.median(rJ), 2), yes(np.median(rJ) >= 0.5)))
    L.append(row("**M** (at u)", "ρ_M(selfv) ≥ 0.75", f(np.median(rM), 2), yes(np.median(rM) >= 0.75)))
    L.append(row("**F** (at u)", "decoded change(selfv) − (goal) ≤ 0.1 × pair difference", f"{f(np.median(Fv), 3)} ×", yes(np.median(Fv) <= 0.1)))
    L.append(row("**Z** (at z)", "ρ_J(selfv) ≥ 0.5", f(np.median(rZ), 2), yes(np.median(rZ) >= 0.5)))
    L.append(row("Q (comparison, at u)", "ρ_J(query), above selfv", f"{f(np.median(rQ), 2)}; p {fp(pQ)}", ""))
    ratio_zu = v("sites", "z", "interaction_over_main") / v("sites", "u", "interaction_over_main")
    L += ["", f"|dJ|²/|dM|² at z over at u: {mr(ratio_zu, 2)}.", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
