"""The random-spawns experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/6_hard_cases_and_tasks/random_spawns/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
ARMS = (("four", "four corridor cells"), ("all", "all 11 non-goal cells"))
ROWS = (("natural", "natural optimal"), ("additive", "additive optimal"), ("agree", "same action"), ("additive_share", "additive share of the logits' goal dependence"),
        ("unsolvable_share", "additively unsolvable share"), ("natural_unsolvable", "natural optimal, unsolvable"), ("additive_unsolvable", "additive optimal, unsolvable"),
        ("natural_solvable", "natural optimal, solvable"), ("additive_solvable", "additive optimal, solvable"))


def main():
    R = json.load(open(OUT / "results.json"))
    seeds = sorted(R["four"]["runs"], key=lambda s: int(s[4:]))
    v = lambda arm, *p: np.array([np.nan if (x := _get(R[arm]["runs"][s], p)) is None else x for s in seeds], dtype=float)
    L = ["# The random-spawns experiment tables", "",
         "Generated by `studies/6_hard_cases_and_tasks/random_spawns/tables.py`. Ten reward-trained models per arm; 8 moves, prefix 0–2. Decisions of the solver with "
         "20 % random moves, replayed under all three goals; test half of the episodes. Median (range).", "",
         "## Task and competence", ""]
    L += head("arm", "graph nodes", "decisions (first)", "solver success", "V*", "greedy regret", "regret / V*", "optimal-move rate", "success")
    for a, al in ARMS:
        r = R[a]
        L.append(row(al, r["nodes"], f"{r['decisions']} ({r['first']})", f(r["solver_success"]), f(r["v_star"]), mr(v(a, "competence", "regret"), 4),
                     mr(v(a, "competence", "regret") / v(a, "competence", "v_star")), mr(v(a, "competence", "opt_rate")), mr(v(a, "competence", "success"))))
    for part, pl in (("all", "all decisions"), ("first", "first decision (at the reveal)"), ("later", "later decisions")):
        L += ["", f"## Additive code, goal-dependent cells: {pl}", ""]
        L += head("", *[al for _, al in ARMS], *[f"solver's Q*, {a}" for a, _ in ARMS])
        L.append(row("goal-dependent cells", *[R[a]["solver"][part]["goal_dependent_cells"] for a, _ in ARMS], "", ""))
        for k, kl in ROWS:
            L.append(row(kl, *[mr(v(a, part, k)) for a, _ in ARMS], *[f(R[a]["solver"][part][k]) for a, _ in ARMS]))
        L.append(row("additive / natural", *[mr(v(a, part, "additive") / v(a, part, "natural")) for a, _ in ARMS], "", ""))
    ratio = {a: v(a, "all", "additive") / v(a, "all", "natural") for a, _ in ARMS}
    rel = {a: v(a, "competence", "regret") / v(a, "competence", "v_star") for a, _ in ARMS}
    rep = np.median(ratio["four"]) >= 0.9
    ad = np.median(ratio["all"]) >= 0.9 and np.median(v("all", "all", "agree")) >= 0.9
    pD = p_gt(ratio["four"], ratio["all"] + 0.05)
    drop = np.median(ratio["four"] - ratio["all"]) >= 0.05 and pD < 0.05
    learn = np.median(rel["all"]) <= 2 * np.median(rel["four"])
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**REP**", "four arm: additive ≥ 0.9 × natural", f(np.median(ratio["four"])), yes(rep)))
    L.append(row("**AD-all**", "all arm: additive ≥ 0.9 × natural, same action ≥ 0.9", f"{f(np.median(ratio['all']))}; {f(np.median(v('all', 'all', 'agree')))}", yes(ad)))
    L.append(row("**DROP**", "ratio lower in the all arm by ≥ 0.05", f"{f(np.median(ratio['four'] - ratio['all']))}; p {fp(pD)}", yes(drop)))
    L.append(row("**LEARN**", "all arm: regret / V* ≤ 2 × the four arm's", f"{f(np.median(rel['all']))} against {f(np.median(rel['four']))}", yes(learn)))
    reading = ("the shorter setting itself changes the result" if not rep else "the additive code was a consequence of the four spawns" if not ad else
               "mostly additive, with more interaction under random spawns" if drop else "the additive code does not depend on the spawns")
    sf, sa = R["four"]["solver"]["all"], R["all"]["solver"]["all"]
    d_ = v("all", "all", "natural_unsolvable") - v("all", "all", "additive_unsolvable")
    L += ["", f"**Registered reading: {reading}{'' if learn else ' (LEARN failed: competence differs)'}.**", "",
          f"Solver reference (E2): the best additive move fails on {f(1 - sf['additive'])} of goal-dependent cells in the four arm and {f(1 - sa['additive'])} in the all arm.",
          f"E6: natural − additive in unsolvable posteriors, all arm: {mr(d_)}.", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
