"""The navigate-commit experiment, step 1: which regimes does the exact optimal policy have, as a function of cost, horizon and
reliability? Run over every layout (420 ordered station pairs) and every start cell (25), before any model
is trained. Writes tune.json and tune.md.

For each (layout, start) the policy class is restricted to at most 0, 1 or 2 queries and solved exactly,
so "how many queries are optimal" is a statement about values and does not depend on tie-breaking:
    zero  : V0 = V2            one : V0 < V1 = V2            two : V1 < V2
A case is "meaningful" when the wrong number of queries costs at least MARGIN in expected return: for
zero, the best policy that queries at least once loses that much; for one, V1 - V0; for two, V2 - V1.
One optimal policy is rolled out to find adaptive cases (the number of queries depends on a report) and
reroutes (after a query, the optimal action sets for the two possible reports are disjoint)."""

from __future__ import annotations

import argparse, json
from pathlib import Path

import numpy as np

from goalgeo import navcommit as NC

HERE = Path(__file__).resolve().parent
MARGIN = 0.02
FROZEN = dict(n=5, H=12, c=0.025, q=0.8)
Q_GRID = (0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95)


def forced_query_value(n, H, c, h, v, sol):
    """Value from the start of the best policy that makes at least one query."""
    i, nxt = np.arange(len(h)), NC.move_table(n)
    F = np.full((len(h), H + 1, n * n), -np.inf)
    for k in range(1, H + 1):
        for a in range(4):
            ok = np.where(nxt[:, a] >= 0)[0]
            F[:, k][:, ok] = np.maximum(F[:, k][:, ok], -c + F[:, k - 1][:, nxt[ok, a]])
        F[i, k, h] = np.maximum(F[i, k, h], sol.Q[i, k, h, 0, 0, NC.QUERY])
        F[i, k, v] = np.maximum(F[i, k, v], sol.Q[i, k, v, 0, 0, NC.QUERY])
    return F[:, H]


def regimes(n, H, c, qh, qv, tol=NC.TIE):
    h, v = NC.all_layouts(n)
    sols = [NC.solve(n, H, c, h, v, qh, qv, max_queries=m) for m in (0, 1, 2)]
    V0, V1, V2 = (s.V[:, H, :, 0, 0] for s in sols)                       # [layout, start]
    zero, two = V2 - V0 <= tol, V2 - V1 > tol
    one = ~zero & ~two
    sol, opt = sols[2], sols[2].optimal()
    F = forced_query_value(n, H, c, h, v, sol)
    adaptive = np.zeros(V0.shape, bool); nq = 0; nre = 0
    for b in range(len(h)):
        for s in range(n * n):
            leaves = NC.rollout_tree(sol, b, s, opt=opt)
            adaptive[b, s] = len({l["queries"] for l in leaves}) > 1
            for (k, p, sh, sv) in {q for l in leaves for q in l["qstates"]}:
                if p == h[b]:
                    o0, o1 = opt[b, k - 1, p, 1, sv], opt[b, k - 1, p, 2, sv]
                else:
                    o0, o1 = opt[b, k - 1, p, sh, 1], opt[b, k - 1, p, sh, 2]
                nq += 1; nre += not (o0 & o1).any()
    out = dict(H=H, c=c, qh=qh, qv=qv, zero=zero.mean(), one=one.mean(), two=two.mean(),
               zero_meaningful=(zero & (V0 - F >= MARGIN - tol)).mean(),
               one_meaningful=(one & (V1 - V0 >= MARGIN - tol)).mean(),
               two_meaningful=(V2 - V1 >= MARGIN - tol).mean(),
               adaptive=adaptive.mean(), reroute=nre / max(nq, 1), V_opt=V2.mean(), V_noquery=V0.mean())
    return {k: float(x) for k, x in out.items()}


COLS = ("H", "c", "qh", "qv", "zero", "one", "two", "zero_meaningful", "one_meaningful", "two_meaningful", "adaptive",
        "reroute", "V_opt", "V_noquery")


def table(rows):
    fmt = lambda k, x: f"{int(x)}" if k == "H" else f"{x:g}" if k in ("c", "qh", "qv") else f"{x:.3f}"
    return "\n".join(["| " + " | ".join(COLS) + " |", "|" + "---|" * len(COLS)] +
                     ["| " + " | ".join(fmt(k, r[k]) for k in COLS) + " |" for r in rows])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(HERE))
    ap.add_argument("--quick", action="store_true")
    a = ap.parse_args()
    out = Path(a.out); out.mkdir(parents=True, exist_ok=True)
    f = FROZEN
    if a.quick:
        sweep, qs = [(20, 0.02, 0.8)], [(0.6, 0.6)]
    else:
        sweep = [(20, 0.02, 0.8)] + [(H, c, q) for q in (0.8, 0.9) for H in (10, 12, 14, 16, 20)
                                     for c in (0.02, 0.025, 0.03, 0.04, 0.05)]
        qs = [(a_, b_) for a_ in Q_GRID for b_ in Q_GRID if a_ <= b_]
    res = dict(margin=MARGIN, frozen=f,
               sweep=[regimes(f["n"], H, c, q, q) for H, c, q in sweep],
               frozen_fixed_q=regimes(f["n"], f["H"], f["c"], f["q"], f["q"]),
               frozen_q_grid=[regimes(f["n"], f["H"], f["c"], qh, qv) for qh, qv in qs])
    (out / "tune.json").write_text(json.dumps(res, indent=1))
    md = ["# The navigate-commit experiment: regimes of the exact optimal policy", "",
          f"Generated by `studies/3_reward_trained_agents/navigate_commit/tune.py`. Shares are over 420 layouts x 25 starts. "
          f"Meaningful: the wrong number of queries costs at least {MARGIN} in expected return. "
          "Reroute: share of optimal queries after which the two possible reports have disjoint optimal action sets.", "",
          "## Frozen configuration, fixed q", "", f"n = {f['n']}, H = {f['H']}, c = {f['c']}, q = {f['q']}", "",
          table([res["frozen_fixed_q"]]), "",
          "## Sweep (first row: the brief's pilot defaults)", "", table(res["sweep"]), "",
          "## Frozen H and c over the reliability grid (q_h <= q_v; the mirrored half is the same by symmetry of the "
          "layout set)", "", table(res["frozen_q_grid"]), ""]
    (out / "tune.md").write_text("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()
