"""The belief-edit experiment: tables from results.json.

    .venv/bin/python studies/3_reward_trained_agents/belief_edit/tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path("studies/3_reward_trained_agents/belief_edit")
REG = ("whole", "belief", "belief_rank", "complement", "random_subspace", "random_norm")
POST = ("pattern", "pattern_shift", "pattern_complement")
f = lambda x, d=2: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]


def main():
    r = json.load(open(OUT / "results.json")); R = r["runs"]
    L = ["# The belief-edit experiment tables", "", f"Generated by `studies/3_reward_trained_agents/belief_edit/tables.py`. {r['pairs']} recipient–donor pairs with matched prefix length: "
         f"{r['sets']['mode']} mode, {r['sets']['uncertainty']} uncertainty, {r['sets']['similar']} similar-posterior, {r['sets']['evidence']} with posteriors ≥ 0.5 apart "
         "(cross-goal). Edits `pattern`, `pattern_shift`, `pattern_complement` and every 'raw route removed' cross-goal number are post hoc.", "",
         "## 1. Validity at the interface (entering block 1)", ""] + head("model", "decoder R² (held out)", *[f"{k}: share of ‖x_B − x_A‖²" for k in ("belief", "random_subspace", "pattern", "pattern_shift")],
                                                                      *[f"{k}: decoded posterior, share of the way to the donor's" for k in ("belief", "complement", "random_subspace", "pattern", "pattern_shift", "pattern_complement")])
    for k, m in R.items():
        x = m["resid1"]
        L.append(row(k, f(x["decoder_r2"]), *[f(x["norm_share"][a]) for a in ("belief", "random_subspace", "pattern", "pattern_shift")],
                     *[f(x["interface_decoded_to_donor"][a]) for a in ("belief", "complement", "random_subspace", "pattern", "pattern_shift", "pattern_complement")]))
    for l in ("resid1", "resid2"):
        for cond in ("intact", "raw_route_ablated"):
            if l == "resid2" and cond != "intact":
                continue
            for meas, title in (("moved", "moved to the hybrid"), ("solver_gain", "gain on the solver's set for the donor's belief, share of the hybrid's"),
                                ("output_decoded_to_hybrid", "posterior decoded at the goal token's output, share of the way"), ("arbitrary", "probability moved to actions optimal for neither")):
                L += ["", f"## Edits entering block {l[-1]}, raw route {'intact' if cond == 'intact' else 'removed'}: {title} (mode / uncertainty pairs)", ""] + head("model", *REG, *POST, "similar-posterior donors: TV from base (whole)")
                for k, m in R.items():
                    c = m[l]["steps"]["0"][cond]
                    L.append(row(k, *[f"{f(c[e]['mode'].get(meas))} / {f(c[e]['uncertainty'].get(meas))}" for e in REG + POST], f(c["whole"]["similar"].get("tv_from_base"))))
    L += ["", "## Persistence: moved to the hybrid at later decisions (edits entering block 1, raw route intact; mode / uncertainty)", ""] + head("model", "edit", "reveal", "1 move later", "2", "4")
    for k, m in R.items():
        for e in ("whole", "belief", "pattern", "pattern_shift"):
            L.append(row(k, e, *[f"{f(m['resid1']['steps'][s]['intact'][e]['mode'].get('moved'))} / {f(m['resid1']['steps'][s]['intact'][e]['uncertainty'].get('moved'))}" for s in ("0", "1", "2", "4")]))
    for key, title in (("cross_goal", "raw route intact"), ("cross_goal_ablated", "raw route removed (post hoc)")):
        L += ["", f"## Cross-goal reuse, {title}: the same edited prefix states under each goal", "", "Per goal: moved to the hybrid for that goal.", ""] + \
            head("model", "goal", "pairs", "whole", "belief", "complement", "pattern", "pattern_shift", "pattern_complement", "random_subspace")
        for k, m in R.items():
            for g, v in m[key]["per_goal"].items():
                L.append(row(k, g, v["n"], *[f(v[e]) for e in ("whole", "belief", "complement", "pattern", "pattern_shift", "pattern_complement", "random_subspace")]))
        L += ["", "Both goals: among pairs where the hybrid's greedy action differs between the two goals and from the base's under each, the share in which the edited "
              "model takes the hybrid's action under both.", ""] + head("model", "goals", "pairs", "whole", "belief", "complement", "pattern", "pattern_shift", "pattern_complement", "random_subspace")
        for k, m in R.items():
            for g, v in m[key]["both"].items():
                L.append(row(k, g, v["n"], *[f(v[e]) for e in ("whole", "belief", "complement", "pattern", "pattern_shift", "pattern_complement", "random_subspace")]))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print(len(L), "lines")


if __name__ == "__main__":
    main()
