"""Tables and the per-cell profile figure of the H-simplex experiment, from results.json.

    .venv/bin/python studies/7_information_seeking/H_simplex/tables.py [--results PATH] [--out DIR]
"""

from __future__ import annotations

import argparse, json
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from goalgeo import bigmaze as BM

HERE = Path(__file__).resolve().parent
FORMS = ["step", "affine", "popt", "reach", "mix", "mix3", "mls", "affine+sharp", "affine+ent", "mlp", "history", "history_linear"]
LABEL = {"step": "step only", "affine": "affine in b (QMDP form, 55 × 4)", "popt": "belief-weighted optimal share, 4 × 4 map", "reach": "belief-weighted reachability, 4 × 4 map",
         "mix": "both (mix)", "mix3": "both, one slope each + action and step intercepts (mix3)", "mls": "table at the most likely cell", "affine+sharp": "affine + sharpened belief",
         "affine+ent": "affine + entropy-scaled profile", "mlp": "MLP on b (nonlinear-in-b ceiling)", "history": "MLP on b + prefix features", "history_linear": "ridge on b + prefix features"}


def med(xs):
    xs = [x for x in xs if x is not None and np.isfinite(x)]
    return (float(np.median(xs)), float(min(xs)), float(max(xs))) if xs else (float("nan"),) * 3


def f3(m):
    return f"{m[0]:.3f} ({m[1]:.3f}–{m[2]:.3f})"


def wilcoxon_greater(x, y):
    """Exact one-sided Wilcoxon signed-rank p for median(x - y) > 0 (ties dropped)."""
    from itertools import product
    d = np.array([a - b for a, b in zip(x, y)]); d = d[d != 0]
    if len(d) == 0:
        return 1.0
    r = np.argsort(np.argsort(np.abs(d))) + 1
    W = float(r[d > 0].sum())
    n = len(d)
    cnt = sum(1 for signs in product((0, 1), repeat=n) if float(sum(ri for ri, s_ in zip(r, signs) if s_)) >= W)
    return cnt / 2 ** n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=str(HERE / "results.json"))
    ap.add_argument("--out", default=str(HERE))
    a = ap.parse_args()
    res = json.load(open(a.results))
    out = Path(a.out); out.mkdir(parents=True, exist_ok=True)
    runs = list(res["runs"].values())
    L = ["# H on the belief simplex: tables", "", f"Generated by `tables.py` from `results.json`: {len(runs)} models, {res['n_episodes']} fit and {res['n_episodes']} test episodes each; "
         f"medians (min–max) over models.", ""]
    # A
    L += ["## A. Prediction of H on held-out decisions (R², pooled over the four centred numbers)", "", "| model of H | R² |", "|---|---|"]
    for k in FORMS:
        L.append(f"| {LABEL[k]} | {f3(med([r['r2'][k] for r in runs]))} |")
    L += ["", f"Nonlinear-in-b gain (mlp − affine): {f3(med([r['r2']['gain_nonlinear_in_b'] for r in runs]))}; beyond-b gain (history − mlp): {f3(med([r['r2']['gain_beyond_b'] for r in runs]))}.",
          f"mix3 slopes: popt {f3(med([r['r2']['mix3_slopes']['popt'] for r in runs]))}, reach {f3(med([r['r2']['mix3_slopes']['reach'] for r in runs]))}.", ""]
    # B
    L += ["## B. The per-cell profiles h_s of the affine fit", "", "| measure | value |", "|---|---|",
          f"| cells whose top action in h_s is a shortest-path move for some goal | {f3(med([r['profiles']['top_action_optimal_for_some_goal'] for r in runs]))} |",
          f"| correlation of h_s with popt(s, ·) | {f3(med([r['profiles']['corr_popt'] for r in runs]))} |",
          f"| correlation with reach(s, ·) | {f3(med([r['profiles']['corr_reach'] for r in runs]))} |",
          f"| correlation with their best affine combination | {f3(med([r['profiles']['corr_mix'] for r in runs]))} |", "", "Figure: `profiles.png` (seed 0).", ""]
    # C
    names = ["H", "affine", "mix", "mix3", "mlp", "affine+ent", "mls", "goal_blind"]
    L += ["## C. Decisions", "", "Offline, on test decisions where the model's move depends on the goal (share " + f3(med([r['offline']['goal_matters_share'] for r in runs])) + "): the share where argmax(Ĥ + G) is the model's move.", "",
          "| Ĥ | agreement |", "|---|---|"] + [f"| {k} | {f3(med([r['offline'][k] for r in runs]))} |" for k in names]
    on = ["natural", "additive", "affine", "mix", "mix3", "mlp", "goal_blind", "history_blind"]
    L += ["", "Online, the policy argmax(Ĥ(b_t) + G(g, t)) on the evaluation spawns:", "", "| policy | return | success | recovery (return − goal-blind) / (natural − goal-blind) |", "|---|---|---|---|"]
    for k in on:
        rows = [r["natural"] if k == "natural" else r["online"][k] for r in runs]
        rec = f3(med([r["recovery"].get(k, 1.0 if k == "natural" else None) for r in runs])) if k != "natural" else "1"
        L.append(f"| {k} | {f3(med([x['ret'] for x in rows]))} | {f3(med([x['success'] for x in rows]))} | {rec} |")
    # decision rule
    g = lambda key, f: [f(r) for r in runs]
    aff = g("", lambda r: r["r2"]["affine"]); mix = g("", lambda r: r["r2"]["mix"])
    nl = g("", lambda r: r["r2"]["gain_nonlinear_in_b"]); by = g("", lambda r: r["r2"]["gain_beyond_b"])
    crit = {
        "QMDP": (np.median(aff) >= 0.75, f"R²(affine) {np.median(aff):.3f}"),
        "MIX": (np.median(mix) >= 0.9 * np.median(aff), f"R²(mix) {np.median(mix):.3f} against 0.9 × {np.median(aff):.3f} = {0.9 * np.median(aff):.3f}"),
        "NONLIN": (np.median(nl) <= 0.05, f"nonlinear-in-b gain {np.median(nl):.3f}"),
        "BEYOND": (np.median(by) > np.median(nl) and wilcoxon_greater(by, nl) < 0.05, f"beyond-b {np.median(by):.3f} against nonlinear-in-b {np.median(nl):.3f}, p {wilcoxon_greater(by, nl):.3f}"),
        "PROF": (np.median(g("", lambda r: r["profiles"]["top_action_optimal_for_some_goal"])) >= 0.85 and np.median(g("", lambda r: r["profiles"]["corr_mix"])) >= 0.7,
                 f"top action optimal for some goal {np.median(g('', lambda r: r['profiles']['top_action_optimal_for_some_goal'])):.2f}, corr with mix {np.median(g('', lambda r: r['profiles']['corr_mix'])):.2f}"),
        "DEC": (np.median(g("", lambda r: r["offline"]["affine"])) >= 0.9 * np.median(g("", lambda r: r["offline"]["H"])) and np.median(g("", lambda r: r["recovery"]["affine"])) >= 0.9 * np.median(g("", lambda r: r["recovery"]["additive"])),
                f"offline affine {np.median(g('', lambda r: r['offline']['affine'])):.3f} against H {np.median(g('', lambda r: r['offline']['H'])):.3f}; recovery affine {np.median(g('', lambda r: r['recovery']['affine'])):.2f} against additive {np.median(g('', lambda r: r['recovery']['additive'])):.2f}"),
        "NONET": (np.median(g("", lambda r: r["recovery"]["mix3"])) >= 0.8 * np.median(g("", lambda r: r["recovery"]["additive"])),
                  f"recovery mix3 {np.median(g('', lambda r: r['recovery']['mix3'])):.2f} against 0.8 × additive {0.8 * np.median(g('', lambda r: r['recovery']['additive'])):.2f}"),
    }
    L += ["", "## Decision rule", "", "| criterion | value | held |", "|---|---|---|"] + [f"| {k} | {v[1]} | {'yes' if v[0] else 'no'} |" for k, v in crit.items()]
    (out / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))
    # figure: per-cell profiles of seed 0 as arrows, against popt
    r0 = runs[0]
    maze = BM.make(**res["task"])
    fig, axes = plt.subplots(1, 3, figsize=(13, 4.6))
    for ax, (title, key) in zip(axes, (("h_s: the affine fit's per-cell profile", "h_cells"), ("popt(s, ·): share of goals for which the move is optimal", "popt"), ("reach(s, ·): mean γ^d to the goals", "reach"))):
        V = np.array(r0["profiles"][key])                                                      # [n, 4] centred: N S W E
        V = V / (np.abs(V).max() + 1e-9)
        R, C = max(r for r, _ in maze.cells) + 1, max(c for _, c in maze.cells) + 1
        grid = np.ones((R, C, 3)) * 0.25
        for (rr, cc) in maze.cells:
            grid[rr, cc] = 1.0
        ax.imshow(grid, interpolation="nearest")
        for i, (rr, cc) in enumerate(maze.cells):
            for a_, (dr, dc) in enumerate(((-1, 0), (1, 0), (0, -1), (0, 1))):
                v = V[i, a_]
                if v > 0.05:
                    ax.arrow(cc, rr, 0.42 * v * dc, 0.42 * v * dr, head_width=0.12 * v + 0.03, color="C0", length_includes_head=True)
        for j, gcell in enumerate(maze.goals):
            rr, cc = maze.cells[gcell]; ax.text(cc, rr, "ABCD"[j], ha="center", va="center", color="C3", fontsize=11, weight="bold")
        for lcell in maze.landmarks:
            rr, cc = maze.cells[lcell]; ax.plot(cc, rr, marker="*", color="C1", ms=9)
        ax.set_title(title, fontsize=9); ax.set_xticks([]); ax.set_yticks([])
    fig.suptitle("Per-cell action profiles (arrows: the positive, centred preference per move; goals in red, landmarks orange)", fontsize=10)
    fig.tight_layout()
    fig.savefig(out / "profiles.png", dpi=130)


if __name__ == "__main__":
    main()
