# Round 18: checks before freezing the task

Generated by `rounds/r18_maze_belief/checks.py` from the exact filter and solver.

```
  ·    ·   0L    ·    ·    ·   1b    ·    ·    ·    ·  
  ·   2a   3a   4a   5a   6a*  7b   8b   9b  10b  11b* 
  ·    ·  12a    ·    ·    ·  13b*   ·    ·    ·    ·  
```

Cells are numbered; letter = symbol (L: landmark); * = goal cell. Start cells: (2, 3, 9, 10). eps = 0.4, gamma = 0.9, H = 12 moves after the goal is revealed.

## 1. Effective dimension of the reachable posterior (goal-free filter, random prefix actions)

| start cells | prefix | distinct posteriors | distinct supports | participation ratio | components for 95 % | variance explained by P(left arm) alone | leading spectrum |
|---|---|---|---|---|---|---|---|
| 2 | 0 | 2 | 1 | 1.00 | 1 | 1.000 | [1.0, 0.0, 0.0, 0.0, 0.0, 0.0] |
| 2 | 2 | 30 | 9 | 4.42 | 7 | 0.075 | [0.3821, 0.2219, 0.1111, 0.0917, 0.076, 0.0437] |
| 2 | 4 | 115 | 26 | 6.50 | 8 | 0.087 | [0.2599, 0.1911, 0.1311, 0.1162, 0.095, 0.0677] |
| 4 | 0 | 2 | 1 | 1.00 | 1 | 1.000 | [1.0, 0.0, 0.0, 0.0, 0.0, 0.0] |
| 4 | 2 | 54 | 14 | 4.98 | 7 | 0.132 | [0.3087, 0.2435, 0.1659, 0.1039, 0.0624, 0.0527] |
| 4 | 4 | 452 | 65 | 6.67 | 9 | 0.117 | [0.2298, 0.2133, 0.151, 0.111, 0.0835, 0.0669] |
| 6 | 0 | 2 | 1 | 1.00 | 1 | 1.000 | [1.0, 0.0, 0.0, 0.0, 0.0, 0.0] |
| 6 | 2 | 60 | 16 | 5.02 | 8 | 0.156 | [0.3154, 0.2518, 0.1386, 0.0945, 0.064, 0.0462] |
| 6 | 4 | 885 | 92 | 6.54 | 10 | 0.137 | [0.2652, 0.1956, 0.1377, 0.1023, 0.0787, 0.0667] |

## 2–4. At the reveal, by goal and prefix length (4 start cells)

Beliefs are weighted by their probability under random prefix actions. Regret: optimal value minus the baseline's exact value.

| goal | prefix | posteriors | V* mean | V* sd over beliefs | V* range | arrival time mean | arrival sd over beliefs | first action shares | one action optimal for every belief | most likely cell | fully observed average | no future observations |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| G1 | 0 | 2 | 0.643 | 0.010 | 0.63–0.65 | 5.50 | 0.20 | W0.50 E0.50 | no | 0.150 | 0.004 | 0.000 |
| G1 | 1 | 13 | 0.669 | 0.048 | 0.60–0.76 | 5.11 | 0.73 | N0.07 S0.06 W0.62 E0.25 | no | 0.147 | 0.004 | 0.000 |
| G1 | 2 | 54 | 0.685 | 0.062 | 0.58–0.87 | 4.85 | 0.86 | N0.16 S0.06 W0.55 E0.23 | no | 0.115 | 0.009 | 0.002 |
| G1 | 3 | 175 | 0.698 | 0.066 | 0.58–0.92 | 4.65 | 0.92 | N0.16 S0.08 W0.49 E0.26 | no | 0.100 | 0.008 | 0.002 |
| G1 | 4 | 452 | 0.710 | 0.070 | 0.57–1.00 | 4.49 | 0.96 | N0.16 S0.10 W0.48 E0.26 | no | 0.080 | 0.010 | 0.001 |
| G2 | 0 | 2 | 0.548 | 0.031 | 0.52–0.58 | 7.23 | 0.43 | N0.50 W0.50 | no | 0.178 | 0.034 | 0.006 |
| G2 | 1 | 13 | 0.565 | 0.057 | 0.47–0.68 | 6.90 | 0.91 | N0.12 S0.06 W0.62 E0.20 | no | 0.148 | 0.023 | 0.003 |
| G2 | 2 | 54 | 0.585 | 0.065 | 0.47–0.80 | 6.51 | 1.01 | N0.19 S0.12 W0.54 E0.15 | no | 0.134 | 0.026 | 0.008 |
| G2 | 3 | 175 | 0.601 | 0.072 | 0.47–0.87 | 6.24 | 1.09 | N0.17 S0.15 W0.49 E0.19 | no | 0.110 | 0.023 | 0.006 |
| G2 | 4 | 452 | 0.615 | 0.078 | 0.47–0.95 | 6.00 | 1.16 | N0.14 S0.17 W0.48 E0.21 | no | 0.094 | 0.020 | 0.004 |
| G3 | 0 | 2 | 0.702 | 0.050 | 0.65–0.75 | 5.00 | 0.70 | E1.00 | yes | 0.000 | 0.000 | 0.000 |
| G3 | 1 | 13 | 0.686 | 0.109 | 0.43–0.86 | 5.31 | 1.61 | S0.06 E0.94 | no | 0.025 | 0.002 | 0.000 |
| G3 | 2 | 54 | 0.686 | 0.124 | 0.43–0.94 | 5.26 | 1.78 | N0.03 S0.06 E0.91 | no | 0.026 | 0.009 | 0.000 |
| G3 | 3 | 175 | 0.683 | 0.142 | 0.42–1.00 | 5.30 | 2.03 | N0.08 S0.09 E0.83 | no | 0.021 | 0.007 | 0.000 |
| G3 | 4 | 452 | 0.680 | 0.154 | 0.41–1.00 | 5.31 | 2.20 | N0.11 S0.10 E0.80 | no | 0.020 | 0.008 | 0.000 |
