"""The additive ceiling (no network, no training of agents): if the agent knew its cell, how often could the best
additive rule argmax_a H(cell, a) + G(goal, a) pick a shortest-path move? H (four numbers per cell) and G (four per
goal) are fitted directly to the shortest-path moves by gradient descent, several restarts; the best is reported.
Goal-blind: the best rule argmax_a H(cell, a) alone.

    .venv/bin/python studies/7_information_seeking/additive_ceiling/run.py            # writes results.json, tables.md
"""
import json
from pathlib import Path

import numpy as np
import torch

from goalgeo import bigmaze as BM, mazebelief as MB

HERE = Path(__file__).resolve().parent


def ceiling(maze, goals, restarts=8, steps=3000, additive=True, seed=0):
    n = maze.n
    D = np.stack([BM.distances(maze.nxt, g) for g in goals])                                   # [K, n]
    dn = D[:, maze.nxt]                                                                        # [K, n, 4] distance after the move
    opt = torch.tensor(dn <= dn.min(-1, keepdims=True) + 1e-9)                                 # shortest-path moves
    keep = torch.tensor([[s != g for s in range(n)] for g in goals])                           # no decision on the goal itself
    best = 0.0
    for r in range(restarts):
        torch.manual_seed(seed + r)
        H = torch.zeros(n, 4, requires_grad=True)
        G = (0.1 * torch.randn(len(goals), 4)).requires_grad_(additive)
        opt_ = torch.optim.Adam([H, G] if additive else [H], lr=0.05)
        for i in range(steps):
            l = H[None].expand(len(goals), -1, -1) + (G[:, None] if additive else 0)
            lp = torch.log_softmax(l * (1 + i / 300), -1)                                      # sharpen as it goes: the target is the argmax
            loss = -(torch.logsumexp(lp.masked_fill(~opt, -1e9), -1))[keep].mean()
            opt_.zero_grad(); loss.backward(); opt_.step()
        with torch.no_grad():
            a = (H[None].expand(len(goals), -1, -1) + (G[:, None] if additive else 0)).argmax(-1)
            acc = opt.gather(2, a[..., None]).squeeze(-1)[keep].float().mean().item()
        best = max(best, acc)
    return best


def main():
    big = BM.make(pairs=1, eps=0.4)
    junc = BM.make(pairs=1, eps=0.4, junctions=6)
    small = MB.cross_maze()
    cases = {"small maze, its 3 goals": (small, list(small.goals)),
             "small maze, every cell a goal (14)": (small, list(range(small.n))),
             "larger maze, the 4 spread goals (maze10)": (big, list(big.goals)),
             "larger maze, the 6 junction goals": (junc, list(junc.goals)),
             "larger maze, 16 goals (every third cell)": (big, list(range(0, big.n, 3))[:16]),
             "larger maze, every cell a goal (55)": (big, list(range(big.n)))}
    res = {}
    L = ["# The additive ceiling", "", "Generated by `run.py`. The agent knows its cell. Share of (cell, goal) decisions where the best rule of each form picks a shortest-path move.", "",
         "| maze and goals | best additive rule: argmax H(cell) + G(goal) | best goal-blind rule: argmax H(cell) |", "|---|---|---|"]
    for name, (m, goals) in cases.items():
        res[name] = dict(additive=ceiling(m, goals), goal_blind=ceiling(m, goals, restarts=1, additive=False))
        L.append(f"| {name} | {res[name]['additive']:.3f} | {res[name]['goal_blind']:.3f} |")
        print(L[-1], flush=True)
    (HERE / "results.json").write_text(json.dumps(res, indent=1))
    (HERE / "tables.md").write_text("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
