"""The history-mediator experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/5_goal_belief_mechanism/history_mediator/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
CANDS = (("none", "none (L only)"), ("top", "H's top action"), ("rank2", "H's top two"), ("H2", "H, 2 principal components"), ("H", "H"),
         ("mix", "H-mixture code"), ("b", "posterior"), ("all", "all history (reference)"))
ORDER = ("top", "rank2", "H2", "H", "mix", "b")


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(runs[s], p)) is None else x for s in seeds], dtype=float)
    arm = lambda k, a, m: v("cands", k, "arms", a, m)
    r0 = runs[seeds[0]]
    L = ["# The history-mediator experiment tables", "",
         "Generated by `studies/5_goal_belief_mechanism/history_mediator/tables.py`. The observation-prediction experiment's ten reward models; edits at the goal "
         f"token's four attention outputs. Cells: {r0['cells']} (dropped {r0['cells_dropped']}: a table candidate's (Z, L) value had fewer than 5 fit-side histories); "
         f"informative pairs {mr(v('informative_pairs'), 0)}. Median (range).", "",
         f"Natural: optimal {mr(v('natural', 'optimal'))}, history dependence {mr(v('natural', 'history_dependence'))}; history-blind ceiling {mr(v('ceiling'))}.", "",
         "## Swaps (informative pairs: recipient's and donor's natural actions differ)", ""]
    L += head("Z", "R² of x_Z for d", "swap_Z: follow", "ratio to all", "swap_Z rotated: follow", "swap_r: change", "swap_r: follow", "swap_r matched Z: change")
    fall = arm("all", "swap_Z", "follow")
    call = arm("all", "swap_Z", "change")
    for k, kl in CANDS:
        fz = arm(k, "swap_Z", "follow") if k != "none" else np.zeros(len(seeds))
        L.append(row(kl, mr(v("cands", k, "r2")), mr(fz) if k != "none" else "—", mr(fz / fall, 2) if k != "none" else "—",
                     mr(arm(k, "swap_Z_rot", "follow")) if k != "none" else "—",
                     mr(arm(k, "swap_r", "change")) if k != "all" else "—", mr(arm(k, "swap_r", "follow")) if k != "all" else "—",
                     mr(arm(k, "swap_r_matched", "matched_change")) if k in ("top", "rank2", "mix", "b") else "—"))
    L += ["", "## Removals (all cells)", ""]
    L += head("Z", "remove_Z: optimal", "remove_Z: history dependence", "remove_r: optimal", "remove_r: drop", "remove_r: history dependence")
    nat = v("natural", "optimal")
    for k, kl in CANDS:
        L.append(row(kl, mr(arm(k, "remove_Z", "optimal")) if k != "none" else "—", mr(arm(k, "remove_Z", "history_dependence")) if k != "none" else "—",
                     mr(arm(k, "remove_r", "optimal")) if k != "all" else "—", mr(nat - arm(k, "remove_r", "optimal")) if k != "all" else "—",
                     mr(arm(k, "remove_r", "history_dependence")) if k != "all" else "—"))
    L += ["", "## Decision rule (registered)", ""]
    L += head("Z", "S90: swap ratio ≥ 0.9", "R0: swap_r change ≤ 0.05 and ≤ 0.1 × swap_all's", "mediates", "secondary: remove_Z at ceiling, dependence ≤ 0.25 ×", "remove_r drop ≤ 0.02", "matched change ≤ 0.05")
    minimal = None
    yes = lambda b: "**yes**" if b else "no"
    for k in ORDER:
        ratio = arm(k, "swap_Z", "follow") / fall
        ch = arm(k, "swap_r", "change")
        s90 = np.median(ratio) >= 0.9
        rz = np.median(ch) <= 0.05 and np.median(ch / call) <= 0.1
        if s90 and rz and minimal is None:
            minimal = k
        sec1 = np.median(np.abs(arm(k, "remove_Z", "optimal") - v("ceiling"))) <= 0.05 and np.median(arm(k, "remove_Z", "history_dependence") / v("natural", "history_dependence")) <= 0.25
        sec2 = np.median(nat - arm(k, "remove_r", "optimal")) <= 0.02
        mc = f"{yes(np.median(arm(k, 'swap_r_matched', 'matched_change')) <= 0.05)}" if k in ("top", "rank2", "mix", "b") else "—"
        L.append(row(dict(CANDS)[k], f"{f(np.median(ratio), 2)}; {yes(s90)}", f"{f(np.median(ch))} ({f(np.median(ch / call), 2)} ×); {yes(rz)}", yes(s90 and rz),
                     yes(sec1), yes(sec2), mc))
    L += ["", f"**Minimal mediating Z: {dict(CANDS)[minimal] if minimal else 'none of the candidates'}.**", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
