"""Round 26: tables and the figure from results.json.

    .venv/bin/python rounds/r26_predictive_transfer/tables.py            # writes tables.md, fig1_curves.png
"""

from __future__ import annotations

import json, sys
from pathlib import Path

import numpy as np
from scipy.stats import mannwhitneyu

OUT = Path(__file__).resolve().parent
CONDS = (("predict1", "predict1"), ("reward", "reward"), ("random", "random"), ("predict2", "predict2 (secondary)"))
REFS = (("goal_only", "goal only"), ("posterior", "exact posterior"), ("predict2_exact", "exact two-step prediction"),
        ("predict1_exact", "exact one-step prediction"), ("raw_history", "raw prefix tokens"))
FAILED_REWARD = ("seed3", "seed6")                                   # failed G2 in round 23 (regret > 0.05)
f = lambda x, d=4: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
mr = lambda xs, d=4: f"{f(np.median(xs), d)} ({f(np.min(xs), d)}–{f(np.max(xs), d)})"
p1 = lambda a, b: float(mannwhitneyu(a, b, alternative="less", method="exact").pvalue)
p2 = lambda a, b: float(mannwhitneyu(a, b, alternative="two-sided", method="exact").pvalue)
fp = lambda p: "< 0.001" if p < 0.001 else f"{p:.3f}"


class R:
    def __init__(self, res):
        self.res, self.ns = res, [str(n) for n in res["ns"]]
        self.B, self.H, self.Ref = res["backbones"], res["heads"], res["references"]
        self.n1k = min(self.ns, key=lambda n: abs(np.log(int(n) / 1000)))          # 1 000 in the full grid

    def conds(self):
        return [(c, lab) for c, lab in CONDS if c in self.B]

    def seeds(self, c, drop=()):
        return [s for s in self.B[c] if s not in drop]

    def curve(self, h, c, s, site, key="regret"):
        return np.array([np.mean(self.H[h][c][s][str(site)][n][key]) for n in self.ns])

    def auc(self, h, c, s, site, key="regret"):
        return float(self.curve(h, c, s, site, key).mean())

    def site(self, h, c):
        """The site with the lowest median AUC on the selection half."""
        sites = sorted(self.H[h][c]["seed0"], key=int)
        return int(min(sites, key=lambda l: np.median([self.auc(h, c, s, l, "regret_select") for s in self.seeds(c)])))

    def ref_curve(self, h, name, key="regret"):
        return np.array([np.mean(self.Ref[h][name][n][key]) for n in self.ns])

    def n_at(self, curve, h, q):
        """Examples at which the curve first reaches R_post + (1 - q)(R_goal - R_post), interpolated in log N."""
        rg, rp = self.ref_curve(h, "goal_only")[-1], self.ref_curve(h, "posterior")[-1]
        thr = rp + (1 - q) * (rg - rp)
        ns = np.log10([float(n) for n in self.ns])
        for i, r in enumerate(curve):
            if r <= thr:
                if i == 0:
                    return 10 ** ns[0]
                a = (curve[i - 1] - thr) / (curve[i - 1] - r)
                return 10 ** (ns[i - 1] + a * (ns[i] - ns[i - 1]))
        return np.inf


def fmt_n(x):
    return "> 100 000" if not np.isfinite(x) else f"{x:,.0f}".replace(",", " ")


def main():
    res = R(json.load(open(OUT / "results.json")))
    h = "h16"
    L = ["# Round 26 tables", "",
         f"Generated by `rounds/r26_predictive_transfer/tables.py`. Ten backbones per condition; median (range) over backbones. Held-out histories of round 22's bank, "
         f"decision at the reveal under every goal ({res.res['n_test'] * 3} decisions, of which the report half is {(res.res['n_test'] - res.res['n_select']) * 3}). "
         "Regret: greedy, in discounted return. Heads: three head seeds per backbone, averaged. Sites: residual stream at the last prefix token entering block 0–3, and after block 3 (site 4).", ""]
    # ---------------------------------------------------------------- stage 1
    L += ["## Stage 1: representations at the last prefix token", "", "### Posterior decodability (affine R², held-out) by site", ""]
    sites = sorted(res.B["random"]["seed0"]["sites"], key=int)
    for key, title in (("r2_posterior", None), ("r2_predict1", "### One-step prediction decodability (affine R²) by site"),
                       ("r2_predict2", "### Two-step prediction decodability (affine R²) by site"),
                       ("consistency_ratio", "### Identical-posterior consistency: squared state distance, type A / type C (0 = identical states)"),
                       ("decoded_consistency_ratio", "### Same, for the decoded posterior (L1), type A / type C")):
        if title:
            L += ["", title, ""]
        L += head("condition", *[f"site {l}" for l in sites])
        for c, lab in res.conds():
            L.append(row(lab, *[mr([res.B[c][s]["sites"][l][key] for s in res.seeds(c)], 3) for l in sites]))
    L += ["", "Ceilings from the exact predictions (`checks.md`): posterior R² 0.448 from the one-step prediction, 0.880 from the two-step prediction.", ""]
    L += ["### The predictors' own heads at the last prefix token", ""] + head("condition", "error (TV, own targets)", "one-step error (TV, four moves)", "D_same (type A, one-step)", "D_diff (type C)")
    for c, lab in res.conds():
        if c.startswith("predict"):
            g = lambda k: [res.B[c][s]["head"][k] for s in res.seeds(c)]
            L.append(row(lab, mr(g("error")), mr(g("error_1step")), mr(g("d_same")), mr(g("d_diff"), 3)))
    own = [res.B["reward"][s]["own_policy"]["regret_report"] for s in res.seeds("reward")]
    L += ["", f"Reward backbones, their own policy at the reveal (goal token, natural access), same decisions: greedy regret {mr(own)}; "
          f"without seeds 3 and 6 {mr([res.B['reward'][s]['own_policy']['regret_report'] for s in res.seeds('reward', FAILED_REWARD)])}.", ""]
    # ---------------------------------------------------------------- stage 2
    for h, hl in (("h16", "16 hidden units (primary)"), ("h0", "linear (secondary)")):
        if h not in res.H:
            continue
        sel = {c: res.site(h, c) for c, _ in res.conds()}
        L += [f"## Stage 2: frozen backbone, head with {hl}", "", "### AUC (mean regret over the eight N) by site, report half", ""]
        L += head("condition", *[f"site {l}" for l in sites], "selected (selection half)")
        for c, lab in res.conds():
            L.append(row(lab, *[mr([res.auc(h, c, s, l) for s in res.seeds(c)]) for l in sites], sel[c]))
        L += ["", "### Learning curves at each condition's selected site: greedy regret by number of examples", ""]
        L += head("", *[f"N = {n}" for n in res.ns], "AUC")
        for c, lab in res.conds():
            cur = np.array([res.curve(h, c, s, sel[c]) for s in res.seeds(c)])
            L.append(row(f"{lab} (site {sel[c]})", *[f(np.median(cur[:, i])) for i in range(len(res.ns))], f(np.median(cur.mean(1)))))
        for name, lab in REFS:
            cur = res.ref_curve(h, name)
            L.append(row(f"*reference: {lab}*", *[f(x) for x in cur], f(cur.mean())))
        L += ["", "### Primary measures and the decision rule", ""]
        L += head("condition", "site", "AUC", "N50", "N90", "regret at N = 1 000", "regret at N = 100 000")
        A, N50 = {}, {}
        for c, lab in res.conds():
            cur = [res.curve(h, c, s, sel[c]) for s in res.seeds(c)]
            A[c] = [x.mean() for x in cur]
            N50[c] = [res.n_at(x, h, 0.5) for x in cur]
            n90 = [res.n_at(x, h, 0.9) for x in cur]
            i1k, i100k = res.ns.index(res.n1k), len(res.ns) - 1
            L.append(row(lab, sel[c], mr(A[c]), fmt_n(np.median(N50[c])), fmt_n(np.median(n90)), mr([x[i1k] for x in cur]), mr([x[i100k] for x in cur])))
        for name, lab in REFS:
            cur = res.ref_curve(h, name)
            L.append(row(f"*{lab}*", "", f(cur.mean()), fmt_n(res.n_at(cur, h, 0.5)), fmt_n(res.n_at(cur, h, 0.9)), f(cur[res.ns.index(res.n1k)]), f(cur[-1])))
        L += ["", "N50 / N90: examples needed to close half / 90 % of the gap between the goal-only and exact-posterior references at N = 100 000 "
              f"(thresholds {f(res.ref_curve(h, 'posterior')[-1] + 0.5 * (res.ref_curve(h, 'goal_only')[-1] - res.ref_curve(h, 'posterior')[-1]))} and "
              f"{f(res.ref_curve(h, 'posterior')[-1] + 0.1 * (res.ref_curve(h, 'goal_only')[-1] - res.ref_curve(h, 'posterior')[-1]))}). Median over backbones.", ""]
        tests = [("C1", "predict1 below random", "predict1", "random", p1), ("C2", "predict1 against reward", "predict1", "reward", p2),
                 ("C3", "reward below random", "reward", "random", p1), ("C4", "predict2 against predict1", "predict2", "predict1", p2)]
        L += head("", "comparison (AUC)", "p", "medians", "same on N50: p")
        for k, lab, a, b, fn in tests:
            if a in A and b in A:
                L.append(row(k, lab, fp(fn(A[a], A[b])), f"{f(np.median(A[a]))} / {f(np.median(A[b]))}", fp(fn(N50[a], N50[b]))))
        if "reward" in A:
            keep = [i for i, s in enumerate(res.seeds("reward")) if s not in FAILED_REWARD]
            ar = [A["reward"][i] for i in keep]
            L += ["", f"Without reward seeds 3 and 6 (failed G2 in round 23): reward AUC {mr(ar)}; C2 p {fp(p2(A['predict1'], ar))}, C3 p {fp(p1(ar, A['random']))}.", ""]
        # ------------------------------------------------------------ the precaution
        L += ["### One-step-determined and undetermined decisions (selected site)", ""]
        L += head("", "N = 1 000: determined", "undetermined", "N = 100 000: determined", "undetermined")
        i1k, i100k = res.ns.index(res.n1k), res.ns[-1]
        for c, lab in res.conds():
            g = lambda n, k: [np.mean(res.H[h][c][s][str(sel[c])][n][k]) for s in res.seeds(c)]
            L.append(row(lab, f(np.median(g(res.n1k, "determined"))), f(np.median(g(res.n1k, "undetermined"))), f(np.median(g(i100k, "determined"))), f(np.median(g(i100k, "undetermined")))))
        for name, lab in REFS:
            g = lambda n, k: np.mean(res.Ref[h][name][n][k])
            L.append(row(f"*{lab}*", f(g(res.n1k, "determined")), f(g(res.n1k, "undetermined")), f(g(i100k, "determined")), f(g(i100k, "undetermined"))))
        L += ["", "Regret averaged over the decisions of each kind (determined: the one-step class fixes the optimal set under that goal).", ""]
        L += ["### By goal and by prefix length, N = 1 000 and N = 100 000 (selected site)", ""]
        L += head("", "G1 1k", "G2 1k", "G3 1k", "G1 100k", "G2 100k", "G3 100k", *[f"length {l}, 100k" for l in range(5)])
        for c, lab in res.conds():
            cells = []
            for n in (res.n1k, i100k):
                for gi in range(3):
                    cells.append(f(np.median([np.mean(res.H[h][c][s][str(sel[c])][n]["by_goal"][gi]) for s in res.seeds(c)])))
            for l in range(5):
                cells.append(f(np.median([np.mean(res.H[h][c][s][str(sel[c])][i100k]["by_length"][str(l)]) for s in res.seeds(c)])))
            L.append(row(lab, *cells))
        L += ["", "### The head's identical-posterior inconsistency (TV between action distributions), type A / type C, N = 100 000", ""]
        L += head("condition", "type A", "type C", "ratio")
        for c, lab in res.conds():
            a = [np.mean(res.H[h][c][s][str(sel[c])][i100k]["tv_A"]) for s in res.seeds(c)]
            b = [np.mean(res.H[h][c][s][str(sel[c])][i100k]["tv_C"]) for s in res.seeds(c)]
            L.append(row(lab, mr(a, 3), mr(b, 3), mr(np.array(a) / np.array(b), 3)))
        for name, lab in REFS:
            a, b = np.mean(res.Ref[h][name][i100k]["tv_A"]), np.mean(res.Ref[h][name][i100k]["tv_C"])
            L.append(row(f"*{lab}*", f(a, 3), f(b, 3), f(a / b if b else float("nan"), 3)))
        L.append("")
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))
    figure(res)


def figure(res):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from goalgeo.style import COL, INK, MUTED, _style
    colors = dict(predict1=COL["next_obs"], predict2="#a06a00", reward=COL["act_hard"], random=COL["init"])
    ns = [int(n) for n in res.ns]
    fig, axes = plt.subplots(1, 2, figsize=(10, 3.8))
    for ax, h, title in zip(axes, ("h16", "h0"), ("16 hidden units (primary)", "linear head")):
        if h not in res.H:
            continue
        for c, lab in res.conds():
            site = res.site(h, c)
            cur = np.array([res.curve(h, c, s, site) for s in res.seeds(c)])
            ax.fill_between(ns, cur.min(0), cur.max(0), color=colors[c], alpha=0.15, lw=0)
            ax.plot(ns, np.median(cur, 0), color=colors[c], lw=2, marker="o", ms=3, label=f"{lab}, site {site}")
        for name, lab, ls in (("goal_only", "goal only", ":"), ("posterior", "exact posterior", "--"), ("predict1_exact", "exact one-step prediction", "-."),
                              ("raw_history", "raw tokens", (0, (8, 3)))):
            ax.plot(ns, res.ref_curve(h, name), color=MUTED, lw=1.2, ls=ls, label=lab)
        ax.set_xscale("log"); ax.set_yscale("log"); ax.set_ylim(1e-4, 4e-2)
        ax.set_xlabel("action-labelled examples", color=INK, fontsize=9); ax.set_ylabel("greedy regret at the reveal (held-out)", color=INK, fontsize=9)
        ax.set_title(title, color=INK, fontsize=10, loc="left")
        _style(ax)
    axes[0].legend(fontsize=7, frameon=False)
    fig.tight_layout()
    fig.savefig(OUT / "fig1_curves.png", dpi=150)


if __name__ == "__main__":
    main()
