"""Round 37: tables and the registered decision rule from results.json.

    .venv/bin/python rounds/r37_self_value/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "r32_direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
R36 = json.load(open(OUT.parent / "r36_query_swap" / "results.json"))["runs"]


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    c = R["cells"]
    L = ["# Round 37 tables", "", "Generated by `rounds/r37_self_value/tables.py`. Round 23's ten reward models; block 0's attention at the goal token, "
         f"recomputed with parts of the goal token's own key and value from another goal g′. Cells: goal-matters {c['goal_matters']}, goal-neutral {c['goal_neutral']}. "
         "Median (range) over the ten models.", "", f"Check: recomputed attention against the natural decision, largest |Δp| {v('behaviour', 'check_recomputed_equals_natural').max():.1e}.", ""]
    kinds = (("natural", "natural (g)"), ("selfkv", "own key and value from g′ (round 36)"), ("selfv", "**own value from g′**"), ("selfk", "**own key from g′**"),
             ("embedding_residual", "**embedding in the residual stream from g′** (attention natural)"), ("other_goal", "natural under g′"))
    for cls, title in (("goal_matters", "Goal-matters cells"), ("goal_neutral", "Goal-neutral cells")):
        L += [f"## {title}", ""]
        L += head("swap", "g′'s action", "optimal under g", "unchanged")
        for k, kl in kinds:
            g = lambda m: v("behaviour", cls, k, m)
            L.append(row(kl, mr(g("as_other_goal")), mr(g("optimal")), mr(g("unchanged"))))
        L.append("")
    # per head, per model
    H = 4
    gm = lambda k: v("behaviour", "goal_matters", k, "as_other_goal")
    nat, allkv = gm("natural"), gm("selfkv")
    eff = lambda k: (gm(k) - nat) / np.maximum(allkv - nat, 1e-9)
    L += ["## Per head, goal-matters cells: (g′'s action − natural) / (all heads' own key and value − natural), per model", ""]
    L += head("model", *[f"H{k} key+value" for k in range(H)], *[f"H{k} value" for k in range(H)], "self weight H0–H3", "self-term norm H0–H3")
    kv = np.stack([eff(f"selfkv_head{k}") for k in range(H)], 1)
    vv = np.stack([eff(f"selfv_head{k}") for k in range(H)], 1)
    for i, s in enumerate(seeds):
        b = runs[s]["behaviour"]
        L.append(row(s, *[f(x, 2) for x in kv[i]], *[f(x, 2) for x in vv[i]], " ".join(f"{x:.2f}" for x in b["self_weight"]), " ".join(f"{x:.2f}" for x in b["self_term_norm"])))
    best = kv.max(1)
    bh = kv.argmax(1)
    norms = np.array([runs[s]["behaviour"]["self_term_norm"] for s in seeds])
    weights = np.array([runs[s]["behaviour"]["self_weight"] for s in seeds])
    L += ["", f"Best single head (key+value): {mr(best, 2)} of all heads' effect; head " + ", ".join(f"{s}: H{bh[i]}" for i, s in enumerate(seeds)) +
          f". The best head has the largest self-term norm in {int((norms.argmax(1) == bh).sum())} of 10 models and the largest self weight in {int((weights.argmax(1) == bh).sum())}. "
          f"Sum over heads of the single-head effects: {mr(kv.sum(1), 2)}.", ""]
    # decision rule
    sv, sk = gm("selfv"), gm("selfk")
    pV, pK = p_gt(sv, sk), p_gt(sk, sv)
    V = np.median(sv) >= 0.75 and pV < 0.05
    K = np.median(sk) >= 0.75 and pK < 0.05
    Hc = np.median(best) >= 0.75
    dC = np.median(gm("embedding_residual") - nat)
    C = dC <= 0.10
    yes = lambda b: "**yes**" if b else "no"
    L += ["## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**V** value carries the identity", "selfv: g′'s action ≥ 0.75, above selfk", f"{f(np.median(sv))} against {f(np.median(sk))}; p {fp(pV)}", yes(V)))
    L.append(row("**K** key carries it", "selfk ≥ 0.75, above selfv", f"{f(np.median(sk))}; p {fp(pK)}", yes(K)))
    L.append(row("**H** one head", "best single head's key+value swap ≥ 0.75 × all heads' (median)", f"{f(np.median(best), 2)}", yes(Hc)))
    L.append(row("**C** complement", "embedding_residual − natural ≤ 0.10", f(dC), yes(C)))
    r36 = np.array([R36[s]["behaviour"]["goal_matters"]["selfkv"]["as_other_goal"] for s in seeds])
    L += ["", f"Reproduction: selfkv here {mr(allkv)}, round 36 {mr(r36)}; largest difference {np.abs(allkv - r36).max():.1e}. "
          f"Best head's value-only swap against its key+value swap: {mr(vv[np.arange(len(seeds)), bh] - kv[np.arange(len(seeds)), bh], 2)} (fraction of all heads' effect).", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
