"""Round 35: tables and the registered decision rule from results.json (and identity_check.json).

    .venv/bin/python rounds/r35_block0_steps/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "r32_direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
STEPS = (("attn", "attention output a"), ("self", "  self term"), ("prefix", "  prefix term"), ("head0", "  head 0"), ("head1", "  head 1"), ("head2", "  head 2"),
         ("head3", "  head 3"), ("mid", "m = emb + a (rounds 33–34)"), ("ln", "u = ln2(m): MLP input"), ("ln_sigma_fixed", "  u with σ fixed across goals"))


def main():
    runs = json.load(open(OUT / "results.json"))["runs"]
    ident = json.load(open(OUT / "identity_check.json"))
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    L = ["# Round 35 tables", "", "Generated by `rounds/r35_block0_steps/tables.py`. Round 23's ten reward models; the goal token in block 0. "
         "Median (range) over the ten models.", ""]
    L += ["## Checks", ""]
    L += head("identity", "largest over models")
    L.append(row("m − emb − a", f"{v('checks', 'mid_minus_embedding_minus_attn').max():.1e}"))
    L.append(row("self + prefix terms − a", f"{v('checks', 'terms_sum_to_attn').max():.1e}"))
    L.append(row("edits at attn against mid, each step's own fit (registered)", f"{v('checks', 'attn_vs_mid_edits').max():.1e}"))
    L.append(row("edits at attn against mid, identical edit vectors (`identity_check.py`)", f"{max(ident.values()):.1e}"))
    L += ["", "## Goal × history interaction, per step (held-out)", ""]
    L += head("step", "interaction share", "interaction size (squared norm)", "variance within (goal, length)")
    for k, kl in STEPS:
        L.append(row(kl, mr(v("interaction", k, "share")), mr(v("interaction", k, "size"), 4), mr(v("interaction", k, "variance"), 4)))
    L += ["", f"Layer norm scale σ: coefficient of variation across the three goals for a fixed history {mr(v('sigma', 'cv_across_goals'))}; mean σ {mr(v('sigma', 'mean'))}.", ""]
    L += ["## Encodings of the posterior, per step: held-out R² within (goal, length)", ""]
    L += head("step", "linear shared", "linear goal-specific", "table shared", "table goal-conditioned", "goal × posterior gain (table_goal − table)")
    for k, kl in STEPS[:-1]:
        g = lambda m: v("fit", k, m)
        L.append(row(kl, mr(g("linear")), mr(g("linear_goal")), mr(g("table")), mr(g("table_goal")), mr(g("table_goal") - g("table"))))
    L += ["", "## Edits at each step: goal-dependent pairs (rate / whole) and main pairs", ""]
    L += head("step", "table shared", "table, recipient's goal", "table, another goal", "right − wrong", "whole rate", "main S: shared / goal / wrong", "harm: shared / goal")
    for site in ("attn", "mid", "ln"):
        gd = lambda k: v("edits", site, "goal_dependent", k, "right_every_change_goal")
        r = lambda k: gd(k) / gd("whole")
        S = lambda k: v("edits", site, "change", k, "share_of_whole")
        h = lambda k: v("edits", site, "preserve", k, "harm")
        L.append(row(site, mr(r("table"), 2), mr(r("table_goal"), 2), mr(r("table_wrong"), 2), mr(r("table_goal") - r("table_wrong"), 2), mr(gd("whole")),
                     f"{f(np.median(S('table')), 2)} / {f(np.median(S('table_goal')), 2)} / {f(np.median(S('table_wrong')), 2)}",
                     f"{f(np.median(h('table')))} / {f(np.median(h('table_goal')))}"))
    # decision rule
    ia = v("interaction", "attn", "share")
    gain_a = v("fit", "attn", "table_goal") - v("fit", "attn", "table")
    gd = lambda site, k: v("edits", site, "goal_dependent", k, "right_every_change_goal")
    rr = lambda site, k: gd(site, k) / gd(site, "whole")
    pA = p_gt(gd("attn", "table_goal"), gd("attn", "table_wrong"))
    A = bool(np.all(ia >= 0.02)) and np.median(gain_a) >= 0.01 and pA < 0.05
    n1, n2r, n2 = v("checks", "mid_minus_embedding_minus_attn").max(), v("checks", "attn_vs_mid_edits").max(), max(ident.values())
    d_int = v("interaction", "ln", "share") - v("interaction", "mid", "share")
    d_tab = rr("ln", "table") - rr("mid", "table")
    gap = lambda s: rr(s, "table_goal") - rr(s, "table_wrong")
    d_gap = gap("ln") - gap("mid")
    p_tab, p_gap = p_gt(rr("mid", "table"), rr("ln", "table")), p_gt(gap("ln"), gap("mid"))
    LN1, LN2, LN3 = np.median(d_int) >= 0.02, np.median(d_tab) <= -0.05 and p_tab < 0.05, np.median(d_gap) >= 0.05 and p_gap < 0.05
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**A** attention output already goal-conditioned", "interaction ≥ 0.02 every model; goal × posterior gain ≥ 0.01; table_goal above table_wrong",
                 f"min {f(ia.min())}; {f(np.median(gain_a))}; p {fp(pA)}", yes(A)))
    L.append(row("**N** nothing but the embedding between", "m − emb − a ≤ 10⁻⁵; attn and mid edits identical within 10⁻⁴",
                 f"{n1:.1e}; registered form {n2r:.1e}, identical vectors {n2:.1e}", f"registered form: {yes(n1 <= 1e-5 and n2r <= 1e-4)}; identical vectors: {yes(n1 <= 1e-5 and n2 <= 1e-4)}"))
    L.append(row("**LN** (any of three)", "interaction ln ≥ mid + 0.02", f"{f(np.median(d_int))}", yes(LN1)))
    L.append(row("", "goal-dependent table ratio ln ≤ mid − 0.05 (p < 0.05)", f"{f(np.median(d_tab), 2)}; p {fp(p_tab)}", yes(LN2)))
    L.append(row("", "right − wrong gap ln ≥ mid + 0.05 (p < 0.05)", f"{f(np.median(d_gap), 2)}; p {fp(p_gap)}", yes(LN3)))
    L.append(row("", "LN", "", yes(LN1 or LN2 or LN3)))
    # descriptive: where in attention
    si, pi = v("interaction", "self", "size"), v("interaction", "prefix", "size")
    hs = np.stack([v("interaction", f"head{k}", "size") for k in range(4)], 1)
    top = hs.max(1) / hs.sum(1)
    L += ["", "## Where in attention (descriptive)", "",
          f"Interaction size: self term {mr(si, 4)}, prefix term {mr(pi, 4)}, attention output {mr(v('interaction', 'attn', 'size'), 4)}; prefix > self in {int((pi > si).sum())} of 10 models. "
          f"Largest head's share of the summed per-head size {mr(top, 2)}; which head: " + ", ".join(f"{s}: H{int(np.argmax(hs[i]))}" for i, s in enumerate(seeds)) + ".", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
