"""Round 29: tables from results.json.

    .venv/bin/python rounds/r29_goal_route_selection/tables.py            # writes tables.md
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from scipy.stats import wilcoxon

OUT = Path(__file__).resolve().parent
f = lambda x, d=3: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
mr = lambda xs, d=3: f"{f(np.nanmedian(xs), d)} ({f(np.nanmin(xs), d)}–{f(np.nanmax(xs), d)})"
fp = lambda p: "< 0.001" if p < 0.001 else f"{p:.3f}"
p2 = lambda x: float(wilcoxon(x, alternative="two-sided", method="exact").pvalue)
pl = lambda x: float(wilcoxon(x, alternative="less", method="exact").pvalue)


def main():
    R = json.load(open(OUT / "results.json"))["runs"]
    seeds = sorted(R, key=lambda s: int(s[4:]))
    v = lambda *path: np.array([np.nan if _get(R[s], path) is None else _get(R[s], path) for s in seeds], dtype=float)
    L = ["# Round 29 tables", "", "Generated by `rounds/r29_goal_route_selection/tables.py`. Round 23's ten reward models; round 27's pairs under all three goals. "
         "Reliance a: projection of a route intervention's logit change onto the hybrid's (1 = the whole behavioural difference). Eligible cells: TV(none, hybrid) ≥ 0.1. "
         "Median (range) over the ten models; p: exact Wilcoxon signed-rank over the ten.", ""]
    for ps, pl_ in (("main", "main pairs"), ("onestep", "one-step agreeing pairs")):
        L += [f"## {pl_}", "", f"Eligible cells {mr(v(ps, 'n_cells'), 0)}; in pairs with ≥ 2 eligible goals {mr(v(ps, 'n_within'), 0)}; largest |a_both − 1| {mr(v(ps, 'both_check'), 4)}.", ""]
        L += ["### Per goal (all eligible cells)", ""]
        L += head("goal", "cells", "a_interface", "a_encoding", "a_direct", "1 − a_interface − a_direct", "TV(none, hybrid)", "oracle gap", "direct-adequate share",
                  "a_interface: direct-adequate", "direct-inadequate")
        for g in ("G1", "G2", "G3"):
            q = lambda k: v(ps, "per_goal", g, k)
            L.append(row(g, mr(q("n"), 0), mr(q("a_interface")), mr(q("a_encoding")), mr(q("a_direct")), mr(1 - q("a_interface") - q("a_direct")), mr(q("tv")), mr(q("gap"), 4),
                         mr(q("direct_adequate")), mr(q("direct_adequate_a_interface")), mr(q("direct_inadequate_a_interface"))))
        L += ["", f"### The same pairs under all three goals ({mr(v(ps, 'all_three', 'n'), 0)} pairs per model)", ""]
        L += head("goal", "a_interface", "a_encoding", "a_direct")
        for g in ("G1", "G2", "G3"):
            L.append(row(g, *[mr(v(ps, "all_three", g, k)) for k in ("a_interface", "a_encoding", "a_direct")]))
        L += ["", "### Within-pair regressions (pair fixed effects; covariates TV, logit-difference norm, oracle gap)", ""]
        L += head("outcome", "model", "coefficient", "median (range)", "p (two-sided)", "p (β < 0)")
        for r in ("interface", "encoding", "direct"):
            for mod, ml, keys in (("primary", "direct-adequate + controls (Q2)", ("direct_adequate",)), ("with_goal", "+ goal dummies (Q2b)", ("direct_adequate", "G2", "G3")),
                                  ("goal_only", "goal dummies + controls (Q1)", ("G2", "G3")), ("with_interface_adequacy", "+ interface-adequate", ("direct_adequate", "interface_adequate"))):
                for k in keys:
                    x = v(ps, "regression", r, mod, k)
                    L.append(row(f"a_{r}", ml, k, mr(x), fp(p2(x)), fp(pl(x))))
        # per-model goal effects (magnitude, whatever the direction)
        g2, g3 = v(ps, "regression", "interface", "goal_only", "G2"), v(ps, "regression", "interface", "goal_only", "G3")
        spread = np.max(np.abs(np.stack([g2, g3, g2 - g3])), 0)
        L += ["", f"Largest within-pair goal contrast in a_interface per model (|G2 − G1|, |G3 − G1|, |G3 − G2|, controls held): {mr(spread)}; "
              f"models with a contrast ≥ 0.05: {int((spread >= 0.05).sum())} of 10.", ""]
        if ps in R[seeds[0]] and "contrast" in R[seeds[0]][ps]:
            L += ["### Matched contrast: two goals of the same pair, direct route inadequate under one and adequate under the other", ""]
            L += head("", "contrasts", "Δ a_interface (inadequate − adequate)", "Δ TV", "Δ gap", "matched (|Δ TV| < 0.1, |Δ gap| < 0.02)", "Δ a_interface, matched")
            q = lambda k: v(ps, "contrast", k)
            L.append(row("all", mr(q("n"), 0), mr(q("diff_interface")), mr(q("diff_tv")), mr(q("diff_gap"), 4), mr(q("n_matched"), 0), mr(q("diff_interface_matched"))))
            L.append("")
    L += ["## Probe accuracy (held-out histories): greedy action of the probe optimal", ""]
    L += head("route", "G1", "G2", "G3")
    for r in ("direct", "interface"):
        L.append(row(r, *[mr(v("probe_accuracy", f"{r}_G{g}")) for g in (1, 2, 3)]))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


def _get(d, path):
    for p in path:
        d = d[p]
    return d


if __name__ == "__main__":
    main()
