"""Round 28: tables from results.json.

    .venv/bin/python rounds/r28_policy_belief_edit/tables.py            # writes tables.md
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from scipy.stats import wilcoxon

OUT = Path(__file__).resolve().parent
READERS = (("head", "new head"), ("policy_natural", "original policy, natural access"), ("policy_removed", "original policy, direct route removed"))
KINDS = (("none", "none"), ("whole", "whole"), ("encoding", "**encoding**"), ("rotated", "rotated encoding"), ("random", "random patch"), ("pca", "PCA patch"))
f = lambda x, d=3: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
mr = lambda xs, d=3: f"{f(np.median(xs), d)} ({f(np.min(xs), d)}–{f(np.max(xs), d)})"
fp = lambda p: "< 0.001" if p < 0.001 else f"{p:.3f}"
p_gt = lambda a, b: float(wilcoxon(a, b, alternative="greater", method="exact").pvalue)


def main():
    res = json.load(open(OUT / "results.json"))
    R = res["runs"]
    seeds = sorted(R, key=lambda s: int(s[4:]))
    v = lambda *path: np.array([_get(R[s], path) for s in seeds], dtype=float)
    L = ["# Round 28 tables", "", "Generated by `rounds/r28_policy_belief_edit/tables.py`. Round 23's ten reward-only models; edit at the residual stream entering block 1 "
         "at every prefix token. Median (range) over the ten models; the head's values are the mean of its three heads. Change cells: the two posteriors' optimal sets are "
         "disjoint under that goal; preserve cells: identical. T: transfer, the share of the way from no edit to the reader's behaviour on the donor's evidence (policy: hybrid; "
         "head: whole). S: the share of the whole interface patch's effect. p: exact Wilcoxon signed-rank over the ten models.", ""]
    for pset, pl in (("main", "main pairs"), ("onestep", "one-step agreeing pairs (change cells only)")):
        L += [f"## {pl}", ""]
        for rd, rl in READERS:
            L += [f"### {rl}", ""]
            L += head("edit", "change: donor-optimal", "T", "S", "change: moved", "preserve: still optimal", "preserve: unchanged", "regret at the donor's posterior (change)")
            ks = KINDS + ((("hybrid", "*hybrid (donor's own prefix)*"),) if rd != "head" else ())
            for k, kl in ks:
                g = lambda *p: v(pset, rd, k, *p)
                L.append(row(kl, mr(g("change", "donor_optimal")), mr(g("transfer")), mr(g("share_of_interface")) if k != "hybrid" else "", mr(g("change", "moved")),
                             mr(g("preserve", "donor_optimal")) if pset == "main" else "", mr(g("preserve", "unchanged")) if pset == "main" else "", mr(g("change", "regret_donor"), 4)))
            L.append("")
    # decision rule
    L += ["## Decision rule (main pairs, change cells)", ""]
    Th, Tp = v("main", "head", "encoding", "transfer"), v("main", "policy_natural", "encoding", "transfer")
    Sh, Sp = v("main", "head", "encoding", "share_of_interface"), v("main", "policy_natural", "encoding", "share_of_interface")
    D = lambda rd, k: v("main", rd, k, "change", "donor_optimal")
    L += head("", "quantity", "value", "test")
    L.append(row("H", "T_head(encoding)", mr(Th), f"above rotated p {fp(p_gt(D('head', 'encoding'), D('head', 'rotated')))}, above random patch p {fp(p_gt(D('head', 'encoding'), D('head', 'random')))}"))
    L.append(row("", "T_policy(encoding), natural", mr(Tp), f"above rotated p {fp(p_gt(D('policy_natural', 'encoding'), D('policy_natural', 'rotated')))}, above random patch p {fp(p_gt(D('policy_natural', 'encoding'), D('policy_natural', 'random')))}"))
    L.append(row("", "T_policy / T_head (encoding)", mr(Tp / Th), f"T_head above T_policy p {fp(p_gt(Th, Tp))}"))
    L.append(row("", "T_policy(whole), natural", mr(v("main", "policy_natural", "whole", "transfer")), ""))
    L.append(row("", "S_policy(encoding) / S_head(encoding), natural", mr(Sp / Sh), f"S_head above S_policy p {fp(p_gt(Sh, Sp))}; S_policy above S_head p {fp(p_gt(Sp, Sh))}"))
    Tr, Sr = v("main", "policy_removed", "encoding", "transfer"), v("main", "policy_removed", "encoding", "share_of_interface")
    L.append(row("secondary", "direct route removed: T_policy(whole), T_policy(encoding), S_policy(encoding)",
                 f"{mr(v('main', 'policy_removed', 'whole', 'transfer'))}; {mr(Tr)}; {mr(Sr)}", f"S_policy(removed) / S_head {mr(Sr / Sh)}"))
    L += ["", "## The encoding at the interface", ""]
    L += head("", "encoding R² (state from posterior and position)", "within position", "edit norm / actual difference", "cosine(edit, difference)", "residual share")
    L.append(row("main pairs", mr(v("encoding_r2")), mr(v("encoding_r2_within_position")), mr(v("main", "stats", "edit_norm_over_diff_norm")), mr(v("main", "stats", "cosine")), mr(v("main", "stats", "residual_share"))))
    L.append(row("one-step agreeing", "", "", mr(v("onestep", "stats", "edit_norm_over_diff_norm")), mr(v("onestep", "stats", "cosine")), mr(v("onestep", "stats", "residual_share"))))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


def _get(d, path):
    for p in path:
        d = d[p]
    return np.nan if d is None else d


if __name__ == "__main__":
    main()
