"""The interior-goals experiment: tables and the registered decision rule, from results_single.json and
results_collect.json here and the maze10 experiment's results.json.

    .venv/bin/python studies/7_information_seeking/interior_goals/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np
from scipy.stats import mannwhitneyu

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
REFS = (("oracle", "oracle"), ("qmdp2", "QMDP + lookahead"), ("qmdp", "QMDP"), ("mls", "most likely cell"), ("random", "random moves"))
p_less = lambda a, b: float(mannwhitneyu(a, b, alternative="less", method="exact").pvalue)


def arm(R):
    seeds = sorted(R["runs"], key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(R["runs"][s], p)) is None else x for s in seeds], dtype=float)
    return v, len(seeds)


def recovery(v):
    nat, blind = v("natural", "ret"), v("online", "goal_blind", "ret")
    return (v("online", "additive", "ret") - blind) / (nat - blind)


def main():
    C4 = json.load(open(OUT.parent / "maze10" / "results.json"))
    S, B = json.load(open(OUT / "results_single.json")), json.load(open(OUT / "results_collect.json"))
    vc, _ = arm(C4); vs, n = arm(S); vb, _ = arm(B)
    const = lambda x: np.full(n, x)
    L = ["# The interior-goals experiment tables", "",
         "Generated by `studies/7_information_seeking/interior_goals/tables.py`. Six reward-trained models per arm; the maze10 maze with six junction goals. "
         "Evaluation episodes fixed per arm (8 192 single, 4 096 collect). Median (range) over models. maze10: that experiment's models (four spread goals).", "",
         "## Behaviour", ""]
    L += head("", "maze10 (four spread goals)", "single junction goal", "collect two junction goals")
    L.append(row("**models: return**", mr(vc("natural", "ret")), mr(vs("natural", "ret")), mr(vb("natural", "ret"))))
    L.append(row("models: success (collect: both goals)", mr(vc("natural", "success")), mr(vs("natural", "success")), mr(vb("natural", "success"))))
    for k, kl in REFS:
        L.append(row(f"{kl}: return (success)", *[f"{f(R['references'][k]['ret'])} ({f(R['references'][k]['success'], 2)})" for R in (C4, S, B)]))
    L += ["", "## The additive policy, run in the environment", ""]
    L += head("", "maze10", "single junction goal", "collect two junction goals")
    for k, kl in (("additive", "**additive: argmax H + G**"), ("goal_blind", "goal-blind: argmax H"), ("history_blind", "history-blind: argmax G")):
        L.append(row(f"{kl}, return", *[mr(v("online", k, "ret")) for v in (vc, vs, vb)]))
    rc, rs, rb = recovery(vc), recovery(vs), recovery(vb)
    L.append(row("**recovery** (additive − goal-blind) / (natural − goal-blind)", mr(rc, 2), mr(rs, 2), mr(rb, 2)))
    L.append(row("the model's move depends on the goal (state): share of decisions", mr(vc("additive_offline", "goal_matters_share")), mr(vs("additive_offline", "goal_matters_share")),
                 mr(vb("additive_offline", "all", "goal_matters_share"))))
    L.append(row("there: the additive choice is the model's move", mr(vc("additive_offline", "same_action_goal_matters")), mr(vs("additive_offline", "same_action_goal_matters")),
                 mr(vb("additive_offline", "all", "same_action_goal_matters"))))
    L.append(row("there: the goal-blind choice is the model's move", mr(vc("additive_offline", "same_action_goal_blind")), mr(vs("additive_offline", "same_action_goal_blind")),
                 mr(vb("additive_offline", "all", "same_action_goal_blind"))))
    L.append(row("additive share of the logits' goal dependence", mr(vc("additive_offline", "additive_share")), mr(vs("additive_offline", "additive_share")),
                 mr(vb("additive_offline", "all", "additive_share"))))
    rcI = (vc("removal", "noI", "ret") - vc("removal", "goal_blind", "ret")) / (vc("removal", "natural", "ret") - vc("removal", "goal_blind", "ret"))
    rsI = (vs("removal", "noI", "ret") - vs("removal", "goal_blind", "ret")) / (vs("removal", "natural", "ret") - vs("removal", "goal_blind", "ret"))
    L += ["", "## Single-goal arms: removals at the decision token, online", ""]
    L += head("at the decision token", "maze10", "single junction goal")
    for k, kl in (("natural", "nothing"), ("noI", "interaction removed"), ("noH", "history part removed, interaction kept"), ("noG", "goal part removed, interaction kept"),
                  ("goal_blind", "reference: goal-blind policy")):
        L.append(row(kl, mr(vc("removal", k, "ret")), mr(vs("removal", k, "ret"))))
    L.append(row("**recovery**, interaction removed", mr(rcI, 2), mr(rsI, 2)))
    L += ["", "## Collect arm: before and after the first pickup", ""]
    L += head("", "before the first pickup", "after it")
    for k, kl in (("goal_matters_share", "the model's move depends on the goal state"), ("same_action_goal_matters", "there: the additive choice is the model's move"),
                  ("same_action_goal_blind", "there: the goal-blind choice is the model's move"), ("additive_share", "additive share of the logits' goal dependence")):
        L.append(row(kl, mr(vb("additive_offline", "before", k)), mr(vb("additive_offline", "after", k))))
    L += ["", "Collect arm, behaviour:", ""]
    L += head("policy", "return", "goals collected", "both", "first pickup is the goal nearer to the spawn")
    L.append(row("**models**", mr(vb("natural", "ret")), mr(vb("natural", "collected")), mr(vb("natural", "success")), mr(vb("natural", "first_is_nearer"))))
    for k, kl in (("additive", "additive policy"), ("goal_blind", "goal-blind"), ("history_blind", "history-blind")):
        L.append(row(kl, mr(vb("online", k, "ret")), mr(vb("online", k, "collected")), mr(vb("online", k, "success")), mr(vb("online", k, "first_is_nearer"))))
    for k, kl in REFS:
        d = B["references"][k]
        L.append(row(kl, f(d["ret"]), f(d["collected"]), f(d["success"]), f(d["first_is_nearer"])))
    L += ["", "## Information seeking (collect arm: before the first pickup)", ""]
    L += head("", "deviates from QMDP", "information gain of its move − QMDP's, at deviations", "a random other move in the same states", "posterior entropy: mean; steps 0, 5, 10, 20")
    for name, v, R in (("maze10", vc, C4), ("single junction goal", vs, S), ("collect two junction goals", vb, B)):
        e = [np.median([(R["runs"][s]["natural"]["entropy_by_step"][i] or np.nan) for s in R["runs"]]) for i in range(4)]
        q = R["references"]["qmdp"]
        L.append(row(f"**models, {name}**", mr(v("natural", "deviation_rate")), mr(v("natural", "ig_advantage"), 4), mr(v("natural", "ig_advantage_random_same_state"), 4),
                     f"{mr(v('natural', 'entropy_mean'), 2)}; " + ", ".join(f(x, 2) for x in e)))
        L.append(row(f"QMDP, {name}", "0", "—", "—", f"{f(q['entropy_mean'], 2)}; " + ", ".join(f(x, 2) for x in q["entropy_by_step"][:4])))
    L += ["", "## Single junction goal: decoders", ""]
    L += head("", "maze10", "single junction goal")
    for k, kl in (("posterior_r2", "exact posterior, R²"), ("occupancy_r2_state", "occupancy R² from the state"), ("occupancy_r2_posterior_goal_step", "occupancy R² from posterior × goal × step")):
        L.append(row(kl, mr(vc("decoders", k)), mr(vs("decoders", k))))
    yes = lambda b: "**yes**" if b else "no"
    pP, pC = p_less(rs, rc - 0.15), p_less(rb, rs - 0.15)
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "value", "held")
    for name, v, R in (("single", vs, S), ("collect", vb, B)):
        nat, mls_ = v("natural", "ret"), R["references"]["mls"]["ret"]
        L.append(row(f"**LEARN** ({name})", "return ≥ the most-likely-cell policy's", f"{f(np.median(nat))} against {f(mls_)}; p {fp(p_gt(nat, const(mls_)))}", yes(np.median(nat) >= mls_)))
    L.append(row("**AD** (single)", "additive policy: recovery ≥ 0.9", f(np.median(rs), 2), yes(np.median(rs) >= 0.9)))
    L.append(row("**AD** (collect)", "additive policy: recovery ≥ 0.9", f(np.median(rb), 2), yes(np.median(rb) >= 0.9)))
    L.append(row("**PLACE**", "single arm's recovery lower than maze10's by ≥ 0.15", f"{f(np.median(rs), 2)} against {f(np.median(rc), 2)}; p {fp(pP)}", yes(np.median(rc) - np.median(rs) >= 0.15 and pP < 0.05)))
    L.append(row("**COLLECT**", "collect arm's recovery lower than the single arm's by ≥ 0.15", f"{f(np.median(rb), 2)} against {f(np.median(rs), 2)}; p {fp(pC)}", yes(np.median(rs) - np.median(rb) >= 0.15 and pC < 0.05)))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
