"""Round 19: tables from results.json.

    .venv/bin/python rounds/r19_occupancy/tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

OUT = Path("rounds/r19_occupancy")
f = lambda x, d=2: "—" if x is None else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]


def main():
    r = json.load(open(OUT / "results.json")); R, sites = r["runs"], r["sites"]
    runs = [k[:-6] for k in R if k.endswith("/final")]
    best = lambda m, t, s: max(v[s] for v in m["decode"][t].values())
    L = ["# Round 19 tables", "", f"Generated by `rounds/r19_occupancy/tables.py`. {r['rows']} rows (12 000 histories × 3 goals) at the reveal: {r['fit']} fitted, "
         f"{r['held_evidence']} with held-out evidence, {r['held_combination']} held-out evidence–goal combinations. R² is the share of total variance, held out.", "",
         "## 1. Exact-feature predictors of occupancy (held-out combinations)", ""] + head("model", "occupancy of", "P0 goal mean", "P1 [b, goal]", "P2 b per goal", "P3 [b, Q*] per goal",
                                                                                         "residual share (after P3)", "after P4 (with the model's action distribution)")
    for k in runs:
        e = R[k + "/final"]["exact"]
        for nm in ("solver", "model"):
            if nm == "solver" and k != runs[0]:
                continue
            L.append(row("any" if nm == "solver" else k, nm, *[f(e[nm][p]["held_combination"]) for p in ("P0", "P1", "P2", "P3")], f(e[nm]["residual_share"], 3),
                         f(e[nm].get("residual_share_P4"), 3)))
    targets = ("posterior", "action_values", "advantage", "occupancy_solver", "occupancy_model", "residual_solver_P2", "residual_solver", "residual_model", "residual_model_policy")
    for s, title in (("held_combination", "held-out combinations"), ("held_evidence", "held-out evidence")):
        L += ["", f"## 2. Decoding at the goal token, best site ({title})", ""] + head("model", "checkpoint", *targets)
        for k in runs:
            for lab in ("init", "final"):
                if lab == "init" and not k.endswith("seed0"):
                    continue
                L.append(row(k, lab, *[f(best(R[f"{k}/{lab}"], t, s)) for t in targets]))
    L += ["", "## 3. By site, reward-trained models (mean of 5 seeds, final; held-out combinations)", ""] + head("target", *sites)
    ppo = [k for k in runs if k.startswith("ppo")]
    for t in targets:
        L.append(row(t, *[f(np.mean([R[k + "/final"]["decode"][t][s]["held_combination"] for k in ppo])) for s in sites]))
    L += ["", "Same, at initialisation:", ""] + head("target", *sites)
    for t in targets:
        L.append(row(t, *[f(np.mean([R[k + "/init"]["decode"][t][s]["held_combination"] for k in ppo])) for s in sites]))
    L += ["", "## 4. At the last prefix token (goal unknown), decoders per goal, held-out evidence; reward-trained, final", ""] + head("target", *sites)
    for t in ("posterior", "action_values", "occupancy_solver"):
        L.append(row(t, *[f(np.mean([R[k + "/final"]["prefix_decode"][t][s] for k in ppo])) for s in sites]))
    L += ["", "## 5. A decoder fitted without one goal, tested on it (goal means removed; last site)", ""] + head("model", *[f"{t}: held-out goal / own goal" for t in ("posterior", "action_values", "occupancy_solver")])
    for k in runs:
        tr = R[k + "/final"]["transfer"]
        L.append(row(k, *[f"{f(tr[t][sites[-1]]['held_out_goal'])} / {f(tr[t][sites[-1]]['own_goal'])}" for t in ("posterior", "action_values", "occupancy_solver")]))
    for ps, title in (("same_evidence", "the same evidence, two goals"), ("same_goal", "the same goal, two pieces of evidence")):
        L += ["", f"## 6. Pairs with the same first action and different occupancy: {title}", "",
              "Slope of the predicted occupancy difference on the true one.", ""] + \
            head("model", "checkpoint", "pairs", "true L1", "TV of the model's actions", "activations", "P0", "P1", "P2", "P3", "action values (activations)", "model's occupancy: activations", "P4")
        for k in runs:
            for lab in ("init", "final"):
                if lab == "init" and not k.endswith("seed0"):
                    continue
                p = R[f"{k}/{lab}"]["pairs"][ps]
                L.append(row(k, lab, p["n"], f(p["true_l1"]), f(p["model_tv"]), *[f(p["occupancy"][x]) for x in ("activations", "P0", "P1", "P2", "P3")],
                             f(p["action_values"]["activations"]), f(p["occupancy_model"]["activations"]), f(p["occupancy_model"]["P4"])))
    L += ["", "## 7. The models' own occupancy against the solver's", ""] + head("model", "expected regret at the reveal", "G1", "G2", "G3", "L1 gap to the solver's occupancy", "G1", "G2", "G3")
    for k in runs:
        m = R[k + "/final"]["model"]
        L.append(row(k, f(m["regret"], 4), *[f(m[f"regret_G{g}"], 4) for g in (1, 2, 3)], f(m["occupancy_gap_l1"]), *[f(m[f"occupancy_gap_G{g}"]) for g in (1, 2, 3)]))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[:60]))


if __name__ == "__main__":
    main()
