"""The cross-history-MLP experiment: tables from results.json.

    .venv/bin/python studies/5_goal_belief_mechanism/cross_history_mlp/tables.py            # writes tables.md
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
f = lambda x, d=2: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
mr = lambda xs, d=2: f"{f(np.median(xs), d)} ({f(np.min(xs), d)}–{f(np.max(xs), d)})"
SETS = (("none", "no patch"), ("L0.mlp", "L0.mlp (before the interface)"), ("L1.mlp", "L1.mlp"), ("L2.mlp", "L2.mlp"), ("L3.mlp", "L3.mlp"),
        ("selected_r30", "the goal-swap-components experiment's selected MLPs"), ("mlps_1_3", "**all three MLPs of blocks 1–3**"))


def reading(x):
    d, o, k = x["greedy_donor_action"], x["greedy_own_under_donor_goal"], x["greedy_recipient"]
    if o >= 0.5 and o > d:
        return "goal instruction"
    if d >= 0.5 and d > o:
        return "donor's action"
    if k >= 0.5:
        return "retained"
    return "mixed"


def main():
    R = json.load(open(OUT / "results.json"))["runs"]
    seeds = sorted(R, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(R[s], p) for s in seeds], dtype=float)
    L = ["# The cross-history-MLP experiment tables", "", "Generated by `studies/5_goal_belief_mechanism/cross_history_mlp/tables.py`. The observation-prediction experiment's ten reward models; held-out histories; patches at the goal token. "
         f"Cross-goal cells per model {mr(v('n_cross'), 0)}, same-goal cells {mr(v('n_same'), 0)}. Median (range) over the ten models; greedy shares.", ""]
    L += ["## Cross-goal cells: donor A under g′ (chooses a_A′) into recipient B under g (chooses a_B; would choose a_B′ under g′)", ""]
    L += head("patched MLP outputs", "a_A′ donor's action", "a_B′ own action under donor goal", "a_B retained", "other", "reading (median shares)", "P(a_A′)", "P(a_B′)", "P(a_B)")
    for k, kl in SETS:
        g = lambda m: v("cross", k, m)
        med = {m: np.median(g(m)) for m in ("greedy_donor_action", "greedy_own_under_donor_goal", "greedy_recipient")}
        L.append(row(kl, mr(g("greedy_donor_action")), mr(g("greedy_own_under_donor_goal")), mr(g("greedy_recipient")), mr(g("greedy_other")), reading(med),
                     mr(g("prob_donor_action")), mr(g("prob_own_under_donor_goal")), mr(g("prob_recipient"))))
    L += ["", "## Within-history reference: the same MLP outputs from B's own run under g′", ""]
    L += head("patched MLP outputs", "a_B′ own action under donor goal", "a_A′", "a_B retained", "other")
    for k, kl in SETS[1:]:
        g = lambda m: v("within", k, m)
        L.append(row(kl, mr(g("greedy_own_under_donor_goal")), mr(g("greedy_donor_action")), mr(g("greedy_recipient")), mr(g("greedy_other"))))
    L += ["", "## Same-goal cells: donor A under the recipient's goal g (chooses a_A ≠ a_B)", ""]
    L += head("patched MLP outputs", "a_A donor's action", "a_B retained", "other")
    for k, kl in SETS[1:]:
        g = lambda m: v("same", k, m)
        L.append(row(kl, mr(g("greedy_donor_action")), mr(g("greedy_recipient")), mr(g("greedy_other"))))
    L += ["", "## Representation: held-out R² of each MLP's goal-token output", ""]
    L += head("MLP", "goal", "goal × action", "goal × posterior", "both", "goal × action / both", "both − goal × action", "reading")
    for l in range(4):
        g = lambda m: v("representation", f"L{l}.mlp", m)
        ga, gb, both = g("goal_x_action"), g("goal_x_posterior"), g("both")
        rd = "action preference" if np.median(ga / both) >= 0.8 else ("evidence–goal combination" if np.median(gb) > np.median(ga) and np.median(both - ga) >= 0.1 else "neither")
        L.append(row(f"L{l}.mlp", mr(g("goal")), mr(ga), mr(gb), mr(both), mr(ga / both), mr(both - ga), rd))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


def _get(d, p):
    for k in p:
        d = d[k]
    return d


if __name__ == "__main__":
    main()
