"""The what-is-H experiment: tables and the registered decision rule from results.json and untrained.json.

    .venv/bin/python studies/5_goal_belief_mechanism/what_is_H/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
NAMES = dict(maxQ="max_g Q*", meanQ="mean_g Q*", popt="P(optimal | random goal)", maxA="max_g advantage", maxMDP="max_g Q_MDP (reachability)",
             meanMDP="mean_g Q_MDP (reachability)", nearest="nearest goal", blin="ceiling: affine in b", Htab="ceiling: H per posterior")


def main():
    R = json.load(open(OUT / "results.json"))
    U = json.load(open(OUT / "untrained.json"))["runs"]
    runs, CANDS = R["runs"], R["candidates"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    u = lambda *p: np.array([_get(U[s], p) for s in seeds], dtype=float)
    ALL = list(CANDS) + ["blin", "Htab"]
    L = ["# The what-is-H experiment tables", "", "Generated by `studies/5_goal_belief_mechanism/what_is_H/tables.py`. The observation-prediction experiment's ten reward models (and their initial checkpoints for prediction); H = the "
         "goal-averaged centred logits at the goal token. Median (range) over the ten models.", ""]
    L += ["## Prediction of H (held-out) and the decision with the fitted H + goal bias", ""]
    L += head("candidate", "R² flexible", "R² one slope", "top action agrees", "untrained R² flexible", "decision: optimal on goal-dependent cells")
    for k in ALL:
        L.append(row(NAMES[k], mr(v("prediction", k, "r2_flexible"), 2), mr(v("prediction", k, "r2_one_slope"), 2) if k in CANDS else "—",
                     mr(v("prediction", k, "top_agree"), 2) if k in CANDS else "—", mr(u("prediction", k, "r2_flexible"), 2), mr(v("prediction", k, "decision_goal_dependent"))))
    L.append(row("(references) natural policy / H itself + G", "", "", "", "", f"{mr(v('decision_reference', 'natural'))} / {mr(v('decision_reference', 'additive_H'))}"))
    for site in ("resid2", "resid4"):
        lab = "entering block 2 (primary)" if site == "resid2" else "final residual stream"
        L += ["", f"## Causal edits at the goal token, {lab}: the same vector (C(b_B) − C(b_A)) W under every goal", ""]
        L += head("edit", "change cells: donor-optimal", "gain over none", "share of whole's gain", "goal-dependent pairs: right under every change goal", "preserve: harm")
        ch = lambda k: v("edits", site, "change", k, "donor_optimal")
        for k in ["none", "whole"] + ALL + ["rotated"]:
            nm = NAMES.get(k, k)
            L.append(row(nm, mr(ch(k)), mr(ch(k) - ch("none")), mr((ch(k) - ch("none")) / (ch("whole") - ch("none")), 2),
                         mr(v("edits", site, "goal_dependent", k, "right_every_change_goal")), mr(v("edits", site, "preserve", k, "harm")) if k != "none" else "—"))
    # decision rule
    r2 = {k: v("prediction", k, "r2_flexible") for k in ALL}
    best = max(CANDS, key=lambda k: np.median(r2[k]))
    order = sorted(CANDS, key=lambda k: -np.median(r2[k]))
    runner = order[1]
    pMQ = p_gt(r2["maxQ"], r2[order[0] if order[0] != "maxQ" else order[1]])
    MQ = best == "maxQ" and pMQ < 0.05
    EXPL = np.median(r2[best] / r2["Htab"])
    ch = lambda k: v("edits", "resid2", "change", k, "donor_optimal")
    gain = lambda k: ch(k) - ch("none")
    pCE = p_gt(ch(best), v("edits", "resid2", "change", "rotated", "donor_optimal"))
    CEr = np.median(gain(best) / gain("whole"))
    AGd = min(np.median(gain(best) - gain(k)) for k in CANDS if k != best)
    Dr = np.median(v("prediction", best, "decision_goal_dependent") / v("decision_reference", "additive_H"))
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule", "", f"Ranking by median flexible R²: " + " > ".join(f"{k} ({f(np.median(r2[k]), 2)})" for k in order) +
          f". Best against runner-up ({runner}): p {fp(p_gt(r2[best], r2[runner]))}, best higher in {int((r2[best] > r2[runner]).sum())} of 10 models.", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**MQ**", "maxQ best, above the runner-up", f"maxQ ranks {order.index('maxQ') + 1} of {len(CANDS)} ({f(np.median(r2['maxQ']), 2)})", yes(MQ)))
    L.append(row("**EXPL**", "best R² ≥ 0.8 × Htab's", f"{best}: {f(EXPL, 2)} ×", yes(EXPL >= 0.8)))
    L.append(row("**CE**", "best's edit gain ≥ 0.5 × whole's, above rotated", f"{f(CEr, 2)} ×; p {fp(pCE)}", yes(CEr >= 0.5 and pCE < 0.05)))
    L.append(row("**AG**", "best's edit gain ≥ every other candidate's − 0.02", f"smallest margin {f(AGd)}", yes(AGd >= -0.02)))
    L.append(row("**D**", "decision with best ≥ 0.9 × with H", f"{f(Dr, 2)} ×", yes(Dr >= 0.9)))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
