"""The pattern-specificity experiment: tables from results.json.

    .venv/bin/python studies/3_reward_trained_agents/pattern_specificity/tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

OUT = Path("studies/3_reward_trained_agents/pattern_specificity")
DRAWS = 5
f = lambda x, d=2: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
CONDS = (("raw_route_removed", "raw route removed"), ("intact", "raw route intact"))


def draws(c, pre, get):
    """Mean and range over the random draws."""
    v = [get(c[f"{pre}_{i}"]) for i in range(DRAWS)]
    v = [x for x in v if x is not None]
    return f"{f(np.mean(v))} ({f(min(v))}–{f(max(v))})" if v else "—"


def cell(c, k, get):
    return draws(c, k, get) if f"{k}_0" in c else f(get(c[k]))


def trimmed(x):
    """Post hoc: the bin-weighted difference over bins in which `moved` is defined for both sets and within [-1, 1]
    (the lowest bins of s_model have TV(base, hybrid) near zero, and the ratio is unbounded there)."""
    ok = [(a, b, na + nb) for a, b, na, nb in zip(x["uncertainty"], x["mode"], x["n_uncertainty"], x["n_mode"]) if a is not None and b is not None and abs(a) <= 1 and abs(b) <= 1]
    return sum((a - b) * w for a, b, w in ok) / sum(w for _, _, w in ok) if ok else None


def main():
    r = json.load(open(OUT / "results.json")); R = r["runs"]
    L = ["# The pattern-specificity experiment tables", "", f"Generated by `studies/3_reward_trained_agents/pattern_specificity/tables.py`. {r['pairs']} recipient–donor pairs from the new bank: {r['sets']['mode']} mode, "
         f"{r['sets']['uncertainty']} uncertainty, {r['sets']['similar']} similar-posterior, {r['sets']['evidence']} with posteriors ≥ 0.5 apart (cross-goal); "
         f"{r['matched_pairs']} posterior-binned pairs. Random edits: mean over {DRAWS} draws (range).", "",
         "## 0. The frozen subspaces", ""] + head("model", "rank k", "decoder R² (held out)", "variance in top-k PCs", "variance in pattern span", "overlap of pattern and PCA spans (1 = same; k/128 = unrelated)", "rank of equal-share random")
    for k, m in R.items():
        s = m["subspaces"]
        L.append(row(k, s["k"], f(s["decoder_r2"]), f(s["pca_variance_share"]), f(s["variance_in_pattern"]), f(s["pattern_in_pca"]), s["random_share_rank"]))
    main_edits = ("whole", "pattern", "pattern_shift", "pattern_complement", "belief", "pca", "pca_out_pattern", "pattern_out_pca", "random_rank", "random_share", "random_norm")
    for cond, title in CONDS:
        L += ["", f"## 1. Edits, {title}: rank; magnitude; captured share; moved to the hybrid (mode / uncertainty); solver gain (mode); arbitrary (mode)", ""] + head("model", *main_edits)
        for k, m in R.items():
            c = m[cond]
            L.append(row(k, *[f"{c[e if e in c else e + '_0']['rank'] or '—'}; {cell(c, e, lambda x: x['magnitude'])}; {cell(c, e, lambda x: x['share'])}; "
                              f"{cell(c, e, lambda x: x['mode'].get('moved'))} / {cell(c, e, lambda x: x['uncertainty'].get('moved'))}; "
                              f"{cell(c, e, lambda x: x['mode'].get('solver_gain'))}; {cell(c, e, lambda x: x['mode'].get('arbitrary'))}" for e in main_edits]))
        L += ["", f"## 2. Rank sweep, {title}: captured share → moved to the hybrid (mode pairs)", ""] + head("model", "family", "rank 1", "2", "4", "7", "k")
        for k, m in R.items():
            c = m[cond]
            for fam, full in (("pattern", "pattern"), ("pca", "pca"), ("random", "random_rank")):
                names = [f"{fam}_r{q}" for q in (1, 2, 4, 7)] + [full]
                L.append(row(k, fam, *[f"{cell(c, n, lambda x: x['share'])} → {cell(c, n, lambda x: x['mode'].get('moved'))}" for n in names]))
    L += ["", "## 2b. Pattern against PCA at equal captured share (mode pairs)", "",
          "Moved by the pattern edit at rank r, minus the PCA curve (through the origin, ranks 1, 2, 4, 7, k and the whole patch) interpolated at the same captured share.", ""]
    for cond, title in CONDS:
        L += ["", f"### {title}", ""] + head("model", "rank 1", "2", "4", "7", "k", "mean over ranks ≤ 7")
        for k, m in R.items():
            c = m[cond]
            xs = [0.0] + [c[n]["share"] for n in ("pca_r1", "pca_r2", "pca_r4", "pca_r7", "pca")] + [1.0]
            ys = [0.0] + [c[n]["mode"]["moved"] for n in ("pca_r1", "pca_r2", "pca_r4", "pca_r7", "pca")] + [c["whole"]["mode"]["moved"]]
            d = [c[n]["mode"]["moved"] - float(np.interp(c[n]["share"], xs, ys)) for n in ("pattern_r1", "pattern_r2", "pattern_r4", "pattern_r7", "pattern")]
            L.append(row(k, *[f(x) for x in d], f(np.mean(d[:4]))))
    L += ["", "## 3. Posterior-matched histories: TV(edited, base), and as a share of the whole patch's, by the L1 distance between the posteriors", ""]
    pm_edits = ("whole", "pattern", "pattern_shift", "pattern_complement", "pca", "random_share_0", "belief")
    for cond, title in CONDS:
        L += ["", f"### {title}", ""] + head("model", "posterior L1", "pairs", "TV(base, hybrid)", *pm_edits)
        for k, m in R.items():
            for b in m["posterior_matched"][cond]:
                if "whole" in b:
                    L.append(row(k, f"{b['lo']:g}–{min(b['hi'], 2):g}", b["n"], f(b["tv_base_hybrid"], 3), *[f"{f(b[e]['tv_from_base'], 3)} ({f(b[e]['share_of_whole'])})" for e in pm_edits]))
    cg_edits = ("whole", "pattern", "pattern_shift", "pattern_complement", "pca", "random_share_0")
    for cond, title in CONDS:
        L += ["", f"## 4. Across goals, {title}: per goal, gain on the solver's set for the donor (share of the hybrid's) / TV from base", ""] + head("model", "goal", "pairs", "hybrid's gain", *cg_edits)
        for k, m in R.items():
            for g, v in m["cross_goal"][cond]["per_goal"].items():
                L.append(row(k, g, v["n"], f(v["hybrid_gain"]), *[f"{f(v[e]['gain'])} / {f(v[e]['changed'])}" for e in cg_edits]))
        L += ["", f"Both goals, {title}: appropriate under both / changed under both but not appropriate.", ""] + head("model", "goals", "pairs", "base", "hybrid", *cg_edits)
        for k, m in R.items():
            for g, v in m["cross_goal"][cond]["both"].items():
                if "whole" in v:
                    L.append(row(k, g, v["n"], *[f"{f(v[e]['appropriate_both'])} / {f(v[e]['changed_not_appropriate'])}" for e in ("base", "hybrid") + cg_edits]))
    L += ["", "## 5. Uncertainty against mode pairs, raw route intact: moved to the hybrid within quintiles of the size of the change", ""]
    for size, title in (("s_solver", "s_solver: regret under the donor's posterior of the recipient's optimal action (responsive pairs)"), ("s_model", "s_model: TV(base, hybrid) (all pairs)")):
        L += ["", f"### {title}", ""] + head("model", "edit", "mean size (unc / mode)", "bins: uncertainty / mode (n)", "unmatched difference [95 %]", "matched difference [95 %]", "post hoc: matched, bins where both sets have TV(base, hybrid) responsive (moved within [−1, 1])")
        for k, m in R.items():
            u = m["uncertainty_vs_mode"].get(size)
            if not u:
                continue
            for e in ("whole", "pattern"):
                x = u[e]
                bins = "; ".join(f"{f(a)} / {f(b)} ({na}, {nb})" for a, b, na, nb in zip(x["uncertainty"], x["mode"], x["n_uncertainty"], x["n_mode"]))
                L.append(row(k, e, f"{f(u['mean_size']['uncertainty'], 3)} / {f(u['mean_size']['mode'], 3)}", bins,
                             f"{f(x['unmatched_difference'])} [{f(x['unmatched_ci'][0])}, {f(x['unmatched_ci'][1])}]", f"{f(x['matched_difference'])} [{f(x['matched_ci'][0])}, {f(x['matched_ci'][1])}]", f(trimmed(x))))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print(len(L), "lines")


if __name__ == "__main__":
    main()
