"""The maze10 experiment, design probe (no network): reference policies on candidate settings of the larger maze.

    .venv/bin/python studies/7_information_seeking/maze10/design.py            # writes design.md

For each setting: discounted return and success of the oracle (knows the cell), QMDP (ignores the value of
information), QMDP with one step of lookahead, the most-likely-cell policy and uniformly random moves, on 20 000
episodes each; the mean posterior entropy over an episode under QMDP.
"""

from __future__ import annotations

import itertools, json
from pathlib import Path

import torch

from goalgeo import bigmaze as BM

HERE = Path(__file__).resolve().parent
N = 20000


def run(maze, dev="cuda"):
    t = BM.Sim(maze, dev)
    out = {}
    for name in ("oracle", "qmdp2", "qmdp", "mls", "random"):
        gen = torch.Generator(device=dev); gen.manual_seed(7)
        beh = BM.uniform(gen) if name == "random" else getattr(BM, name)
        b = BM.rollout(None, t, N, gen, behaviour=beh, record=name == "qmdp")
        out[name] = BM.summarize(b, t)[0]
        if name == "qmdp":
            e = BM.entropy(b.belief)
            out["entropy_start"], out["entropy_mean"] = float(e[:, 0].mean()), float(e[b.alive].mean())
            out["pmax_mean"] = float(b.belief.max(-1).values[b.alive].mean())
    out["dist_mean"] = float(t.dist[:, t.starts].mean()); out["dist_max"] = float(t.dist[:, t.starts].max())
    return out


def main():
    rows = {}
    m = BM.make(pairs=1, eps=0.4)                                         # the setting chosen for training
    L = ["# maze10: design probe", "", "Generated by `design.py`. The layout as trained on (seed 0, 6 loops, one symbol pair; 0 / 1: the two ordinary symbols, `*`: landmarks, letters: goals, `#`: walls), "
         f"{m.n} open cells:", "", "```", BM.draw(m), "```", "",
         "| noise | symbol pairs | landmarks | moves | oracle return (success) | QMDP + lookahead | QMDP | most likely cell | random | posterior entropy: start / mean under QMDP | most likely cell's probability |",
         "|---|---|---|---|---|---|---|---|---|---|---|"]
    for eps, pairs, land, H in itertools.product((0.2, 0.4), (1, 2), (1, 2), (40,)):
        r = run(BM.make(eps=eps, pairs=pairs, n_land=land, H=H))
        rows[f"eps{eps}_pairs{pairs}_land{land}_H{H}"] = r
        c = lambda k: f"{r[k]['ret']:.3f} ({r[k]['success']:.2f})"
        L.append(f"| {eps} | {pairs} | {land} | {H} | {c('oracle')} | {c('qmdp2')} | {c('qmdp')} | {c('mls')} | {c('random')} | {r['entropy_start']:.2f} / {r['entropy_mean']:.2f} | {r['pmax_mean']:.2f} |")
        print(L[-1], flush=True)
    L += ["", f"Path length to the goal from a random start: mean {r['dist_mean']:.1f}, longest {r['dist_max']:.0f}."]
    (HERE / "design.md").write_text("\n".join(L) + "\n")
    (HERE / "design.json").write_text(json.dumps(rows, indent=1))
    print("\n".join(L[:8]), "\n", L[-1])


if __name__ == "__main__":
    main()
