"""The maze10 experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/7_information_seeking/maze10/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
REFS = (("oracle", "oracle (knows the cell)"), ("qmdp2", "QMDP + lookahead"), ("qmdp", "QMDP"), ("mls", "most likely cell"), ("random", "random moves"))


def main():
    R = json.load(open(OUT / "results.json"))
    runs, ref = R["runs"], R["references"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(runs[s], p)) is None else x for s in seeds], dtype=float)
    const = lambda x: np.full(len(seeds), x)
    L = ["# The maze10 experiment tables", "",
         f"Generated by `studies/7_information_seeking/maze10/tables.py`. {len(seeds)} reward-trained models; {R['cells']} cells, task {R['task']}. "
         "8 192 evaluation episodes, the same spawns and goals for every policy. Median (range) over models.", "",
         "## A. Behaviour", ""]
    L += head("policy", "return", "success", "moves")
    L.append(row("**reward-trained models (greedy)**", mr(v("natural", "ret")), mr(v("natural", "success")), mr(v("natural", "length"), 1)))
    for k, kl in REFS:
        L.append(row(kl, f(ref[k]["ret"]), f(ref[k]["success"]), f(ref[k]["length"], 1)))
    L += ["", "## B. Information seeking", ""]
    L += head("policy", "deviates from QMDP", "information gain of its move − QMDP's, at deviations", "its move is the more informative", "QMDP value given up",
              "posterior entropy (mean; steps 0, 5, 10, 20, 30)", "episodes stepping on a landmark")
    ent = lambda d: f"{f(d['entropy_mean'], 2)}; " + ", ".join(f(x, 2) for x in d["entropy_by_step"])
    ents = lambda k: f"{mr(v(k, 'entropy_mean'), 2)}; " + ", ".join(f(np.median([runs[s][k]["entropy_by_step"][i] or np.nan for s in seeds]), 2) for i in range(5))
    L.append(row("**models**", mr(v("natural", "deviation_rate")), mr(v("natural", "ig_advantage"), 4), mr(v("natural", "more_informative")),
                 mr(v("natural", "qmdp_value_given_up"), 4), ents("natural"), mr(v("natural", "landmark_episodes"))))
    L.append(row("null: a random other move at the models' deviations", "", mr(v("natural", "ig_advantage_random_same_state"), 4), "", "", "", ""))
    L.append(row("null (registered): QMDP with random moves inserted", mr(v("noisy_qmdp", "deviation_rate")), mr(v("noisy_qmdp", "ig_advantage"), 4),
                 mr(v("noisy_qmdp", "more_informative")), mr(v("noisy_qmdp", "qmdp_value_given_up"), 4), ents("noisy_qmdp"), mr(v("noisy_qmdp", "landmark_episodes"))))
    for k, kl in REFS[:4]:
        d = ref[k]
        L.append(row(kl, f(d["deviation_rate"]), f(d["ig_advantage"], 4), f(d["more_informative"]), f(d["qmdp_value_given_up"], 4), ent(d), f(d["landmark_episodes"])))
    nat = v("natural", "ret")
    blind = v("online", "goal_blind", "ret")
    rec = (v("online", "additive", "ret") - blind) / (nat - blind)
    L += ["", "## C. The additive code as a policy", ""]
    L += head("", "value")
    for k, kl in (("goal_matters_share", "decisions where the model's move depends on the goal"), ("same_action_goal_matters", "there: argmax H + G is the model's move"),
                  ("same_action_goal_blind", "there: argmax H (no goal) is the model's move"), ("same_action_all", "all decisions: argmax H + G is the model's move"),
                  ("additive_share", "additive share of the logits' goal dependence")):
        L.append(row(kl, mr(v("additive_offline", k))))
    L += ["", "Run in the environment (return; success):", ""]
    L += head("policy", "return", "success")
    L.append(row("natural", mr(nat), mr(v("natural", "success"))))
    for k, kl in (("additive", "**additive: argmax H + G**"), ("goal_blind", "goal-blind: argmax H"), ("history_blind", "history-blind: argmax G")):
        L.append(row(kl, mr(v("online", k, "ret")), mr(v("online", k, "success"))))
    L.append(row("**recovery** (additive − goal-blind) / (natural − goal-blind)", mr(rec, 2), ""))
    rn, rb = v("removal", "natural", "ret"), v("removal", "goal_blind", "ret")
    recI = (v("removal", "noI", "ret") - rb) / (rn - rb)
    L += ["", "## D. Removals at the decision token, online (the first 4 096 evaluation episodes)", ""]
    L += head("at the decision token", "return", "success")
    for k, kl in (("natural", "nothing"), ("noI", "**interaction removed (history part + goal part)**"), ("noH", "history part removed, interaction kept"),
                  ("noG", "goal part removed, interaction kept"), ("goal_blind", "reference: goal-blind policy (argmax H)")):
        L.append(row(kl, mr(v("removal", k, "ret")), mr(v("removal", k, "success"))))
    L.append(row("**recovery** (interaction removed − goal-blind) / (natural − goal-blind)", mr(recI, 2), ""))
    L += ["", "## E. Decoders from the final state at decision tokens (held-out episodes)", ""]
    L += head("", "value")
    for k, kl in (("posterior_r2", "exact posterior, R²"), ("cell_accuracy_decoded", "true cell from the decoded posterior"), ("cell_accuracy_posterior", "true cell from the exact posterior"),
                  ("occupancy_r2_state", "occupancy R²: from the state"), ("occupancy_r2_posterior_goal_step", "occupancy R²: from the exact posterior × goal × step"),
                  ("occupancy_r2_state_goal_step", "occupancy R²: state + goal × step"), ("occupancy_r2_both", "occupancy R²: both")):
        L.append(row(kl, mr(v("decoders", k))))
    occ = v("decoders", "occupancy_r2_state") - v("decoders", "occupancy_r2_posterior_goal_step")
    yes = lambda b: "**yes**" if b else "no"
    pL, pS = p_gt(nat, const(ref["mls"]["ret"])), p_gt(nat, const(ref["qmdp"]["ret"]))
    iga, ign = v("natural", "ig_advantage"), v("noisy_qmdp", "ig_advantage")
    pB0, pB1 = p_gt(iga, const(0.0)), p_gt(iga, ign)
    pO = p_gt(occ, const(0.05))
    learn = np.median(nat) >= ref["mls"]["ret"]
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**LEARN**", "return ≥ the most-likely-cell policy's", f"{f(np.median(nat))} against {f(ref['mls']['ret'])}; p {fp(pL)}", yes(learn)))
    L.append(row("**SEEK-R**", "return > QMDP's", f"{f(np.median(nat))} against {f(ref['qmdp']['ret'])}; p {fp(pS)}", yes(np.median(nat) > ref["qmdp"]["ret"] and pS < 0.05)))
    L.append(row("**SEEK-B**", "information gain advantage at deviations > 0, and above the random-deviation null",
                 f"{f(np.median(iga), 4)} (p {fp(pB0)}); null {f(np.median(ign), 4)} (p {fp(pB1)})", yes(np.median(iga) > 0 and pB0 < 0.05 and pB1 < 0.05)))
    L.append(row("**AD-B**", "additive policy: recovery ≥ 0.9", f(np.median(rec), 2), yes(np.median(rec) >= 0.9)))
    L.append(row("**AD-S**", "interaction removed at the decision token: recovery ≥ 0.9", f(np.median(recI), 2), yes(np.median(recI) >= 0.9)))
    L.append(row("**OCC**", "occupancy R² from the state − from posterior × goal × step ≥ 0.05", f"{f(np.median(occ))}; p {fp(pO)}", yes(np.median(occ) >= 0.05 and pO < 0.05)))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
