"""Round 27: tables from results.json.

    .venv/bin/python rounds/r27_belief_encoding_edit/tables.py            # writes tables.md
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from scipy.stats import wilcoxon

OUT = Path(__file__).resolve().parent
CONDS = (("predict1", "predict1"), ("predict2", "predict2"), ("reward", "reward"), ("random", "random"))
KINDS = (("none", "none"), ("whole", "whole"), ("encoding", "**encoding**"), ("rotated", "rotated encoding"), ("random_patch", "random patch"),
         ("enc_patch", "encoding-subspace patch"), ("decoder_patch", "decoder patch"), ("pca_patch", "PCA patch"), ("onestep", "one-step encoding"))
f = lambda x, d=3: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
mr = lambda xs, d=3: f"{f(np.median(xs), d)} ({f(np.min(xs), d)}–{f(np.max(xs), d)})"
fp = lambda p: "< 0.001" if p < 0.001 else f"{p:.3f}"
gt = lambda a, b: float(wilcoxon(a, b, alternative="greater", method="exact").pvalue)


def main():
    res = json.load(open(OUT / "results.json"))
    R, C = res["runs"], res["counts"]
    seeds = lambda c: sorted(R[c], key=lambda s: int(s[4:]))
    v = lambda c, n, *path: np.array([_get(R[c][s][n], path) for s in seeds(c)])
    L = ["# Round 27 tables", "", "Generated by `rounds/r27_belief_encoding_edit/tables.py`. Ten backbones per condition, three frozen heads each (averaged); median (range) "
         "over backbones. p: exact one-sided Wilcoxon signed-rank test over the ten backbones. Cells: a pair under one goal. "
         f"Main pairs {C['main']['pairs']} (change cells {C['main']['change_cells']}, preserve cells {C['main']['preserve_cells']}); one-step agreeing pairs "
         f"{C['onestep']['pairs']} (change cells {C['onestep']['change_cells']}); shared-belief triples {C['shared']['triples']} (change cells {C['shared']['change_cells']}).", ""]
    for n, nl in (("100000", "heads trained on 100 000 examples (primary)"), ("1000", "heads trained on 1 000 examples")):
        L += [f"## {nl}", ""]
        for c, cl in CONDS:
            L += [f"### {cl}: main pairs", ""]
            L += head("edit", "change: donor-optimal", "change: as whole", "change: moved", "preserve: donor-optimal", "preserve: unchanged", "selective (pairs)", "regret at the donor's posterior, all cells")
            for k, kl in KINDS:
                g = lambda *p: v(c, n, "main", k, *p)
                L.append(row(kl, mr(g("change", "donor_optimal")), mr(g("change", "as_whole")), mr(g("change", "moved")), mr(g("preserve", "donor_optimal")),
                             mr(g("preserve", "unchanged")), mr(g("selective")), mr(g("all", "regret_donor"), 4)))
            w = lambda *p: v(c, n, "main", "wrong", *p)
            L += ["", f"Wrong posterior C (cells disjoint from both A and B): donor-optimal for C {mr(w('to_C', 'donor_optimal'))}, for B {mr(w('to_B', 'donor_optimal'))}.", ""]
            L += [f"### {cl}: one-step agreeing pairs (change cells) and shared-belief triples", ""]
            L += head("edit", "one-step agreeing: donor-optimal", "as whole", "moved", "shared: both donor-optimal", "shared: agreement of the two recipients", "shared: TV between them")
            for k, kl in KINDS:
                L.append(row(kl, mr(v(c, n, "onestep", k, "change", "donor_optimal")), mr(v(c, n, "onestep", k, "change", "as_whole")), mr(v(c, n, "onestep", k, "change", "moved")),
                             mr(v(c, n, "shared", k, "both_donor_optimal")), mr(v(c, n, "shared", k, "agree")), mr(v(c, n, "shared", k, "tv"))))
            L.append("")
        # the decision rule
        L += [f"### Decision rule ({nl})", ""]
        L += head("condition", "S1 encoding / whole (change)", "S2 encoding − none (preserve)", "S3 encoding vs rotated: p", "vs random patch: p", "rotated / encoding",
                  "S4 shared: encoding / whole", "S4 agreement − none's", "S5 one-step agreeing: encoding", "vs rotated: p")
        for c, cl in CONDS:
            enc, whole = v(c, n, "main", "encoding", "change", "donor_optimal"), v(c, n, "main", "whole", "change", "donor_optimal")
            rot, rp = v(c, n, "main", "rotated", "change", "donor_optimal"), v(c, n, "main", "random_patch", "change", "donor_optimal")
            pe, pn = v(c, n, "main", "encoding", "preserve", "donor_optimal"), v(c, n, "main", "none", "preserve", "donor_optimal")
            se, sw = v(c, n, "shared", "encoding", "both_donor_optimal"), v(c, n, "shared", "whole", "both_donor_optimal")
            ae, an = v(c, n, "shared", "encoding", "agree"), v(c, n, "shared", "none", "agree")
            oe, orot = v(c, n, "onestep", "encoding", "change", "donor_optimal"), v(c, n, "onestep", "rotated", "change", "donor_optimal")
            L.append(row(cl, f(np.median(enc) / np.median(whole)), f(np.median(pe) - np.median(pn)), fp(gt(enc, rot)), fp(gt(enc, rp)), f(np.median(rot) / np.median(enc)),
                         f(np.median(se) / np.median(sw)), f(np.median(ae) - np.median(an)), f(np.median(oe)), fp(gt(oe, orot))))
        L.append("")
    L += ["## The encoding and the edits (heads not involved)", ""]
    L += head("condition", "encoding R² (h from b)", "one-step encoding R²", "edit norm / actual difference", "cosine(edit, actual difference)", "residual share",
              "share of the difference in: encoding subspace", "decoder subspace", "PCA-13", "random-13", "one-step agreeing pairs: edit norm / difference")
    for c, cl in CONDS:
        e = lambda *p: v(c, "100000", "edit_stats", *p)
        L.append(row(cl, mr(np.array([R[c][s]["encoding_r2"] for s in seeds(c)])), mr(np.array([R[c][s]["onestep_encoding_r2"] for s in seeds(c)])),
                     mr(e("edit_norm_over_diff_norm")), mr(e("cosine_edit_diff")), mr(e("residual_share")), mr(e("share_enc")), mr(e("share_dec")), mr(e("share_pca")),
                     mr(e("share_random")), mr(v(c, "100000", "onestep_stats", "edit_norm_over_diff_norm"))))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


def _get(d, path):
    for p in path:
        d = d[p]
    return d


if __name__ == "__main__":
    main()
