"""Round 24: tables from results.json.

    .venv/bin/python rounds/r24_head_consistency/tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

OUT = Path("rounds/r24_head_consistency")
f = lambda x, d=3: f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
med = lambda v: f"{f(np.median(v))} ({f(min(v))}–{f(max(v))})"
ARMS = (("aux1", "c = 1"), ("aux01", "c = 0.1"))


def main():
    R = json.load(open(OUT / "results.json"))["runs"]
    L = ["# Round 24 tables", "", "Generated by `rounds/r24_head_consistency/tables.py`. Total variation over the three symbols (head) or the four moves (policy); "
         "median (range) over ten seeds. The greedy-move and other-moves rows are post hoc.", ""]
    where = (("goal token, all candidate moves (registered)", lambda x: x), ("goal token, the recipient's greedy move", lambda x: x["greedy_move"]), ("goal token, the other three moves", lambda x: x["other_moves"]),
             ("last prefix token, lengths 2–3", lambda x: x["prefix_token"]["lengths_2_3"]))
    for arm, name in ARMS:
        pol = [R[arm][s]["relative_inconsistency"]["policy"] for s in R[arm]]
        L += ["", f"## {name}", ""] + head("where the head is read", "D_same (type A)", "error against exact (type A)", "D_diff (type C)", "exact D (type C)", "relative inconsistency", "as a share of the policy's", "seeds with D_same ≤ error")
        for label, g in where:
            A = [g(R[arm][s]["A"]) for s in R[arm]]; C = [g(R[arm][s]["C"]) for s in R[arm]]
            rel = [a["d_head"] / c["d_head"] for a, c in zip(A, C)]
            L.append(row(label, med([a["d_head"] for a in A]), med([a["error"] for a in A]), med([c["d_head"] for c in C]), med([c["d_exact"] for c in C]), med(rel),
                         med([x / y for x, y in zip(rel, pol)]), f"{sum(a['d_head'] <= a['error'] for a in A)} of {len(A)}"))
        g = lambda ty, k: [R[arm][s][ty][k] for s in R[arm]]
        L += ["", f"Policy: TV between the two histories' action distributions {med(g('A', 'policy_tv'))} (type A), {med(g('C', 'policy_tv'))} (type C); relative inconsistency {med(pol)}. "
              f"Last prefix token at length 4 (no target in training): D_same {med([R[arm][s]['A']['prefix_token']['length_4_untrained']['d_head'] for s in R[arm]])}.", "",
              f"Type A cells where the greedy action differs between the two histories ({med(g('A', 'greedy_differs'))} of cells): D_same {med(g('A', 'd_head_where_greedy_differs'))}, "
              f"error {med(g('A', 'error_where_greedy_differs'))}; where it is the same: D_same {med(g('A', 'd_head_where_greedy_same'))}, error {med(g('A', 'error_where_greedy_same'))}.", ""]
        L += head("seed", "D_same", "error", "D_diff", "policy TV, type A", "relative: head", "relative: policy")
        for s in R[arm]:
            x = R[arm][s]
            L.append(row(s[4:], f(x["A"]["d_head"], 4), f(x["A"]["error"], 4), f(x["C"]["d_head"]), f(x["A"]["policy_tv"]), f(x["relative_inconsistency"]["head"]), f(x["relative_inconsistency"]["policy"])))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print(len(L), "lines")


if __name__ == "__main__":
    main()
