"""The reward-bandit experiment: tables and the registered decision rule, from results.json.

    .venv/bin/python studies/2_belief_state/reward_bandit/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parents[1] / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
ARCHS = (("tfm", "transformer"), ("gru", "GRU"))


def main():
    R = json.load(open(OUT / "results.json"))
    refs = R["references"]
    V = {}
    for arch, _ in ARCHS:
        keys = sorted(k for k in R["runs"] if k.startswith(arch + "/"))
        for which in ("trained", "untrained"):
            V[(arch, which)] = lambda *p, keys=keys, which=which: np.array([np.nan if (x := _get(R["runs"][k][which], p)) is None else x for k in keys], dtype=float)
        V[(arch, "n")] = len(keys)
    L = ["# The reward-bandit experiment tables", "",
         f"Generated by `studies/2_belief_state/reward_bandit/tables.py`. Six reward-trained models per architecture; {R['states']} belief states. "
         "16 384 fixed evaluation episodes (the same goals, cues and reward draws for every policy). Median (range) over models; the untrained rows are the "
         "initial checkpoints of the same seeds.", "", "## Behaviour", ""]
    L += head("policy", "return", "exact regret", "optimal actions", "where information pays: optimal action", "where information pays: myopic action")
    for arch, al in ARCHS:
        v = V[(arch, "trained")]
        L.append(row(f"**{al}, trained**", mr(v("behaviour", "ret")), mr(v("behaviour", "regret")), mr(v("behaviour", "opt_rate"), 2), mr(v("behaviour", "opt_where_pays"), 2), mr(v("behaviour", "myopic_where_pays"), 2)))
    for k, kl in (("optimal", "optimal (exact belief MDP)"), ("myopic", "myopic (ignores the value of information)"), ("constant", "evidence-blind: the best fixed action"), ("random", "random")):
        d = refs[k]
        L.append(row(kl, f(d["ret"]), f(d["regret"]), f(d["opt_rate"], 2), f(d["opt_where_pays"], 2), f(d["myopic_where_pays"], 2)))
    L += ["", "## Decodability of the posterior, by site", "",
          "Affine probes, unregularised. IID: 5-fold by episode. EXT: fit on decisions (after the first) with every log-odds below 2 nats, test on those with one at or above 3. "
          "y: the two log-odds; b: the three probabilities; V*, Q*: the solver's values. Within-action: y decoded within each optimal-action class.", ""]
    L += head("site", "IID R² y", "IID R² b", "EXT R² y", "EXT R² b", "R² V*", "R² Q*", "optimal action from the state", "within-action R² y")
    for arch, al in ARCHS:
        for which in ("trained", "untrained"):
            v = V[(arch, which)]
            sites_ = ["res0", "res1", "res2"] if arch == "tfm" else ["h"]
            for st in sites_:
                L.append(row(f"{al} {which}: {st}", *[mr(v("probes", st, k), 3) for k in ("IID_r2y", "IID_r2b", "EXT_r2y", "EXT_r2b", "IID_r2v", "IID_r2q", "action_acc", "r2y_within_action")]))
    L += ["", "## Does the policy act on the belief alone?", ""]
    L += head("", "transformer trained", "transformer untrained", "GRU trained", "GRU untrained")
    cols = [V[(a, w)] for a, _ in ARCHS for w in ("trained", "untrained")]
    for k, kl in (("equal_belief", "equal_js"), ("equal_belief", "random_js"), ("equal_belief", "js_ratio"), ("equal_belief", "equal_flip"), ("equal_belief", "random_flip"), ("node_table", "r2")):
        name = {"equal_js": "equal-belief pairs (permuted history): JS divergence of the action distribution", "random_js": "random pairs at the same step: JS divergence",
                "js_ratio": "**ratio** equal / random", "equal_flip": "equal-belief pairs: the greedy action changes", "random_flip": "random pairs: the greedy action differs",
                "r2": "**belief-node table**: share of the logits' variance explained by the belief state"}[kl]
        L.append(row(name, *[mr(v(k, kl), 3) for v in cols]))
    L += ["", "## Transplant along the probe at the state the heads read", "",
          "Pairs (A, B) of decisions at the same step. A's state is moved to B's decoded log-odds along the encoder (probe_e), along the decoder's pseudo-inverse (probe_d), "
          "or in a random direction of the same length. Gap closed: 1 − JS(edited, model on B) / JS(model on A, model on B).", ""]
    L += head("", "transformer trained", "transformer untrained", "GRU trained", "GRU untrained")
    for k, kl in (("probe_e_gap_closed", "**probe_e: gap closed**"), ("probe_d_gap_closed", "probe_d: gap closed"), ("rand_gap_closed", "random direction: gap closed"),
                  ("probe_e_same_action_as_B", "probe_e: the greedy action is the model's on B"), ("probe_e_opt_action_at_B", "probe_e: the greedy action is optimal at B"),
                  ("model_B_opt", "the model's own action on B is optimal"), ("opt_agree_A_on_B", "no edit: A's action is optimal at B"), ("probe_e_decoded_r2", "probe_e: decoded log-odds reach the target (R²)")):
        L.append(row(kl, *[mr(v("transplant", k), 3) for v in cols]))
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "transformer", "GRU")
    rows_ = []
    for arch, al in ARCHS:
        v, n = V[(arch, "trained")], V[(arch, "n")]
        const = lambda x: np.full(n, x)
        reg, retn = v("behaviour", "regret"), v("behaviour", "ret")
        blind = refs["constant"]["regret"]
        learn = np.median(reg) <= 0.25 * blind
        seek_p = p_gt(retn, const(refs["myopic"]["ret"]))
        seek = np.median(retn) > refs["myopic"]["ret"] and seek_p < 0.05
        final = "res2" if arch == "tfm" else "h"
        ext, ext_u = v("probes", final, "EXT_r2b"), V[(arch, "untrained")]("probes", final, "EXT_r2b")
        belief = np.median(ext) >= 0.9
        state = np.median(v("equal_belief", "js_ratio")) <= 0.1
        table = np.median(v("node_table", "r2")) >= 0.95
        steer = np.median(v("transplant", "probe_e_gap_closed")) >= 0.8 and np.median(v("transplant", "rand_gap_closed")) <= 0.2
        rows_.append([(f"{f(np.median(reg))} against {f(0.25 * blind)}", yes(learn)), (f"{f(np.median(retn))} against {f(refs['myopic']['ret'])}; p {fp(seek_p)}", yes(seek)),
                      (f"{f(np.median(ext), 2)} (untrained {f(np.median(ext_u), 2)})", yes(belief)), (f(np.median(v("equal_belief", "js_ratio")), 3), yes(state)),
                      (f(np.median(v("node_table", "r2")), 3), yes(table)), (f"{f(np.median(v('transplant', 'probe_e_gap_closed')), 2)} (random {f(np.median(v('transplant', 'rand_gap_closed')), 2)})", yes(steer))])
    names = [("**LEARN**", "regret ≤ a quarter of the evidence-blind policy's"), ("**SEEK**", "return > the myopic policy's"),
             ("**BELIEF**", "final site: EXT R² of b ≥ 0.9"), ("**STATE**", "equal-belief JS ratio ≤ 0.1"), ("**TABLE**", "belief-node table R² ≥ 0.95"),
             ("**STEER**", "probe_e gap closed ≥ 0.8, random ≤ 0.2")]
    for i, (nm, crit) in enumerate(names):
        L.append(row(nm, crit, *[f"{rows_[j][i][0]}: {rows_[j][i][1]}" for j in range(len(ARCHS))]))
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
