"""The residual-features experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/5_goal_belief_mechanism/residual_features/tables.py            # writes tables.md
"""

from __future__ import annotations

import collections, importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
GROUPS = ("absolute", "recency", "counts_group", "all")


def main():
    R = json.load(open(OUT / "results.json"))
    runs, names = R["runs"], R["features"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(runs[s], p)) is None else x for s in seeds], dtype=float)
    singles = [k for k in names if k not in GROUPS]
    det = [k for k in singles if all(runs[s]["features"][k].get("determined_by_posterior") for s in seeds)]
    L = ["# The residual-features experiment tables", "",
         "Generated by `studies/5_goal_belief_mechanism/residual_features/tables.py`. The observation-prediction experiment's ten reward models; informative pairs "
         f"{mr(v('pairs'), 0)} per model. Features centred within (posterior, L); x_F = ridge of r on the centred feature; swap against the same vector "
         "rotated. Share = the feature's excess flip / r's. Median (range).", "",
         f"r itself: swap {mr(v('r', 'swap'))}, rotated {mr(v('r', 'rot'))}, excess {mr(v('r', 'excess'))}.", "",
         f"Determined by the posterior (nothing left after centring): {', '.join(det) if det else 'none'}.", "",
         "## Groups", ""]
    L += head("group", "R² of r", "swap", "rotated", "excess", "share of r's excess")
    for k in GROUPS:
        L.append(row(k, mr(v("features", k, "r2")), mr(v("features", k, "swap")), mr(v("features", k, "rot")), mr(v("features", k, "excess")), mr(v("features", k, "share"), 2)))
    L += ["", "## Single features, by median share", ""]
    L += head("feature", "R² of r", "excess", "share of r's excess", "best in models")
    best = collections.Counter(max(singles, key=lambda k: runs[s]["features"][k]["share"] or 0) for s in seeds)
    for k in sorted(singles, key=lambda k: -np.median(v("features", k, "share"))):
        if k in det:
            continue
        L.append(row(k, mr(v("features", k, "r2")), mr(v("features", k, "excess")), mr(v("features", k, "share"), 2), best.get(k, 0)))
    allsh = np.median(v("features", "all", "share"))
    top = max(singles, key=lambda k: np.median(v("features", k, "share")))
    tsh = np.median(v("features", top, "share"))
    yes = lambda b: "**yes**" if b else "no"
    tok, loc = allsh >= 0.75, tsh >= 0.5 and best.get(top, 0) >= 7
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**TOK**", "the group 'all' carries ≥ 0.75 of r's excess", f(allsh, 2), yes(tok)))
    L.append(row("**LOC**", "best single feature ≥ 0.5, best in ≥ 7 of 10 models", f"{top}: {f(tsh, 2)}, best in {best.get(top, 0)}; best counts: {dict(best)}", yes(loc)))
    reading = ("r is mostly one superseded token feature" if tok and loc else "r is a distributed linear code of superseded token features" if tok
               else "r is not a linear code of these features")
    L += ["", f"**Registered reading: {reading}.**", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
