"""Round 18: tables, the scorecard of registered predictions and the figures, from the saved logs and measures.

    .venv/bin/python rounds/r18_maze_belief/tables.py
"""

from __future__ import annotations

import json, sys
from pathlib import Path

import numpy as np
from scipy.stats import spearmanr

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from goalgeo.style import COL, INK, MUTED, _style  # noqa: E402

OUT = Path("rounds/r18_maze_belief")
RUNS = OUT / "runs"
BLUE, ORANGE, GREEN, AMBER, GREY = COL["goal"], COL["act_soft"], COL["act_hard"], COL["next_obs"], COL["init"]


def load(group):
    out = {}
    for d in sorted((RUNS / group).glob("seed*")):
        r = dict(log=json.load(open(d / "log.json"))["log"])
        if (d / "measures.json").exists():
            r["m"] = json.load(open(d / "measures.json"))
        out[int(d.name[4:])] = r
    return out


f = lambda x, d=3: "—" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
cps = lambda r: sorted(int(u) for u in r["m"]["checkpoints"])
ck = lambda r, u: r["m"]["checkpoints"][str(u)]
best = lambda dec, k="r2": max(v[k] for v in dec.values())


def ms(v, d=3):
    v = [x for x in v if x is not None]
    return f"{np.mean(v):.{d}f} ± {np.std(v):.{d}f}" if v else "—"


def baselines():
    c = json.load(open(OUT / "checks.json"))
    rows = [r for g in c["goals"] for r in g["rows"]]
    return {k: float(np.mean([r["regret"][k] for r in rows])) for k in ("map", "qmdp", "open_loop")}, float(np.mean([r["v_opt"] for r in rows]))


def tables():
    P, FZ, SUP = load("ppo"), load("frozen"), load("supervised")
    base, vopt = baselines()
    L = ["# Round 18 tables", "", "Generated by `rounds/r18_maze_belief/tables.py`. ± is the standard deviation over seeds. Regret is in discounted "
         f"return; the optimal return averages {vopt:.3f}. Exact loss of the baselines, averaged over goals and prefix lengths: most likely cell "
         f"taken as certain {base['map']:.3f}; averaged fully observed values {base['qmdp']:.3f}; planning without future observations "
         f"{base['open_loop']:.3f}.", ""]
    S = []
    L += ["## 1. On-policy regret at the end of training", ""] + head("condition", "seed", "updates", "interactions", "greedy", "sampled", "G1", "G2", "G3", "success")
    for name, runs in (("ppo", P), ("frozen backbone", FZ), ("supervised", SUP)):
        for s, r in runs.items():
            e = r["log"][-1]
            L.append(row(name, s, e["update"], f"{e['interactions']:.2e}", f(e["greedy_regret"], 4), f(e["sampled_regret"], 4),
                         *[f(e[f"greedy_regret_G{g}"], 4) for g in (1, 2, 3)], f(e["greedy_success"])))
    L.append("")
    fin = [r["log"][-1]["greedy_regret"] for r in P.values()]
    S.append(("M1", "reward training: greedy regret ≤ 0.012 in ≥ 4 of 5 seeds", sum(v <= 0.012 for v in fin) >= 4,
              ", ".join(f(v, 4) for v in fin) + f"; averaging baseline {base['qmdp']:.4f}"))
    if SUP:
        S.append(("M2", "supervised ≤ 0.003", SUP[0]["log"][-1]["greedy_regret"] <= 0.003, f(SUP[0]["log"][-1]["greedy_regret"], 4)))
    if FZ:
        fz = [r["log"][-1]["greedy_regret"] for r in FZ.values()]
        S.append(("M3", "frozen backbone ≥ 0.05", min(fz) >= 0.05, ", ".join(f(v, 4) for v in fz)))
    L += ["### Greedy regret along training", ""] + head("update", *[f"seed {s}" for s in P])
    for i, e in enumerate(next(iter(P.values()))["log"]):
        L.append(row(e["update"], *[f(r["log"][i]["greedy_regret"], 4) for r in P.values()]))
    L.append("")

    M = {s: r for s, r in P.items() if "m" in r}
    if M:
        a = next(iter(M.values())); sites, us = a["m"]["sites"], cps(a)
        u0, u1 = us[0], us[-1]
        mean = lambda fn, u: float(np.mean([fn(ck(r, u)) for r in M.values()]))
        L += ["## 2. Held-out affine decoding of the exact posterior over the 14 cells (share of variance, mean of seeds)", ""]
        for title, key in (("At the reveal (goal token, prefix ≥ 2)", "decode_reveal"), ("At prefix tokens (goal not yet shown)", "decode_prefix"),
                           ("At the last prefix token", "decode_last_prefix"), ("At every decision token", "decode")):
            L += [f"### {title}", ""] + head("update", *sites)
            for u in us:
                L.append(row(u, *[f(mean(lambda m: m[key][n]["r2"], u)) for n in sites]))
            L.append("")
        L += ["### Other targets at decision tokens, final checkpoint (R², mean of seeds)", ""] + head("target", *sites)
        for k in ("p_left", "q_star", "advantage"):
            L.append(row(k, *[f(mean(lambda m: m["decode"][n][k], u1)) for n in sites]))
        L += ["", "Validity of the decoded posterior at the reveal, final checkpoint: share with a component outside [0, 1] "
              + f(mean(lambda m: m["decode_reveal"][sites[-1]]["invalid"], u1)) + ", mean L1 error "
              + f(mean(lambda m: m["decode_reveal"][sites[-1]]["l1"], u1)) + ".", ""]
        i0 = [best(ck(r, u0)["decode_reveal"]) for r in M.values()]; i1 = [best(ck(r, u1)["decode_reveal"]) for r in M.values()]
        d = np.mean(i1) - np.mean(i0)
        S.append(("M4", "posterior decodable at the reveal before training (≥ 0.5), more after (Δ in [0.05, 0.25])", min(i0) >= 0.5 and 0.05 <= d <= 0.25,
                  f"{ms(i0)} → {ms(i1)}"))
        p1 = [best(ck(r, u1)["decode_prefix"]) for r in M.values()]
        S.append(("M5", "prefix tokens hold the posterior (≥ 0.85)", min(p1) >= 0.85, f"{ms(p1)}; initial {ms([best(ck(r, u0)['decode_prefix']) for r in M.values()])}"))

        L += ["## 3. Along training, on the fixed histories (mean of seeds)", ""] + \
            head("update", "regret", "regret at the reveal", "G1", "G2", "G3", "posterior R² at the reveal (best site)", "TV under goal swap", "TV under evidence swap")
        for u in us:
            g = lambda fn: f(mean(fn, u))
            L.append(row(u, g(lambda m: m["policy"]["regret"]), g(lambda m: m["policy"]["regret_reveal"]),
                         *[g(lambda m, k=k: m["policy"][f"regret_reveal_G{k}"]) for k in (1, 2, 3)], g(lambda m: best(m["decode_reveal"])),
                         g(lambda m: m["swap"]["tv_goal"]), g(lambda m: m["swap"]["tv_evidence"])))
        L.append("")
        key = [u for u in us if "patches" in ck(a, u)]
        L += ["### Use of the evidence and patches along training (mean of seeds; held-out pairs)", ""] + \
            head("update", "use", "L0 attention, same goal: to hybrid", "L0 other heads, cross goal: to hybrid", "to donor", "prefix tokens at resid1, same goal: to hybrid",
                 "pairs (same / cross)")
        for u in key:
            pm = lambda fn: f(np.mean([x for x in [fn(ck(r, u)["patches"]) for r in M.values()] if x is not None] or [np.nan]), 2)
            og = lambda p, k: (p.get("L0.other_heads") or {}).get(k)
            L.append(row(u, pm(lambda p: p["model"]["use"]), pm(lambda p: p["L0.attn"]["same_to_hybrid"]), pm(lambda p: og(p, "cross_to_hybrid")),
                         pm(lambda p: og(p, "cross_to_donor")), pm(lambda p: p["prefix@resid1"]["same_to_hybrid"]),
                         f"{np.mean([ck(r, u)['patches']['n_same'] for r in M.values()]):.0f} / {np.mean([ck(r, u)['patches']['n_cross'] for r in M.values()]):.0f}"))
        L.append("")
        rho = []
        for r in M.values():
            ks = [u for u in cps(r) if "patches" in ck(r, u)]
            rho.append(spearmanr([ck(r, u)["patches"]["model"]["use"] for u in ks], [ck(r, u)["policy"]["regret_reveal"] for u in ks])[0])
        S.append(("M11", "use tracks regret at the reveal (ρ ≤ −0.8)", max(rho) <= -0.8, ", ".join(f(x, 2) for x in rho) + f" ({len(key)} checkpoints)"))
        first = lambda r, g: next((u for u in cps(r) if ck(r, u)["policy"][f"regret_reveal_G{g}"] < 0.01), 10 ** 9)
        fs = [[first(r, g) for g in (1, 2, 3)] for r in M.values()]
        S.append(("M12", "G3 is learned no later than G1 and G2", sum(x[2] <= min(x[0], x[1]) for x in fs) >= 4, "; ".join("/".join(str(v) if v < 10 ** 9 else "never" for v in x) for x in fs) + " (G1/G2/G3)"))

        P1 = lambda r: ck(r, u1)["patches"]
        comps = [k for k, v in P1(a).items() if isinstance(v, dict) and "same_to_hybrid" in v]
        L += ["## 4. Patches at the reveal, final checkpoint, held-out pairs (mean ± sd over seeds)", "",
              "Same goal: donor = the recipient's goal with other evidence. Cross goal: other evidence and another goal; hybrid = donor's evidence with the "
              "recipient's goal; swapped = recipient's evidence with the donor's goal. belief = decoded posterior's displacement along the exact one.", ""] + \
            head("patch", "same goal: to hybrid", "cross: to hybrid", "cross: to donor", "cross: to swapped", "belief", "solver's set")
        for c in comps:
            x = lambda k: ms([(P1(r).get(c) or {}).get(k) for r in M.values()], 2)
            L.append(row(c, x("same_to_hybrid"), x("cross_to_hybrid"), x("cross_to_donor"), x("cross_to_swapped"), x("belief"), x("solver")))
        L += ["", "Head groups chosen on the fitting histories: " + "; ".join(f"seed {s}: goal heads {ck(r, u1)['groups']['L0.goal_heads']}" for s, r in M.items()),
              "", "Pairs: " + "; ".join(f"seed {s}: {P1(r)['n_same']} same-goal, {P1(r)['n_cross']} cross-goal" for s, r in M.items()), ""]
        m6 = [P1(r)["prefix@resid1"]["same_to_hybrid"] for r in M.values()]
        S.append(("M6", "the decision does not read the posterior held at prefix tokens (≤ 0.35)", max(m6) <= 0.35, ms(m6, 2)))
        ok7 = []
        for r in M.values():
            g = ck(r, u1)["groups"]["L0.goal_heads"]; o = P1(r).get("L0.other_heads") or {}
            ok7.append(1 <= len(g) <= 2 and (o.get("cross_to_hybrid") or 0) >= 0.4 and (o.get("cross_to_donor") or 1) <= 0.25)
        S.append(("M7", "evidence heads carry the evidence across goals (to hybrid ≥ 0.4, to donor ≤ 0.25; 1–2 goal heads) in ≥ 4 of 5 seeds", sum(ok7) >= 4,
                  "; ".join(f"{len(ck(r, u1)['groups']['L0.goal_heads'])} goal heads, {f((P1(r).get('L0.other_heads') or {}).get('cross_to_hybrid'), 2)} / "
                            f"{f((P1(r).get('L0.other_heads') or {}).get('cross_to_donor'), 2)}" for r in M.values())))
        a8 = [(P1(r)["L0.attn"]["cross_to_hybrid"], P1(r)["L0.attn"]["cross_to_donor"]) for r in M.values()]
        S.append(("M8", "whole L0 attention is entangled (to hybrid ≤ 0.2, to donor ≥ 0.7)", all(x <= 0.2 and y >= 0.7 for x, y in a8),
                  f"{ms([x for x, _ in a8], 2)} / {ms([y for _, y in a8], 2)}"))

        L += ["## 5. The same history with another goal (final checkpoint, mean ± sd over seeds)", ""] + head("site", "decoded posterior moves (L1): goal swap", "evidence swap", "ratio")
        sw = lambda r: ck(r, u1)["swap"]
        ratios = []
        for k in [k for k in sw(a) if k.startswith("resid")]:
            g_, e_ = [sw(r)[k]["goal"] for r in M.values()], [sw(r)[k]["evidence"] for r in M.values()]
            if k != "resid0":
                ratios += [x / y for x, y in zip(g_, e_)]
            L.append(row(k, ms(g_), ms(e_), f(np.mean(g_) / max(np.mean(e_), 1e-9), 2)))
        tvg = [sw(r)["tv_goal"] for r in M.values()]
        L += ["", f"Action distribution: TV under goal swap {ms(tvg, 2)}, under evidence swap {ms([sw(r)['tv_evidence'] for r in M.values()], 2)}. "
              "(resid0 is the goal token's embedding: it holds no evidence.)", ""]
        S.append(("M9", "goal swap: decoded posterior moves ≤ 0.35 × the evidence swap's, actions change (TV ≥ 0.15)", max(ratios) <= 0.35 and min(tvg) >= 0.15,
                  f"max ratio {max(ratios):.2f}; TV {ms(tvg, 2)}"))
        L += ["## 6. Decoders across goals (at the reveal, final checkpoint, mean over seeds and held-out goals)", ""] + head("site", "own goal", "fitted without the goal", "same, goal means removed")
        tr = lambda r, n, k: float(np.mean([ck(r, u1)["transfer"][n][g][k] for g in ("G1", "G2", "G3")]))
        for n in sites:
            L.append(row(n, *[f(np.mean([tr(r, n, k) for r in M.values()]), 2) for k in ("own", "raw", "centred")]))
        L.append("")
        c_, o_ = [tr(r, sites[-1], "centred") for r in M.values()], [tr(r, sites[-1], "own") for r in M.values()]
        S.append(("M10", "posterior code shared across goals in part (held-out goal, centred: ≥ 0.25 and ≥ 0.15 below own)",
                  np.mean(c_) >= 0.25 and np.mean(o_) - np.mean(c_) >= 0.15, f"centred {ms(c_, 2)}; own {ms(o_, 2)}"))
        ctl = {**{f"frozen {s}": r for s, r in FZ.items()}, **{f"supervised {s}": r for s, r in SUP.items()}}
        ctl = {k: r for k, r in ctl.items() if "m" in r}
        if ctl:
            L += ["## 7. Controls, final checkpoint", ""] + head("model", "bank regret at the reveal", "posterior R² at the reveal", "at prefix tokens", "use",
                                                                "L0 attention, same goal: to hybrid", "L0 other heads, cross: to hybrid / to donor", "goal heads")
            for k, r in ctl.items():
                m = ck(r, cps(r)[-1]); p = m["patches"]; o = p.get("L0.other_heads") or {}
                L.append(row(k, f(m["policy"]["regret_reveal"], 4), f(best(m["decode_reveal"])), f(best(m["decode_prefix"])), f(p["model"]["use"], 2),
                             f(p["L0.attn"]["same_to_hybrid"], 2), f"{f(o.get('cross_to_hybrid'), 2)} / {f(o.get('cross_to_donor'), 2)}", m["groups"]["L0.goal_heads"]))
            L.append("")
    S.sort(key=lambda s: int(s[0][1:]))
    L += ["## Scorecard", ""] + head("", "prediction", "held", "numbers") + [row(a_, b_, "**yes**" if c_ else "no", d_) for a_, b_, c_, d_ in S]
    L += ["", f"{sum(bool(s[2]) for s in S)} of {len(S)} held."]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[-len(S) - 6:]))
    return P, FZ, SUP, base


def figures(P, FZ, SUP, base):
    M = {s: r for s, r in P.items() if "m" in r}
    fig, ax = plt.subplots(1, 2, figsize=(10, 3.6))
    for runs, col, lab in ((P, BLUE, "reward (PPO), 5 seeds"), (FZ, GREY, "frozen backbone"), (SUP, ORANGE, "solver-supervised")):
        for i, r in enumerate(runs.values()):
            ax[0].plot([max(e["update"], 1) for e in r["log"]], [e["greedy_regret"] for e in r["log"]], color=col, lw=1.2, alpha=0.8, label=lab if i == 0 else None)
    for k, name in (("map", "most likely cell as certain"), ("qmdp", "averaged fully observed values")):
        ax[0].axhline(base[k], color=MUTED, lw=0.8, ls=":"); ax[0].text(1.2, base[k] * 1.08, name, fontsize=7, color=MUTED)
    ax[0].set_yscale("log"); ax[0].set_title("Greedy regret", fontsize=9, color=INK, loc="left"); ax[0].legend(fontsize=7, frameon=False)
    if P:
        logs = [r["log"] for r in P.values()]
        for g, col in ((1, BLUE), (2, ORANGE), (3, GREEN)):
            ax[1].plot([max(e["update"], 1) for e in logs[0]], np.mean([[e[f"greedy_regret_G{g}"] for e in l] for l in logs], 0), color=col, lw=2,
                       label=f"G{g}" + (" (direction does not depend on the belief)" if g == 3 else ""))
        ax[1].set_title("Greedy regret by goal (mean of seeds)", fontsize=9, color=INK, loc="left"); ax[1].legend(fontsize=7, frameon=False)
    for a in ax:
        a.set_xscale("log"); a.set_xlabel("updates", fontsize=8); _style(a)
    fig.tight_layout(); fig.savefig(OUT / "fig1_learning.png", dpi=160); plt.close(fig)
    if not M:
        return
    a = next(iter(M.values())); sites, us = a["m"]["sites"], cps(a)
    fig, ax = plt.subplots(1, 2, figsize=(12, 4.8))
    for x, key, title in ((ax[0], "decode_reveal", "Posterior at the reveal: held-out affine R²"), (ax[1], "decode_prefix", "Posterior at prefix tokens: held-out affine R²")):
        Z = np.array([[np.mean([ck(r, u)[key][n]["r2"] for r in M.values()]) for n in sites] for u in us])
        im = x.imshow(Z, aspect="auto", cmap="Blues", vmin=0, vmax=1)
        x.set_xticks(range(len(sites))); x.set_xticklabels(sites, fontsize=7, rotation=45, ha="right")
        x.set_yticks(range(len(us))); x.set_yticklabels(us, fontsize=6); x.set_ylabel("updates", fontsize=8)
        x.set_title(title, fontsize=9, color=INK, loc="left")
        for i in range(len(us)):
            for j in range(len(sites)):
                x.text(j, i, f"{Z[i, j]:.2f}", ha="center", va="center", fontsize=5, color="white" if Z[i, j] > 0.55 else INK)
        fig.colorbar(im, ax=x, fraction=0.03)
    fig.tight_layout(); fig.savefig(OUT / "fig2_layers.png", dpi=160); plt.close(fig)
    panels = (("Regret at the reveal, fixed histories", lambda m: m["policy"]["regret_reveal"]),
              ("Posterior R² at the reveal (best site)", lambda m: best(m["decode_reveal"])),
              ("Action change under evidence swap (TV)", lambda m: m["swap"]["tv_evidence"]),
              ("Action change under goal swap (TV)", lambda m: m["swap"]["tv_goal"]))
    fig, ax = plt.subplots(1, 4, figsize=(14, 3.2))
    for x, (title, fn) in zip(ax, panels):
        for r in M.values():
            x.plot([max(u, 1) for u in us], [fn(ck(r, u)) for u in us], color=BLUE, lw=0.9, alpha=0.5)
        x.plot([max(u, 1) for u in us], np.mean([[fn(ck(r, u)) for u in us] for r in M.values()], 0), color=INK, lw=1.8)
        x.set_xscale("log"); x.set_title(title, fontsize=9, color=INK, loc="left"); x.set_xlabel("updates", fontsize=8); _style(x)
    fig.tight_layout(); fig.savefig(OUT / "fig3_timeline.png", dpi=160); plt.close(fig)
    u1 = us[-1]
    P1 = lambda r: ck(r, u1)["patches"]
    comps = ["L0.goal_heads", "L0.other_heads", "L0.attn", "L0.mlp", "L1.attn", "L1.mlp", "L2.attn", "L2.mlp", "L3.attn", "L3.mlp", "resid4",
             "last@resid0", "prefix@resid1", "prefix@resid2", "prefix@resid3"]
    val = lambda c, k: np.mean([x for x in [(P1(r).get(c) or {}).get(k) for r in M.values()] if x is not None] or [0])
    fig, ax = plt.subplots(figsize=(12, 3.8))
    xs = np.arange(len(comps))
    for i, (k, col, lab) in enumerate((("cross_to_hybrid", BLUE, "to: donor's evidence, own goal"), ("cross_to_donor", ORANGE, "to: the donor's behaviour"),
                                       ("cross_to_swapped", GREEN, "to: own evidence, donor's goal"))):
        ax.bar(xs + (i - 1) * 0.27, [val(c, k) for c in comps], 0.25, color=col, label=lab)
    ax.set_xticks(xs); ax.set_xticklabels(comps, fontsize=7, rotation=40, ha="right"); ax.axhline(0, color=MUTED, lw=0.6)
    ax.set_title("Patch from a donor with other evidence and another goal: where the action distribution moves", fontsize=9, color=INK, loc="left")
    ax.legend(fontsize=7, frameon=False, ncol=3); _style(ax)
    fig.tight_layout(); fig.savefig(OUT / "fig4_patches.png", dpi=160); plt.close(fig)


if __name__ == "__main__":
    figures(*tables())
