"""The additive-ablation experiment: tables and the registered decision rule from results.json; the post hoc recomputed
ablations from explore.json.

    .venv/bin/python studies/5_goal_belief_mechanism/additive_ablation/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
KINDS = (("natural", "nothing"), ("F_additive", "fixed: xbar(h) + M(g) (all_hist)"), ("F_hist_mean", "fixed: Xbar(L) + M(g) (history-blind by construction)"),
         ("F_goal_mean", "fixed: xbar(h) (goal-blind by construction)"), ("live_noH", "**live: −(xbar(h) − Xbar(L)), all 8**"),
         ("live_noH_attn", "live: the same, four attention outputs"), ("live_noI", "live: −I(h, g), all 8"), ("live_noH_rot", "live: rotated history part (control)"),
         ("live_swapH", "live: xbar(h′) − xbar(h), all 8"), ("live_noG", "live: −M(g), all 8"), ("live_swapG", "live: M(g′) − M(g), all 8"))
XKINDS = (("natural", "nothing"), ("rec_noH", "**history part removed, recomputed at every component**"), ("rec_noHI", "history part and interaction removed (history-blind by construction)"),
          ("rec_noI", "interaction removed, recomputed"), ("rec_noG", "goal part removed, recomputed"), ("attn_noI", "interaction removed, four attention outputs (natural vectors)"),
          ("attn_swapH", "history part swapped, four attention outputs"), ("attn0_noG", "goal part removed, block 0's attention only"),
          ("attn0_swapG", "goal part swapped, block 0's attention only"))


def main():
    R = json.load(open(OUT / "results.json"))
    runs, ceil = R["runs"], R["ceiling"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    opt = lambda k, c="all": v("optimal", k, c)
    hd = lambda k: v("history_dependence", k)
    c = R["cells"]
    L = ["# The additive-ablation experiment tables", "",
         "Generated by `studies/5_goal_belief_mechanism/additive_ablation/tables.py`. The observation-prediction experiment's ten reward models; the goal "
         f"token's eight component outputs. Cells: goal-matters {c['goal_matters']}, goal-neutral {c['goal_neutral']}. Median (range).", "",
         f"History-blind ceiling B (best action per goal and prefix length, from fit-side histories): all cells {f(ceil['all'])}, "
         f"goal-matters {f(ceil['goal_matters'])}, goal-neutral {f(ceil['goal_neutral'])}.", "",
         "## Registered kinds (PLAN.md)", ""]
    L += head("edit at the goal token", "optimal, all cells", "goal-matters", "goal-neutral", "history dependence", "agrees with B")
    for k, kl in KINDS:
        L.append(row(kl, mr(opt(k)), mr(opt(k, "goal_matters")), mr(opt(k, "goal_neutral")), mr(hd(k)), mr(v("agree_ceiling", k))))
    L += ["", "Swaps and goal dependence:", ""]
    L += head("", "value")
    L.append(row("live_swapH: follow the donor (pairs with different natural actions)", mr(v("swapH", "follow"))))
    L.append(row("live_swapH: stay", mr(v("swapH", "stay"))))
    L.append(row("goal dependence, natural (goal-matters)", mr(v("goal", "dependence_natural"))))
    L.append(row("goal dependence, live_noG", mr(v("goal", "dependence_noG"))))
    L.append(row("live_swapG: follow g′", mr(v("goal", "swapG_follow"))))
    cf = lambda k: (opt("natural") - opt(k)) / (opt("natural") - ceil["all"])
    dH, dI = opt("natural") - opt("live_noH"), opt("natural") - opt("live_noI")
    yes = lambda b: "**yes**" if b else "no"
    pHC = p_gt(cf("live_noH"), cf("live_noH_rot"))
    pSW = p_gt(v("swapH", "follow"), v("swapH", "stay"))
    gc_ratio = np.median(v("goal", "dependence_noG") / v("goal", "dependence_natural"))
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**HC**", "live_noH collapse fraction ≥ 0.8, above live_noH_rot",
                 f"{f(np.median(cf('live_noH')), 2)} against {f(np.median(cf('live_noH_rot')), 2)}; p {fp(pHC)}; history dependence {f(np.median(hd('live_noH')))} (natural {f(np.median(hd('natural')))})",
                 yes(np.median(cf("live_noH")) >= 0.8 and pHC < 0.05) + " (by the letter; see report)"))
    L.append(row("**ID**", "natural − live_noI ≤ 0.2 × (natural − live_noH)", f"{f(np.median(dI))} against {f(np.median(dH))} (ratio {f(np.median(dI / dH), 2)})",
                 yes(np.median(dI / dH) <= 0.2)))
    L.append(row("**SW**", "live_swapH follow ≥ 0.75, above stay", f"{f(np.median(v('swapH', 'follow')))} against {f(np.median(v('swapH', 'stay')))}; p {fp(pSW)}",
                 yes(np.median(v("swapH", "follow")) >= 0.75 and pSW < 0.05)))
    L.append(row("**GC**", "live_noG goal dependence ≤ 0.25 × natural's, and live_swapG follow ≥ 0.75",
                 f"{f(gc_ratio, 2)} ×; follow {f(np.median(v('goal', 'swapG_follow')))}", yes(gc_ratio <= 0.25 and np.median(v("goal", "swapG_follow")) >= 0.75)))
    # post hoc
    X = json.load(open(OUT / "explore.json"))["runs"]
    xv = lambda *p: np.array([_get(X[s], p) for s in seeds], dtype=float)
    L += ["", "## Post hoc: ablations recomputed under upstream edits (`explore.py`, not registered)", ""]
    L += head("edit at the goal token", "optimal, all cells", "goal-matters", "goal-neutral", "history dependence", "agrees with B")
    for k, kl in XKINDS:
        L.append(row(kl, mr(xv("optimal", k, "all")), mr(xv("optimal", k, "goal_matters")), mr(xv("optimal", k, "goal_neutral")),
                     mr(xv("history_dependence", k)), mr(xv("agree_ceiling", k))))
    L += ["", "Swaps and goal dependence:", ""]
    L += head("", "value")
    L.append(row("attn_swapH: follow the donor", mr(xv("attn_swapH", "follow"))))
    L.append(row("attn_swapH: stay", mr(xv("attn_swapH", "stay"))))
    L.append(row("goal dependence, natural", mr(xv("goal", "dependence_natural"))))
    L.append(row("goal dependence, rec_noG", mr(xv("goal", "dependence_rec_noG"))))
    L.append(row("goal dependence, attn0_noG", mr(xv("goal", "dependence_attn0_noG"))))
    L.append(row("attn0_swapG: follow g′", mr(xv("goal", "attn0_swapG_follow"))))
    gap = xv("optimal", "rec_noH", "all") - xv("optimal", "rec_noHI", "all")
    L += ["", f"rec_noH − rec_noHI (what the interaction alone recovers of the history's use), all cells: {mr(gap)}; "
          f"as a share of natural − rec_noHI: {mr(gap / (xv('optimal', 'natural', 'all') - xv('optimal', 'rec_noHI', 'all')), 2)}.",
          f"rec_noI drop from natural, all cells: {mr(xv('optimal', 'natural', 'all') - xv('optimal', 'rec_noI', 'all'))}; "
          f"rec_noH drop: {mr(xv('optimal', 'natural', 'all') - xv('optimal', 'rec_noH', 'all'))}.", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
