"""Round 17: tables, the scorecard of registered predictions and the figures, from the saved logs and measures.

    .venv/bin/python rounds/r17_navigate_commit/tables.py
"""

from __future__ import annotations

import json, sys
from pathlib import Path

import numpy as np
from scipy.stats import spearmanr

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from goalgeo.style import COL, INK, MUTED, _style  # noqa: E402

OUT = Path("rounds/r17_navigate_commit")
RUNS = OUT / "runs"
BLUE, ORANGE, GREEN, AMBER, GREY = COL["goal"], COL["act_soft"], COL["act_hard"], COL["next_obs"], COL["init"]


def load(group):
    out = {}
    for d in sorted((RUNS / group).glob("seed*")):
        r = dict(log=json.load(open(d / "log.json"))["log"])
        for k in ("measures", "qgen"):
            if (d / f"{k}.json").exists():
                r[k] = json.load(open(d / f"{k}.json"))
        out[int(d.name[4:])] = r
    return out


def f(x, d=3):
    return "—" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.{d}f}"


def row(*c):
    return "| " + " | ".join(str(x) for x in c) + " |"


def head(*c):
    return [row(*c), "|" + "---|" * len(c)]


def cps(r):
    return sorted(int(u) for u in r["measures"]["checkpoints"])


def ck(r, u):
    return r["measures"]["checkpoints"][str(u)]


def marg(site_scores):
    return (site_scores["r2"][4] + site_scores["r2"][5]) / 2


def best_marg(m, key="trained"):
    return max(marg(s) for s in m["probes"][key].values())


def per_seed(runs, fn):
    return [fn(r) for r in runs.values()]


def ms(v, d=3):
    v = [x for x in v if x is not None]
    return f"{np.mean(v):.{d}f} ± {np.std(v):.{d}f}" if v else "—"


def tables():
    P, FZ, SUP, G, SG = load("ppo_fixed"), load("frozen_fixed"), load("sup_fixed"), load("ppo_grid"), load("sup_grid")
    L = ["# Round 17 tables", "", "Generated by `rounds/r17_navigate_commit/tables.py`. ± is the standard deviation over seeds. "
         "Regret is in units of expected return (never querying costs 0.101; the optimal return is 0.311).", ""]
    S = []                                                                    # scorecard rows

    # ---- 1 learning
    L += ["## 1. On-policy regret", ""] + head("condition", "seed", "updates", "interactions", "greedy regret", "sampled regret",
                                               "queries / episode", "query", "commit", "route")
    for name, runs in (("ppo, fixed q", P), ("frozen backbone", FZ), ("supervised, fixed q", SUP), ("ppo, grid q", G), ("supervised, grid q", SG)):
        for s, r in runs.items():
            e = r["log"][-1]
            L.append(row(name, s, e["update"], f"{e['interactions']:.2e}", f(e["greedy_regret"], 4), f(e["sampled_regret"], 4),
                         f(e["greedy_queries"], 2), f(e["greedy_err_query"], 4), f(e["greedy_err_commit"], 4), f(e["greedy_err_route"], 4)))
    L += ["", "Query / commit / route: the greedy regret split by the kind of decision that lost it.", ""]
    fin = {s: r["log"][-1]["greedy_regret"] for s, r in P.items()}
    if P:
        S.append(("N1", "reward training: greedy regret ≤ 0.02 in ≥ 4 of 5 seeds", sum(v <= 0.02 for v in fin.values()) >= 4,
                  ", ".join(f(v, 4) for v in fin.values())))
    if SUP and P:
        sv = SUP[0]["log"][-1]["greedy_regret"]
        S.append(("N2", "supervised ≤ 0.005 and below every PPO seed", sv <= 0.005 and sv < min(fin.values()), f(sv, 4)))
    if FZ and all("measures" in r for r in FZ.values()):
        fr = [(r["log"][-1]["greedy_regret"], ck(r, cps(r)[-1])["use"]["eval"]["use"]) for r in FZ.values()]
        S.append(("N3", "frozen backbone: regret ≥ 0.05 and use ≤ 0.2", all(a >= 0.05 and b <= 0.2 for a, b in fr),
                  "; ".join(f"regret {f(a, 4)}, use {f(b)}" for a, b in fr)))

    L += ["### Regret along training (greedy; every seed)", ""] + head("update", *[f"seed {s}" for s in P], "mean queries")
    if P:
        for i, e in enumerate(next(iter(P.values()))["log"]):
            L.append(row(e["update"], *[f(r["log"][i]["greedy_regret"], 4) for r in P.values()],
                         f(np.mean([r["log"][i]["greedy_queries"] for r in P.values()]), 2)))
    L.append("")

    M = {s: r for s, r in P.items() if "measures" in r}
    if M:
        any_r = next(iter(M.values()))
        sites, us = any_r["measures"]["sites"], cps(any_r)
        first, last = us[0], us[-1]
        # ---- 2 decoding
        L += ["## 2. Held-out affine decoding of the belief on fixed histories", "",
              f"Raw-input baseline (own token and station records, one-hot): marginals R² {f(marg(any_r['measures']['raw_baseline']['trained']))}, "
              f"goal probabilities L1 error {f(any_r['measures']['raw_baseline']['trained']['belief_l1'])}.", ""]
        for title, fn in (("Marginals P(right), P(bottom): mean R²", marg), ("Product term: R²", lambda s: s["r2"][6]),
                          ("Four goal probabilities: mean R²", lambda s: float(np.mean(s["r2"][:4]))),
                          ("Decoded goal probabilities outside [0, 1] (share of decisions)", lambda s: s["invalid"])):
            L += [f"### {title} (mean over seeds)", ""] + head("update", *sites)
            for u in us:
                L.append(row(u, *[f(np.mean([fn(ck(r, u)["probes"]["trained"][n]) for r in M.values()])) for n in sites]))
            L.append("")
        L += ["### Per seed, best site", ""] + head("seed", "marginals, init", "marginals, final", "product, final (max over sites)",
                                                   "two-clue decisions: marginals, final", "64-unit decoder: marginals, final", "64-unit: product, final")
        for s, r in M.items():
            a, b = ck(r, first), ck(r, last)
            L.append(row(s, f(best_marg(a)), f(best_marg(b)), f(max(x["r2"][6] for x in b["probes"]["trained"].values())),
                         f(best_marg(b, "trained_two_clues")), f(best_marg(b, "adam_mlp")) if "adam_mlp" in b["probes"] else "—",
                         f(max(x["r2"][6] for x in b["probes"]["adam_mlp"].values())) if "adam_mlp" in b["probes"] else "—"))
        L += ["", "Budget-matched decoders (Adam, 400 steps, 60 000 decisions), final checkpoint, mean over seeds:", ""] + head("decoder", *sites)
        for key in ("adam_affine", "adam_mlp"):
            L.append(row(key, *[f(np.mean([marg(ck(r, last)["probes"][key][n]) for r in M.values()])) for n in sites]))
        L.append("")
        i0 = per_seed(M, lambda r: best_marg(ck(r, first))); i1 = per_seed(M, lambda r: best_marg(ck(r, last)))
        raw = marg(any_r["measures"]["raw_baseline"]["trained"])
        S.append(("N4", "marginals decodable at initialisation (best site R² ≥ 0.6; raw ≤ 0.05)", min(i0) >= 0.6 and raw <= 0.05,
                  f"init {ms(i0)}; raw {f(raw)}"))
        d = np.mean(i1) - np.mean(i0)
        S.append(("N5", "training does not change affine decodability (Δ in ±0.15; final < 0.9)", abs(d) <= 0.15 and max(i1) < 0.9,
                  f"Δ {d:+.3f}; final {ms(i1)}"))
        pr = per_seed(M, lambda r: max(x["r2"][6] for x in ck(r, last)["probes"]["trained"].values()))
        S.append(("N6", "product term R² < 0.4 at every site", max(pr) < 0.4, f"max over sites: {ms(pr)}"))

        # ---- 3 timeline
        L += ["## 3. Use, decodability and regret on the same fixed histories", ""] + \
            head("update", "bank regret", "bank regret, ≥ 1 clue", "use", "TV between twins", "best-site marginal R²", "L0.attn twin difference / norm",
                 "L0.attn decoded write")
        clue = lambda m: (m["policy"]["regret_1clue"] + m["policy"]["regret_2clue"]) / 2
        for u in us:
            g = lambda fn: f(np.mean([fn(ck(r, u)) for r in M.values()]))
            L.append(row(u, g(lambda m: m["policy"]["regret"]), g(clue), g(lambda m: m["use"]["eval"]["use"]), g(lambda m: m["use"]["eval"]["tv"]),
                         g(best_marg), g(lambda m: m["writes"]["L0.attn"]["rel_norm"]), g(lambda m: m["writes"]["L0.attn"]["write"])))
        L.append("")
        rho_u, rho_d = [], []
        for r in M.values():
            reg = [clue(ck(r, u)) for u in us]
            rho_u.append(spearmanr([ck(r, u)["use"]["eval"]["use"] for u in us], reg)[0])
            rho_d.append(spearmanr([best_marg(ck(r, u)) for u in us], [ck(r, u)["policy"]["regret"] for u in us])[0])
        L += ["Spearman over checkpoints, per seed: use vs bank regret (≥ 1 clue) " + ", ".join(f(x, 2) for x in rho_u)
              + "; best-site marginal R² vs bank regret " + ", ".join(f(x, 2) for x in rho_d) + ".", ""]
        S.append(("N7", "use tracks regret (ρ ≤ −0.8), decodability does not (ρ > −0.5)", max(rho_u) <= -0.8 and min(rho_d) > -0.5,
                  f"use {ms(rho_u, 2)}; decodability {ms(rho_d, 2)}"))
        w0 = per_seed(M, lambda r: ck(r, first)["writes"]["L0.attn"]["rel_norm"]); w1 = per_seed(M, lambda r: ck(r, last)["writes"]["L0.attn"]["rel_norm"])
        S.append(("N12", "L0.attn's twin difference grows ≥ 3×", min(b / a for a, b in zip(w0, w1)) >= 3, f"{ms(w0)} → {ms(w1)}"))

        # ---- 4 causal
        comps = list(ck(any_r, last)["causal"]["eval"]["twin"])
        L += ["## 4. Interventions at the decision token, final checkpoint, held-out layouts", "",
              "cf: gain in probability of the counterfactual optimal set as a share of the model's own gain on the twin "
              "(pairs with disjoint exact optimal sets). belief: decoded displacement of the marginals along the exact one. "
              "to twin / to donor: cross-position pairs (section 4 of THEORY.md). Mean ± sd over seeds.", ""] + \
            head("component", "twin: cf", "twin: belief", "twin: other marginal", "same belief: cf", "random: cf", "cross: to twin", "cross: to donor",
                 "discovery layouts, twin: cf")
        C = lambda r, split="eval": ck(r, last)["causal"][split]
        for c in comps:
            xs = lambda kind, k, split="eval": ms([C(r, split)[kind][c][k] for r in M.values()], 2)
            cs = lambda k: ms([C(r)["cross_strict"].get(c, {}).get(k) for r in M.values()], 2)
            L.append(row(c, xs("twin", "cf_mass"), xs("twin", "belief"), xs("twin", "off"), xs("same", "cf_mass"), xs("random", "cf_mass"),
                         cs("to_twin"), cs("to_donor"), xs("twin", "cf_mass", "discovery")))
        L += ["", "Pairs per seed: " + "; ".join(f"seed {s}: {C(r)['twin']['resid4']['n_disjoint']} decisive twin pairs, "
                                                 f"{C(r)['cross_strict']['n']} strict cross pairs ({C(r)['cross_strict'].get('n_separated', 0)} separated)"
                                                 for s, r in M.items()), ""]
        a0 = per_seed(M, lambda r: C(r)["twin"]["L0.attn"]["cf_mass"])
        later = per_seed(M, lambda r: max(C(r)["twin"][f"L{l}.attn"]["cf_mass"] for l in (1, 2, 3)))
        S.append(("N8", "evidence enters at L0.attn (cf ≥ 0.7; L1–L3.attn ≤ 0.2)", min(a0) >= 0.7 and max(later) <= 0.2,
                  f"L0 {ms(a0, 2)}; later max {ms(later, 2)}"))
        ctl = per_seed(M, lambda r: max(abs(C(r)[k][c]["cf_mass"]) for k in ("same", "random") for c in comps))
        S.append(("N9", "controls flat (|cf| ≤ 0.05, every component)", max(ctl) <= 0.05, f"max |cf| {ms(ctl)}"))
        ratio = per_seed(M, lambda r: C(r)["twin"]["L0.attn"]["off"] / abs(C(r)["twin"]["L0.attn"]["belief"] * 0.6))
        S.append(("N10", "a report moves its own marginal (other / own ≤ 0.2)", max(ratio) <= 0.2, ms(ratio)))
        nonres = [c for c in comps if not c.startswith("resid")]
        td = per_seed(M, lambda r: C(r)["cross_strict"]["L0.attn"]["to_donor"])
        clean = per_seed(M, lambda r: [c for c in nonres if (C(r)["cross_strict"][c]["to_twin"] or 0) >= 0.6 and (C(r)["cross_strict"][c]["to_donor"] or 0) <= 0.3])
        S.append(("N11", "no position-free belief carrier (L0.attn to donor ≥ 0.6; no component with to twin ≥ 0.6 and to donor ≤ 0.3)",
                  min(td) >= 0.6 and not any(clean), f"L0.attn to donor {ms(td, 2)}; clean carriers: {[c for x in clean for c in x] or 'none'}"))

        # ---- 5 development of the causal picture
        key = [u for u in us if "causal" in ck(any_r, u)]
        L += ["### Twin patch (cf) along training, mean over seeds, held-out layouts", "", "The model's own gain on the twin is the denominator; "
              "it is near 0 early, where the ratio is noise ('twin gain' column).", ""] + \
            head("update", "twin gain", "L0.attn", "L0.mlp", "L1.attn", "L1.mlp", "L2.attn", "L2.mlp", "L3.attn", "L3.mlp")
        for u in key:
            g = lambda c: f(np.mean([ck(r, u)["causal"]["eval"]["twin"][c]["cf_mass"] for r in M.values()]), 2)
            L.append(row(u, f(np.mean([ck(r, u)["causal"]["eval"]["twin"]["resid4"]["cf_full"] for r in M.values()])),
                         *[g(f"L{l}.{k}") for l in range(4) for k in ("attn", "mlp")]))
        L.append("")

        # ---- 6 heads
        L += ["## 5. What heads move from report tokens (final checkpoint)", "",
              "own: decoded displacement of the reported coordinate's marginal per report token, towards the reported side; other: of the other "
              "marginal. Heads are not aligned across seeds; each seed's three largest.", ""] + head("seed", "head", "own", "other", "attention on report tokens", "twin patch: cf")
        for s, r in M.items():
            src = ck(r, last)["sources"]
            for h in sorted(src, key=lambda h: -abs(src[h]["on"]))[:3]:
                L.append(row(s, h, f(src[h]["on"]), f(src[h]["off"]), f(src[h]["attn_report_total"], 2), f(C(r)["twin"][h]["cf_mass"], 2)))
        L.append("")

    # ---- reliability
    if G and all("qgen" in r for r in G.values()):
        L += ["## 6. Reliability generalisation (greedy regret, final checkpoint)", ""] + head("model", "seed", "trained pairs", "held-out values", "held-out combinations",
                                                                                           "(0.6, 0.6)", "(0.95, 0.95)", "TV between told 0.6 and 0.95")
        def by(r, k):
            return float(np.mean([p["regret"] for p in r["qgen"]["pairs"] if p["set"] == k]))
        def at(r, a, b):
            return next(p["regret"] for p in r["qgen"]["pairs"] if p["qh"] == a and p["qv"] == b)
        for name, runs in (("ppo, grid q", G), ("supervised, grid q", SG), ("ppo, fixed q", P)):
            for s, r in runs.items():
                if "qgen" in r:
                    L.append(row(name, s, f(by(r, "train"), 4), f(by(r, "held_value"), 4), f(by(r, "held_combo"), 4), f(at(r, 0.6, 0.6), 4),
                                 f(at(r, 0.95, 0.95), 4), f(r["qgen"]["sensitivity"]["tv"])))
        L.append("")
        tr = per_seed(G, lambda r: by(r, "train")); hv = per_seed(G, lambda r: by(r, "held_value")); hc = per_seed(G, lambda r: by(r, "held_combo"))
        S.append(("N13", "grid models: trained pairs ≤ 0.03 in ≥ 2 of 3 seeds; held-out within 0.01",
                  sum(t <= 0.03 for t in tr) >= 2 and all(abs(a - t) <= 0.01 and abs(b - t) <= 0.01 for t, a, b in zip(tr, hv, hc)),
                  f"trained {ms(tr, 4)}; values {ms(hv, 4)}; combinations {ms(hc, 4)}"))
        GM = {s: r for s, r in G.items() if "measures" in r}
        if GM:
            lastg = cps(next(iter(GM.values())))[-1]
            a = per_seed(GM, lambda r: best_marg(ck(r, lastg), "trained")); b = per_seed(GM, lambda r: best_marg(ck(r, lastg), "held"))
            L += ["Grid models, held-out affine decoding of the marginals (decoder fitted on trained reliabilities), best site: trained pairs "
                  f"{ms(a)}, held-out pairs {ms(b)}; initialisation " + ms(per_seed(GM, lambda r: best_marg(ck(r, cps(r)[0]), 'trained'))) + ".", ""]
            S.append(("N14", "decoding generalises over reliability (held ≥ trained − 0.1)", all(y >= x - 0.1 for x, y in zip(a, b)), f"{ms(a)} vs {ms(b)}"))
        PQ = [at(r, 0.6, 0.6) for r in P.values() if "qgen" in r]
        if PQ:
            g6 = np.mean(per_seed(G, lambda r: at(r, 0.6, 0.6)))
            S.append(("N15", "fixed-q models ignore reliability (regret at (0.6, 0.6) ≥ grid models' + 0.02)", min(PQ) >= g6 + 0.02,
                      f"fixed {ms(PQ, 4)}; grid {f(g6, 4)}"))

    S.sort(key=lambda s: int(s[0][1:]))
    L += ["## Scorecard", ""] + head("", "prediction", "held", "numbers") + [row(a, b, "**yes**" if c else "no", d) for a, b, c, d in S]
    L += ["", f"{sum(bool(s[2]) for s in S)} of {len(S)} held."]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[-len(S) - 6:]))
    return P, FZ, SUP, G


def figures(P, FZ, SUP, G):
    M = {s: r for s, r in P.items() if "measures" in r}
    # fig 1: learning curves
    fig, ax = plt.subplots(1, 3, figsize=(12, 3.4))
    for s, r in P.items():
        u = [max(e["update"], 1) for e in r["log"]]
        ax[0].plot(u, [e["greedy_regret"] for e in r["log"]], color=BLUE, lw=1.2, alpha=0.75, label="reward (PPO), 5 seeds" if s == 0 else None)
        ax[1].plot(u, [e["greedy_queries"] for e in r["log"]], color=BLUE, lw=1.2, alpha=0.75)
    for runs, col, lab in ((FZ, GREY, "frozen backbone"), (SUP, ORANGE, "solver-supervised")):
        for i, r in enumerate(runs.values()):
            u = [max(e["update"], 1) for e in r["log"]]
            ax[0].plot(u, [e["greedy_regret"] for e in r["log"]], color=col, lw=1.2, label=lab if i == 0 else None)
            ax[1].plot(u, [e["greedy_queries"] for e in r["log"]], color=col, lw=1.2)
    ax[0].axhline(0.101, color=MUTED, lw=0.8, ls=":"); ax[0].text(1.2, 0.105, "never query", fontsize=7, color=MUTED)
    ax[1].axhline(1.25, color=MUTED, lw=0.8, ls=":"); ax[1].text(1.2, 1.28, "optimal policy", fontsize=7, color=MUTED)
    ax[0].set_title("Greedy regret", fontsize=9, color=INK, loc="left"); ax[1].set_title("Queries per episode", fontsize=9, color=INK, loc="left")
    ax[0].legend(fontsize=7, frameon=False)
    if P:
        logs = [r["log"] for r in P.values()]
        u = [max(e["update"], 1) for e in logs[0]]
        for k, col, lab in (("route", BLUE, "route"), ("query", ORANGE, "query"), ("commit", GREEN, "commit")):
            ax[2].plot(u, np.mean([[e["greedy_err_" + k] for e in l] for l in logs], 0), color=col, lw=2, label=lab)
        ax[2].set_title("Regret by kind of error (mean of seeds)", fontsize=9, color=INK, loc="left"); ax[2].legend(fontsize=7, frameon=False)
    for a in ax:
        a.set_xscale("log"); a.set_xlabel("updates", fontsize=8, color=INK); _style(a)
    fig.tight_layout(); fig.savefig(OUT / "fig1_learning.png", dpi=160); plt.close(fig)
    if not M:
        return
    any_r = next(iter(M.values())); sites, us = any_r["measures"]["sites"], cps(any_r)
    # fig 2: layer by checkpoint
    fig, ax = plt.subplots(1, 2, figsize=(12, 4.6))
    for a, fn, title in ((ax[0], marg, "Marginals: held-out affine R²"), (ax[1], lambda s: s["r2"][6], "Product of the marginals: held-out affine R²")):
        Z = np.array([[np.mean([fn(ck(r, u)["probes"]["trained"][n]) for r in M.values()]) for n in sites] for u in us])
        im = a.imshow(Z, aspect="auto", cmap="Blues", vmin=0, vmax=1)
        a.set_xticks(range(len(sites))); a.set_xticklabels(sites, fontsize=7, rotation=45, ha="right")
        a.set_yticks(range(len(us))); a.set_yticklabels(us, fontsize=6)
        a.set_ylabel("updates", fontsize=8); a.set_title(title, fontsize=9, color=INK, loc="left")
        for i in range(len(us)):
            for j in range(len(sites)):
                a.text(j, i, f"{Z[i, j]:.2f}", ha="center", va="center", fontsize=5, color="white" if Z[i, j] > 0.55 else INK)
        fig.colorbar(im, ax=a, fraction=0.03)
    fig.tight_layout(); fig.savefig(OUT / "fig2_layers.png", dpi=160); plt.close(fig)
    # fig 3: timeline, small multiples with one axis each
    clue = lambda m: (m["policy"]["regret_1clue"] + m["policy"]["regret_2clue"]) / 2
    panels = (("Regret on fixed histories, ≥ 1 clue", clue), ("Use of evidence (twins)", lambda m: m["use"]["eval"]["use"]),
              ("Best-site marginal R² (affine)", best_marg), ("L0 attention: twin difference / norm", lambda m: m["writes"]["L0.attn"]["rel_norm"]))
    fig, ax = plt.subplots(1, 4, figsize=(14, 3.2))
    x = [max(u, 1) for u in us]
    for a, (title, fn) in zip(ax, panels):
        for r in M.values():
            a.plot(x, [fn(ck(r, u)) for u in us], color=BLUE, lw=0.9, alpha=0.5)
        a.plot(x, np.mean([[fn(ck(r, u)) for u in us] for r in M.values()], 0), color=INK, lw=1.8)
        a.set_xscale("log"); a.set_title(title, fontsize=9, color=INK, loc="left"); a.set_xlabel("updates", fontsize=8); _style(a)
    fig.tight_layout(); fig.savefig(OUT / "fig3_timeline.png", dpi=160); plt.close(fig)
    # fig 4: causal
    last = us[-1]
    comps = [c for c in ck(any_r, last)["causal"]["eval"]["twin"]]
    fig, ax = plt.subplots(2, 1, figsize=(13, 5.6), sharex=True)
    xs = np.arange(len(comps))
    mean = lambda kind, k: np.array([np.mean([ck(r, last)["causal"]["eval"][kind][c][k] for r in M.values()]) for c in comps])
    for i, (kind, col, lab) in enumerate((("twin", BLUE, "twin (report flipped)"), ("same", GREY, "same belief, other history"), ("random", AMBER, "random, same norm"))):
        ax[0].bar(xs + (i - 1) * 0.27, mean(kind, "cf_mass"), 0.25, color=col, label=lab)
    ax[0].set_title("Patch at the decision token: share of the counterfactual action gain", fontsize=9, color=INK, loc="left")
    cs = lambda k: np.array([np.mean([ck(r, last)["causal"]["eval"]["cross_strict"][c][k] or 0 for r in M.values()]) for c in comps])
    ax[1].bar(xs - 0.15, cs("to_twin"), 0.28, color=BLUE, label="towards own position with donor's belief")
    ax[1].bar(xs + 0.15, cs("to_donor"), 0.28, color=ORANGE, label="towards the donor's position")
    ax[1].set_title("Donor at another position: where the action distribution moves", fontsize=9, color=INK, loc="left")
    ax[1].set_xticks(xs); ax[1].set_xticklabels(comps, fontsize=7, rotation=60, ha="right")
    for a in ax:
        a.legend(fontsize=7, frameon=False, ncol=3); _style(a); a.axhline(0, color=MUTED, lw=0.6)
    fig.tight_layout(); fig.savefig(OUT / "fig4_causal.png", dpi=160); plt.close(fig)
    # fig 5: reliability
    GQ = [r for r in G.values() if "qgen" in r]; PQ = [r for r in P.values() if "qgen" in r]
    if GQ and PQ:
        fig, ax = plt.subplots(1, 2, figsize=(10, 4.4))
        qs = sorted({p["qh"] for p in GQ[0]["qgen"]["pairs"]})
        for a, runs, title in ((ax[0], GQ, "Trained on the reliability grid"), (ax[1], PQ, "Trained on (0.8, 0.8) only")):
            Z = np.zeros((8, 8)); held = np.zeros((8, 8), bool)
            for p in runs[0]["qgen"]["pairs"]:
                i, j = qs.index(p["qh"]), qs.index(p["qv"])
                Z[i, j] = np.mean([next(x["regret"] for x in r["qgen"]["pairs"] if x["qh"] == p["qh"] and x["qv"] == p["qv"]) for r in runs])
                held[i, j] = p["set"] != "train"
            im = a.imshow(Z, cmap="Blues", vmin=0, vmax=max(0.05, Z.max()))
            for i in range(8):
                for j in range(8):
                    a.text(j, i, f"{Z[i, j]:.3f}" + ("*" if held[i, j] and runs is GQ else ""), ha="center", va="center", fontsize=6,
                           color="white" if Z[i, j] > 0.6 * im.get_clim()[1] else INK)
            a.set_xticks(range(8)); a.set_xticklabels(qs, fontsize=7); a.set_yticks(range(8)); a.set_yticklabels(qs, fontsize=7)
            a.set_xlabel("vertical station reliability", fontsize=8); a.set_ylabel("horizontal station reliability", fontsize=8)
            a.set_title(title + ": greedy regret" + (" (* held out)" if runs is GQ else ""), fontsize=9, color=INK, loc="left")
        fig.tight_layout(); fig.savefig(OUT / "fig5_reliability.png", dpi=160); plt.close(fig)


if __name__ == "__main__":
    figures(*tables())
