"""The MLP-bilinear experiment: tables and the registered decision rule from results.json and untrained.json.

    .venv/bin/python studies/5_goal_belief_mechanism/mlp_bilinear/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
RANKS = (1, 2, 3, 4, 6, 8)


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    U = json.load(open(OUT / "untrained.json"))["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    u = lambda *p: np.array([_get(U[s], p) for s in seeds], dtype=float)
    c = R["cells"]
    L = ["# The MLP-bilinear experiment tables", "", "Generated by `studies/5_goal_belief_mechanism/mlp_bilinear/tables.py`. The observation-prediction experiment's ten reward models and their initial checkpoints; block 0's MLP at the goal token. "
         f"Causal cells: goal-matters {c['goal_matters']}, goal-neutral {c['goal_neutral']}. Median (range) over the ten models.", ""]
    L += ["## The goal × belief part J and its noise ceiling", ""]
    L += head("", "trained", "untrained")
    L.append(row("posteriors in the analysis set", mr(v("n_posteriors"), 0), mr(u("n_posteriors"), 0)))
    L.append(row("split-half reliability of J_y (r)", mr(v("reliability")), mr(u("reliability"))))
    L.append(row("noise ceiling (Spearman–Brown)", mr(v("ceiling")), mr(u("ceiling"))))
    L.append(row("|J_y|² / |M_y|² (output)", mr(v("sizes", "J_y") / v("sizes", "M_y")), mr(u("sizes", "J_y") / u("sizes", "M_y"))))
    L.append(row("|J_u|² / |M_u|² (input)", mr(v("sizes", "J_u") / v("sizes", "M_u")), mr(u("sizes", "J_u") / u("sizes", "M_u"))))
    L += ["", "## Descriptions of J_y: R² (R² / ceiling)", ""]
    L += head("description", "trained", "trained / ceiling", "untrained", "untrained / ceiling")
    for k, kl in [("bilinear_b", "bilinear in the posterior b"), ("bilinear_B", "**bilinear in the MLP's belief input B (full)**")] + [(f"cp_{r}", f"rank {r}: Σ (u·B)(v·G) w") for r in RANKS]:
        L.append(row(kl, mr(v("describe", k), 2), mr(v("describe", k) / v("ceiling"), 2), mr(u("describe", k), 2), mr(u("describe", k) / u("ceiling"), 2)))
    L += ["", "## Mechanism: the MLP applied to the decomposed input (no fitted parameters)", ""]
    L += head("", "trained", "untrained")
    for k, kl in (("exact_vs_Jy", "exact interaction f(ū+B+G) − f(ū+B) − f(ū+G) + f(ū), against J_y: R²"), ("taylor_vs_Jy", "second-order term, against J_y: R²"),
                  ("taylor_vs_exact", "second-order term, against the exact interaction: R²"), ("exact_size", "|exact|² / |J_y|²"), ("Jy_sub_vs_Jy", "(J_y on the 20 000-history subset against the full table)")):
        L.append(row(kl, mr(v("mechanism", k), 2), mr(u("mechanism", k), 2)))
    L += ["", "## Hidden units carrying J_y", ""]
    L += head("", "trained", "untrained")
    L.append(row("units for half of the energy", mr(v("units", "n_for_half"), 0), mr(u("units", "n_for_half"), 0)))
    L.append(row("units for 80 %", mr(v("units", "n_for_80"), 0), mr(u("units", "n_for_80"), 0)))
    for k in (5, 10, 20, 50, 100):
        L.append(row(f"top {k} units: energy share; J_y rebuilt R²", f"{mr(v('units', f'top{k}_energy'), 2)}; {mr(v('units', f'top{k}_r2'), 2)}",
                     f"{mr(u('units', f'top{k}_energy'), 2)}; {mr(u('units', f'top{k}_r2'), 2)}"))
    L += ["", "## Causal: the MLP output at the goal token, y − J_y(b, g) + X (trained)", ""]
    L += ["The ablation's drop is too small for a restored fraction to be meaningful (median-of-ratio ranges explode); absolute differences from the ablation are shown.", ""]
    L += head("X", "goal-matters: optimal", "− ablate", "goal-neutral: optimal")
    cm = lambda k: v("causal", "goal_matters", k)
    cn = lambda k: v("causal", "goal_neutral", k)
    rest = lambda k: (cm(k) - cm("ablate")) / np.maximum(cm("natural") - cm("ablate"), 1e-9)
    for k, kl in (("natural", "J_y (natural)"), ("ablate", "0 (ablate)"), ("cp_1", "rank 1"), ("cp_2", "rank 2"), ("cp_4", "rank 4"), ("bilinear_B", "full bilinear"), ("shuffled", "another posterior's J_y")):
        L.append(row(kl, mr(cm(k)), mr(cm(k) - cm("ablate")) if k != "ablate" else "—", mr(cn(k))))
    # decision rule
    BL = np.median(v("describe", "bilinear_B") / v("ceiling"))
    LR = np.median(v("describe", "cp_4") / v("describe", "bilinear_B"))
    X = np.median(v("mechanism", "exact_vs_Jy"))
    T = np.median(v("mechanism", "taylor_vs_exact"))
    drop = cm("natural") - cm("ablate")
    pC = p_gt(cm("natural"), cm("ablate"))
    C = np.median(drop) >= 0.05 and pC < 0.05 and np.median(rest("cp_4")) >= 0.75 and np.median(rest("shuffled")) <= 0.25
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**BL**", "bilinear_B R² / ceiling ≥ 0.7", f(BL, 2), yes(BL >= 0.7)))
    L.append(row("**LR**", "cp_4 ≥ 0.8 × bilinear_B", f"{f(LR, 2)} ×", yes(LR >= 0.8)))
    L.append(row("**X**", "exact against J_y R² ≥ 0.5", f(X, 2), yes(X >= 0.5)))
    L.append(row("**T**", "taylor against exact R² ≥ 0.8", f(T, 2), yes(T >= 0.8)))
    L.append(row("**C**", "ablate drop ≥ 0.05 (p < 0.05); cp_4 restores ≥ 0.75; shuffled ≤ 0.25",
                 f"drop {f(np.median(drop))} (p {fp(pC)}); restoration not interpretable at this drop", yes(C)))
    rmin = [next((r for r in RANKS if runs[s]["describe"][f"cp_{r}"] >= 0.8 * runs[s]["describe"]["bilinear_B"]), None) for s in seeds]
    L += ["", f"Smallest rank reaching 0.8 × full bilinear, per model: {rmin}. Trained − untrained bilinear_B: {mr(v('describe', 'bilinear_B') - u('describe', 'bilinear_B'), 2)}.", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
