"""Tables of the pair-terms experiment, from results.json.

    .venv/bin/python studies/7_information_seeking/pair_terms/tables.py [--results PATH] [--out DIR]
"""

from __future__ import annotations

import argparse, json
from itertools import product
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
RULES = ["mixture", "mixture_popt", "robust", "commit", "disambiguate", "lookahead"]
LABEL = {"step": "step only", "mixture": "mixture of the model's single-cell profiles", "mixture_popt": "mixture of popt", "robust": "robust (a shortest-path move from both cells)",
         "commit": "commit (the likelier cell's popt)", "disambiguate": "disambiguate (expected information gain)", "lookahead": "lookahead (goal-averaged one-step lookahead value)",
         "mixture_raw": "the mixture in H's own units, no map", "mlp_b": "MLP on b, two-cell decisions only", "affine_all_decisions": "the affine fit of all decisions, scored here"}


def med(xs):
    xs = [x for x in xs if x is not None and np.isfinite(x)]
    return (float(np.median(xs)), float(min(xs)), float(max(xs))) if xs else (float("nan"),) * 3


def f3(m, nd=3):
    return f"{m[0]:.{nd}f} ({m[1]:.{nd}f}–{m[2]:.{nd}f})"


def wilcoxon_greater(x, y):
    d = np.array([a - b for a, b in zip(x, y) if a is not None and b is not None]); d = d[d != 0]
    if len(d) == 0:
        return 1.0
    r = np.argsort(np.argsort(np.abs(d))) + 1
    W = float(r[d > 0].sum())
    return sum(1 for sg in product((0, 1), repeat=len(d)) if float(sum(ri for ri, s_ in zip(r, sg) if s_)) >= W) / 2 ** len(d)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=str(HERE / "results.json"))
    ap.add_argument("--out", default=str(HERE))
    a = ap.parse_args()
    res = json.load(open(a.results)); runs = list(res["runs"].values())
    out = Path(a.out); out.mkdir(parents=True, exist_ok=True)
    g = lambda f: [f(r) for r in runs]
    L = ["# Pair terms: tables", "", f"Generated by `tables.py` from `results.json`: {len(runs)} models; medians (min–max) over models.", "",
         f"Two-cell decisions: {f3(med(g(lambda r: r['two_cell_share'])), 2)} of the test decisions ({f3(med(g(lambda r: r['two_cell_test'])), 0)} per model); the pair's two cells both have a "
         f"single-cell profile (≥ {20} near-certain decisions) in {f3(med(g(lambda r: r['covered_share_test'])), 2)} of them; cells with a profile {f3(med(g(lambda r: r['cells_covered'])), 0)} of 55; "
         f"mean conflict {f3(med(g(lambda r: r['conflict_mean'])), 2)}.", ""]
    L += ["## A. Departure from the mixture ‖H − mixture‖² / ‖H‖² (median over decisions), by conflict", "", "| conflict | decisions | departure |", "|---|---|---|"]
    for k in ("0", "(0,0.5]", "(0.5,1]"):
        L.append(f"| {k} | {f3(med(g(lambda r: r['decisions_by_conflict'][k])), 0)} | {f3(med(g(lambda r: r['departure_by_conflict'][k])), 2)} |")
    L += ["", "## B. Prediction of H on two-cell decisions (held-out R²)", "", "| model of H | R² |", "|---|---|"]
    keys = ["step"] + RULES + ["mixture+" + k for k in RULES[2:]] + ["mixture+all", "mixture_raw", "mlp_b", "affine_all_decisions"]
    for k in keys:
        L.append(f"| {LABEL.get(k, k)} | {f3(med(g(lambda r: r['r2'][k])))} |")
    L += ["", "## C. H's top action where a rule's top action differs from the mixture's", "", "| rule | decisions | H's top is the rule's | H's top is the mixture's | p (rule > mixture) |", "|---|---|---|---|---|"]
    for k in RULES[2:]:
        p = wilcoxon_greater(g(lambda r: r['top'][k]['rule']), g(lambda r: r['top'][k]['mixture']))
        L.append(f"| {k} | {f3(med(g(lambda r: r['top'][k]['decisions'])), 0)} | {f3(med(g(lambda r: r['top'][k]['rule'])), 2)} | {f3(med(g(lambda r: r['top'][k]['mixture'])), 2)} | {p:.3f} |")
    b = lambda k: g(lambda r: r['behaviour'][k])
    nc = lambda k: g(lambda r: r['behaviour']['no_common'][k])
    L += ["", "## D. The model's own move under its goal", "",
          f"A shortest-path move from both cells exists in {f3(med(b('common_exists_share')), 2)} of two-cell decisions. Where one exists and none of them is a move of the likelier cell "
          f"({f3(med(b('common_differs_from_likelier')), 0)} decisions): the model takes a common move in {f3(med(b('takes_common')), 2)}, a likelier-cell move in {f3(med(b('takes_likelier')), 2)}.", "",
          f"Where no common move exists ({f3(med(nc('decisions')), 0)} decisions): the model takes a likelier-cell move in {f3(med(nc('takes_likelier')), 2)}, the most informative move in "
          f"{f3(med(nc('takes_eig_top')), 2)}, QMDP's move in {f3(med(nc('takes_qmdp_top')), 2)}, QMDP + lookahead's in {f3(med(nc('takes_qmdp2_top')), 2)}.", ""]
    # decision rule
    dep0, dep1 = g(lambda r: r['departure_by_conflict']['0']), g(lambda r: r['departure_by_conflict']['(0.5,1]'])
    conf = all(x is not None and y is not None and x > y for x, y in zip(dep1, dep0))
    mix = float(np.median(g(lambda r: r['r2']['mixture'])))
    singles = {k: float(np.median(g(lambda r: r['r2'][k]))) for k in RULES[2:]}
    best = max(singles, key=singles.get); runner = sorted(singles.values())[-2]
    gain = singles[best] - mix >= 0.1
    which = singles[best] - runner >= 0.03
    ptop = wilcoxon_greater(g(lambda r: r['top'][best]['rule']), g(lambda r: r['top'][best]['mixture']))
    top = float(np.median(g(lambda r: r['top'][best]['rule']))) > float(np.median(g(lambda r: r['top'][best]['mixture']))) and ptop < 0.05
    tc = [x for x in b('takes_common') if x is not None]
    beh = bool(tc) and float(np.median(tc)) >= 0.6
    L += ["## Decision rule", "", "| criterion | value | held |", "|---|---|---|",
          f"| CONF | departure at conflict > 0.5 against 0: {f3(med(dep1), 2)} against {f3(med(dep0), 2)} | {'yes' if conf else 'no'} |",
          f"| GAIN | best single rule {best} {singles[best]:.3f} against mixture {mix:.3f} (+{singles[best] - mix:.3f}) | {'yes' if gain else 'no'} |",
          f"| WHICH | {best} against runner-up {runner:.3f} | {'yes' if which else 'no'} |",
          f"| TOP | {best}: H's top is the rule's {np.median(g(lambda r: r['top'][best]['rule'])):.2f} against the mixture's {np.median(g(lambda r: r['top'][best]['mixture'])):.2f}, p {ptop:.3f} | {'yes' if top else 'no'} |",
          f"| BEH | takes the common move {f3(med(b('takes_common')), 2)} | {'yes' if beh else 'no (the set is empty by construction: a move optimal from both cells is a move of the likelier cell; see posthoc.md)'} |"]
    (out / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
