"""The belief-error experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/5_goal_belief_mechanism/belief_error/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
COEF = ("margin", "unsolvable", "interaction", "goal_G2", "goal_G3", "entropy", "H_error", "r_norm")


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([np.nan if (x := _get(runs[s], p)) is None else x for s in seeds], dtype=float)
    L = ["# The belief-error experiment tables", "",
         "Generated by `studies/5_goal_belief_mechanism/belief_error/tables.py`. The observation-prediction experiment's ten reward models; informative pairs "
         f"{mr(v('pairs'), 0)} per model. Median (range).", "",
         f"Decoder (ridge, d → exact posterior): held-out R² {mr(v('decoder', 'r2'))}; ridge {mr(v('decoder', 'ridge'), 4)} (the smallest in the grid in every model). "
         f"Decoded error, total variation: {mr(v('decoded_error_tv', 'mean'))}; correlation with posterior entropy {mr(v('decoded_error_tv', 'corr_with_entropy'), 2)}.", ""]
    for kn, label in (("k95", "S at 95 % of x_b's variance"), ("k13", "S with k = 13")):
        sv = lambda *p: v("subspaces", kn, *p)
        L += [f"## {label} (k {mr(sv('k'), 0)}; x_b variance {mr(sv('xb_var_share'))}; r's variance in S {mr(sv('r_var_share_in_S'))})", ""]
        L += head("arm", "flip real", "flip rotated (same space, same size)", "excess flip", "share of real_r's excess", "shift real", "shift rotated")
        ex_r = sv("excess_flip", "r")
        for n, nl in (("r", "whole r"), ("par", "r inside S"), ("perp", "r outside S")):
            L.append(row(nl, mr(sv("flip", f"real_{n}")), mr(sv("flip", f"rot_{n}")), mr(sv("excess_flip", n)), mr(sv("excess_flip", n) / ex_r, 2),
                         mr(sv("shift", f"real_{n}")), mr(sv("shift", f"rot_{n}"))))
        L.append("")
    L += ["## Joint fit of the excess shift, without and with the decoded error's change", ""]
    L += head("", *COEF, "decoded error")
    L.append(row("without", *[mr(v("joint_without", k)) for k in COEF], "—"))
    L.append(row("with", *[mr(v("joint_with", k)) for k in COEF], mr(v("joint_with", "decoded_error"))))
    ex = lambda n: v("subspaces", "k95", "excess_flip", n)
    rp, rq = np.median(ex("par") / ex("r")), np.median(ex("perp") / ex("r"))
    be = rp >= 0.75 and rq <= 0.25
    pD = p_gt(v("joint_with", "decoded_error"), np.zeros(len(seeds)))
    drop = 1 - np.median(v("joint_with", "entropy") / v("joint_without", "entropy"))
    med = pD < 0.05 and drop >= 0.5
    yes = lambda b: "**yes**" if b else "no"
    pPerp = p_gt(ex("perp"), ex("par"))
    L += ["", "## Decision rule (registered)", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**BE**", "real_par excess ≥ 0.75 × real_r's, and real_perp's ≤ 0.25 × (k at 95 %)", f"{f(rp, 2)} ×; {f(rq, 2)} ×", yes(be)))
    L.append(row("**MED**", "decoded-error coefficient > 0, and entropy coefficient falls ≥ 50 %",
                 f"{f(np.median(v('joint_with', 'decoded_error')))} (p {fp(pD)}); entropy falls {f(drop * 100, 0)} %", yes(med)))
    reading = ("r is belief error" if be and med else "r acts through the belief code, not indexed by the decoded error" if be else
               "r's effect lies outside the belief code")
    L += ["", f"Not registered: excess of r outside S above r inside S, p {fp(pPerp)}.", "", f"**Registered reading: {reading}.**", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
