"""The H-mixture experiment: tables and the registered decision rule from results.json.

    .venv/bin/python studies/5_goal_belief_mechanism/H_mixture/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
QN = dict(opt="1[a optimal under g]", Q="Q*(b, g, a)", MDP="reachability Q_MDP(b, g, a)")


def main():
    runs = json.load(open(OUT / "results.json"))["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    L = ["# The H-mixture experiment tables", "", "Generated by `studies/5_goal_belief_mechanism/H_mixture/tables.py`. The observation-prediction experiment's ten reward models; H = the goal-averaged centred logits at the goal token "
         "(additive code). Held-out R² (the what-is-H experiment's setting). Median (range) over the ten models.", ""]
    L += ["## Prediction of H", ""]
    L += head("model", "parameters per action", "R²")
    for lab, p_, x in (("P(optimal | random goal)", "4 × 4", v("single", "popt")), ("mean reachability", "4 × 4", v("single", "meanMDP")), ("mean Q*", "4 × 4", v("single", "meanQ")),
                       ("P(optimal) + mean reachability", "8 × 4", v("mix_popt_meanMDP")), ("**mix: all three**", "12 × 4", v("mix")),
                       ("**weighted: 3 quantities × 3 goal slopes**", "9 in total", v("weighted", "r2")), ("weighted, equal goal weights", "3 in total", v("weighted", "r2_uniform")),
                       ("ceiling: H per posterior", "", v("Htab"))):
        L.append(row(lab, p_, mr(x, 2)))
    L += ["", "## Goal weights inside H's average (training sampled the goals uniformly: 1/3 each)", ""]
    L += head("per-goal quantity", "w_G1", "w_G2", "w_G3", "R² (free weights)", "R² (equal weights)")
    for q in ("opt", "Q", "MDP"):
        w = np.array([runs[s]["weights"][q]["w"] for s in seeds])
        L.append(row(QN[q], *[mr(w[:, g], 2) for g in range(3)], mr(v("weights", q, "r2"), 2), mr(v("weights", q, "r2_uniform"), 2)))
    ws = {q: np.array([runs[s]["weighted"]["goal_share"][q] for s in seeds]) for q in ("opt", "Q", "MDP")}
    L += ["", "In the nine-slope model, each quantity's goal shares: " + "; ".join(f"{QN[q]}: " + ", ".join(f"G{g + 1} {f(np.median(ws[q][:, g]), 2)}" for g in range(3)) for q in ws) + ".", ""]
    L += ["## Causal edits at the goal token entering block 2 (the what-is-H experiment's editor and pairs)", ""]
    L += head("edit", "change cells: donor-optimal", "gain over none", "share of whole's gain", "goal-dependent pairs", "preserve: harm")
    ch = lambda k: v("edits", "change", k, "donor_optimal")
    for k, kl in (("none", "none"), ("whole", "whole"), ("popt", "P(optimal)"), ("meanMDP", "mean reachability"), ("mix", "**mix (three codes)**"), ("weighted", "**weighted composite (4 numbers)**"),
                  ("weighted_uniform", "weighted composite, equal goal weights"), ("Htab", "ceiling: H per posterior"), ("rotated", "mix, rotated")):
        L.append(row(kl, mr(ch(k)), mr(ch(k) - ch("none")), mr((ch(k) - ch("none")) / (ch("whole") - ch("none")), 2),
                     mr(v("edits", "goal_dependent", k, "right_every_change_goal")), mr(v("edits", "preserve", k, "harm")) if k != "none" else "—"))
    # decision rule
    best_single = np.max(np.stack([v("single", k) for k in ("popt", "meanMDP", "meanQ")], 1), 1)
    pMIX = p_gt(v("mix"), best_single + 0.05)
    gain = lambda k: ch(k) - ch("none")
    pCE = p_gt(gain("mix"), gain("popt") + 0.05)
    dW = np.median(v("weighted", "r2") - v("weighted", "r2_uniform"))
    bestq = max(("opt", "Q", "MDP"), key=lambda q: np.median(v("weights", q, "r2")))
    wdev = np.median(np.abs(np.array([runs[s]["weights"][bestq]["w"] for s in seeds]) - 1 / 3).max(1))
    WC = np.median(gain("weighted") / gain("mix"))
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**MIX**", "mix R² ≥ best single + 0.05", f"{f(np.median(v('mix')), 2)} against {f(np.median(best_single), 2)}; p {fp(pMIX)}", yes(np.median(v("mix") - best_single) >= 0.05 and pMIX < 0.05)))
    L.append(row("**CEm**", "mix edit gain ≥ P(optimal)'s + 0.05", f"{f(np.median(gain('mix')))} against {f(np.median(gain('popt')))}; p {fp(pCE)}", yes(np.median(gain("mix") - gain("popt")) >= 0.05 and pCE < 0.05)))
    L.append(row("**W**", "weighted − equal-weights R² ≤ 0.02; best quantity's max \\|w − 1/3\\| ≤ 0.1", f"{f(dW)}; {bestq}: {f(wdev, 2)}", yes(dW <= 0.02 and wdev <= 0.1)))
    L.append(row("**WC**", "weighted composite's edit gain ≥ 0.9 × mix's", f"{f(WC, 2)} ×", yes(WC >= 0.9)))
    L += ["", f"Weighted against equal-weights composite edit: {mr(gain('weighted') - gain('weighted_uniform'))} (p {fp(p_gt(gain('weighted'), gain('weighted_uniform')))}).", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
