"""Round 22: tables from results.json.

    .venv/bin/python rounds/r22_pair_types/tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path("rounds/r22_pair_types")
f = lambda x, d=2: "—" if x is None or x != x else f"{x:.{d}f}"
row = lambda *c: "| " + " | ".join(str(x) for x in c) + " |"
head = lambda *c: [row(*c), "|" + "---|" * len(c)]
CONDS = (("natural", "natural access"), ("direct_route_removed", "direct route removed"))
KINDS = ("hybrid", "whole", "pca", "pca_complement")
ROWS = (("A", "same", "A: same posterior"), ("B", "same", "B: cells with the same optimal set"), ("B", "disjoint", "B: cells with disjoint optimal sets"), ("C", "disjoint", "C: different action"))


def line(label, x):
    if x.get("n", 0) < 30:
        return row(label, x.get("n", 0), *["—"] * 9)
    return row(label, x["n"], f"{f(x['base_on_optimal'])} / {f(x['base_greedy_optimal'])}",
               " / ".join(f(x[k]["tv_from_base"], 3) for k in KINDS),
               " / ".join(f(x[k]["moved"]) for k in KINDS[1:]),
               " / ".join(f(x[k]["d_optimal"], 3) for k in KINDS),
               " / ".join(f(x[k]["d_optimal_share"]) for k in KINDS[1:]),
               " / ".join(f(x[k]["greedy_changed"]) for k in KINDS),
               " / ".join(f(x[k]["greedy_optimal"]) for k in KINDS),
               " / ".join(f(x[k]["crossing"], 3) for k in KINDS),
               " / ".join(f"{f(x[k]['greedy_within'])}, {f(x[k]['greedy_lost'])}, {f(x[k]['greedy_gained'])}" for k in KINDS[:3]))


COLS = ("cells", "n", "base: P(optimal set) / greedy optimal", "TV from base: hybrid / whole / pca / pca complement", "moved: whole / pca / complement",
        "Δ optimal: hybrid / whole / pca / complement", "Δ optimal as share of hybrid's: whole / pca / complement", "greedy changed: hybrid / whole / pca / complement",
        "greedy in donor's optimal set: hybrid / whole / pca / complement", "post hoc — probability crossing the boundary of the optimal set: hybrid / whole / pca / complement",
        "post hoc — greedy changes (within the set, out of it, into it): hybrid / whole / pca")


def main():
    r = json.load(open(OUT / "results.json")); R = r["runs"]
    L = ["# Round 22 tables", "", "Generated by `rounds/r22_pair_types/tables.py`. The optimal set is the solver's for the donor's evidence under the cell's goal "
         "(in cells with the same optimal set it is also the recipient's).", "", "## 0. Pairs", ""] + head("type", "pairs", "by prefix length", "mean posterior L1", "distinct recipient nodes", "cells: same / disjoint / overlapping")
    for k, v in r["types"].items():
        L.append(row(k, v["n"], ", ".join(f"{a}: {b}" for a, b in v["by_length"].items()), f(v["mean_l1"]), v["distinct_nodes"], " / ".join(str(v["cells"][c]) for c in ("same", "disjoint", "overlapping"))))
    for cond, title in CONDS:
        L += ["", f"## 1. All goals pooled, {title}", ""]
        for k, m in R.items():
            L += ["", f"### {k}", ""] + head(*COLS) + [line(lab, m[cond][ty]["all_goals"][cl]) for ty, cl, lab in ROWS]
            L.append(line("B: the cell chosen as same", m[cond]["B"]["chosen_same"])); L.append(line("B: the cell chosen as disjoint", m[cond]["B"]["chosen_disjoint"]))
    for cond, title in CONDS:
        L += ["", f"## 2. Per goal, {title}", ""]
        for k, m in R.items():
            L += ["", f"### {k}", ""] + head(*COLS)
            for g in ("G1", "G2", "G3"):
                L += [line(f"{g} — {lab}", m[cond][ty]["per_goal"][g][cl]) for ty, cl, lab in ROWS]
    for cond, title in CONDS:
        L += ["", f"## 3. Per prefix length, {title}", ""]
        for k, m in R.items():
            L += ["", f"### {k}", ""] + head(*COLS)
            for l in m[cond]["A"]["by_length"]:
                L += [line(f"length {l} — {lab}", m[cond][ty]["by_length"][l][cl]) for ty, cl, lab in ROWS]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print(len(L), "lines")


if __name__ == "__main__":
    main()
