"""Round 40: tables and the registered decision rule from results.json.

    .venv/bin/python rounds/r40_mlp_depth/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "r32_direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
LAYERS = ("L0", "L1", "L2", "L3")


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    c = R["cells"]
    L = ["# Round 40 tables", "", "Generated by `rounds/r40_mlp_depth/tables.py`. Round 23's ten reward models; the four MLPs at the goal token. "
         f"Ablation cells: goal-matters {c['goal_matters']}, goal-neutral {c['goal_neutral']}. Median (range) over the ten models.", ""]
    L += ["## Per MLP: size, description, mechanism", ""]
    L += head("", *LAYERS)
    lv = lambda *p: [v("layers", l, *p) for l in LAYERS]
    L.append(row("noise ceiling", *[mr(x, 3) for x in lv("ceiling")]))
    L.append(row("|J_y|² / |M_y|² (output: goal × belief / goal main effect)", *[mr(a / b, 2) for a, b in zip(lv("sizes", "J_y"), lv("sizes", "M_y"))]))
    L.append(row("|J_y|² / |S_y|² (output: goal × belief / shared belief)", *[mr(a / b, 2) for a, b in zip(lv("sizes", "J_y"), lv("sizes", "S_y"))]))
    L.append(row("|J_u|² / |M_u|² (input)", *[mr(a / b, 2) for a, b in zip(lv("sizes", "J_u"), lv("sizes", "M_u"))]))
    for k, kl in (("bilinear_b", "bilinear in b: R²"), ("bilinear_B", "**bilinear in the input's belief code B: R²**"), ("cp_1", "rank 1"), ("cp_2", "rank 2"), ("cp_3", "rank 3"),
                  ("cp_4", "**rank 4**"), ("cp_6", "rank 6"), ("cp_8", "rank 8")):
        L.append(row(kl, *[mr(x, 2) for x in lv("describe", k)]))
    for k, kl in (("exact_vs_Jy", "made by the MLP from its rebuilt input: R² against J_y"), ("exact_size", "its size / J_y's"), ("taylor_vs_exact", "second-order share of that interaction (R²)")):
        L.append(row(kl, *[mr(x, 2) for x in lv("mechanism", k)]))
    L.append(row("hidden units for half of J's energy", *[mr(x, 0) for x in lv("units", "n_for_half")]))
    L += ["", "## Ablations: optimal under g", ""]
    L += head("removed from the MLP outputs", "goal-matters", "drop", "goal-neutral", "drop")
    gm = lambda k: v("ablation", "goal_matters", k)
    gn = lambda k: v("ablation", "goal_neutral", k)
    for k, kl in (("natural", "nothing"), ("L0", "J at block 0"), ("L1", "J at block 1"), ("L2", "J at block 2"), ("L3", "J at block 3"), ("L1-3", "J at blocks 1–3"),
                  ("all", "**J at all four**"), ("shuffled_all", "another posterior's J at all four (control)")):
        L.append(row(kl, mr(gm(k)), mr(gm("natural") - gm(k)) if k != "natural" else "—", mr(gn(k)), mr(gn("natural") - gn(k)) if k != "natural" else "—"))
    # decision rule
    d = lambda k: gm("natural") - gm(k)
    dn = lambda k: gn("natural") - gn(k)
    pN1, pN2 = p_gt(gm("natural"), gm("all")), p_gt(d("all"), dn("all") + 0.05)
    N = np.median(d("all")) >= 0.10 and pN1 < 0.05 and np.median(d("all") - dn("all")) >= 0.05 and p_gt(d("all") - dn("all"), np.zeros(len(seeds))) < 0.05
    singles = np.stack([d(l) for l in LAYERS], 1)
    Rr = np.median(singles.max(1) / np.maximum(d("all"), 1e-9))
    pS = p_gt(d("all"), d("shuffled_all"))
    bl_ok = all(np.median(v("layers", l, "describe", "bilinear_B") / v("layers", l, "ceiling")) >= 0.7 and
                np.median(v("layers", l, "describe", "cp_4") / v("layers", l, "describe", "bilinear_B")) >= 0.8 for l in LAYERS)
    yes = lambda b: "**yes**" if b else "no"
    L += ["", "## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**N** necessary", "all four: drop ≥ 0.10 (p < 0.05), ≥ goal-neutral drop + 0.05 (p < 0.05)",
                 f"{f(np.median(d('all')))} (p {fp(pN1)}); goal-neutral {f(np.median(dn('all')))}; difference {f(np.median(d('all') - dn('all')))}", yes(N)))
    L.append(row("**R** redundant", "largest single drop ≤ 0.5 × all-four drop", f"{f(Rr, 2)} ×; largest single at " + ", ".join(LAYERS[i] for i in singles.argmax(1)), yes(Rr <= 0.5)))
    L.append(row("**S** specific", "all-four drop above shuffled-all drop", f"{f(np.median(d('all')))} against {f(np.median(d('shuffled_all')))}; p {fp(pS)}", yes(pS < 0.05)))
    L.append(row("**BLd**", "every layer: bilinear_B / ceiling ≥ 0.7, rank 4 ≥ 0.8 × bilinear", " / ".join(f"{f(np.median(v('layers', l, 'describe', 'bilinear_B')), 2)}, {f(np.median(v('layers', l, 'describe', 'cp_4') / v('layers', l, 'describe', 'bilinear_B')), 2)} ×" for l in LAYERS), yes(bl_ok)))
    L += ["", f"Sum of the four single drops: {mr(singles.sum(1))}; all-four drop {mr(d('all'))}.", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
