"""Round 36: tables and the registered decision rule from results.json and untrained.json.

    .venv/bin/python rounds/r36_query_swap/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent / "r32_direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
KINDS = (("natural", "natural (goal g)"), ("query", "query from g′"), ("selfkv", "goal token's own key and value from g′"), ("both", "both (= block 0 attention under g′)"),
         ("other_goal", "natural under g′ (reference)"))


def main():
    R = json.load(open(OUT / "results.json"))
    U = json.load(open(OUT / "untrained.json"))["runs"]
    runs = R["runs"]
    seeds = sorted(runs, key=lambda s: int(s[4:]))
    v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
    u = lambda *p: np.array([_get(U[s], p) for s in seeds], dtype=float)
    c = R["cells"]
    L = ["# Round 36 tables", "", "Generated by `rounds/r36_query_swap/tables.py`. Round 23's ten reward models (and their initial checkpoints); block 0's attention at the "
         f"goal token. Behaviour cells: goal-matters {c['goal_matters']}, goal-neutral {c['goal_neutral']}. Median (range) over the ten models.", ""]
    L += ["Checks: both swapped against the natural output under g′, largest " + f"{v('representation', 'check_both_equals_other').max():.1e}" +
          "; the recomputed attention against the natural decision, largest |Δp| " + f"{v('behaviour', 'check_recomputed_equals_natural').max():.1e}.", "",
          "Note: over the six ordered goal pairs, share(query) + share(selfkv) = 1 exactly, by construction (each share averages the swap's effect "
          "applied first and applied second; found after the run).", ""]
    L += ["## Representation: share of the goal × history part of block 0's attention output", ""]
    L += head("", "trained: query", "trained: own key and value", "untrained: query", "untrained: own key and value")
    for k, kl in (("share", "goal × history part"), ("share_posterior", "its posterior-explained part")):
        L.append(row(kl, mr(v("representation", k, "query")), mr(v("representation", k, "selfkv")), mr(u("representation", k, "query")), mr(u("representation", k, "selfkv"))))
    L += ["", f"Posterior-explained part of the full swap's history-dependent part: trained {mr(v('representation', 'posterior_part_of_full'))}, untrained "
          f"{mr(u('representation', 'posterior_part_of_full'))}. Its size (squared norm per history): trained {mr(v('representation', 'size_full'), 4)}, untrained {mr(u('representation', 'size_full'), 4)}.", ""]
    for cls, title in (("goal_matters", "goal-matters cells (disjoint optimal sets under g and g′)"), ("goal_neutral", "goal-neutral cells (identical optimal sets)")):
        L += [f"## Behaviour: {title}", ""]
        L += head("block 0 attention output at the goal token", "optimal under g", "same action as natural under g′", "unchanged")
        for k, kl in KINDS:
            g = lambda m: v("behaviour", cls, k, m)
            L.append(row(kl, mr(g("optimal")), mr(g("as_other_goal")), mr(g("unchanged"))))
        L.append("")
    # decision rule
    sq, sk = v("representation", "share", "query"), v("representation", "share", "selfkv")
    pQ = p_gt(sq, sk)
    Q = np.median(sq) >= 0.5 and pQ < 0.05
    Qp = np.median(v("representation", "share_posterior", "query")) >= 0.5
    opt = lambda cls, k: v("behaviour", cls, k, "optimal")
    drop_m, drop_n = opt("goal_matters", "natural") - opt("goal_matters", "query"), opt("goal_neutral", "natural") - opt("goal_neutral", "query")
    pB1, pB2 = p_gt(opt("goal_matters", "natural"), opt("goal_matters", "query")), p_gt(drop_m, drop_n)
    B = np.median(drop_m) >= 0.05 and pB1 < 0.05 and pB2 < 0.05
    yes = lambda b: "**yes**" if b else "no"
    L += ["## Decision rule", ""]
    L += head("", "criterion", "value", "held")
    L.append(row("**Q**", "share(query) ≥ 0.5, above share(selfkv)", f"{f(np.median(sq))} against {f(np.median(sk))}; p {fp(pQ)}", yes(Q)))
    L.append(row("**Qp**", "posterior-explained part: share(query) ≥ 0.5", f(np.median(v('representation', 'share_posterior', 'query'))), yes(Qp)))
    L.append(row("**B**", "goal-matters: optimal drop under the query swap ≥ 0.05 (p < 0.05), larger than goal-neutral (p < 0.05)",
                 f"{f(np.median(drop_m))} (p {fp(pB1)}); goal-neutral {f(np.median(drop_n))} (p {fp(pB2)})", yes(B)))
    dk_m = opt("goal_matters", "natural") - opt("goal_matters", "selfkv")
    L += ["", "Descriptive: the own key-and-value swap lowers optimal on goal-matters cells by " + mr(dk_m) + "; trained − untrained share(query) " +
          mr(sq - u("representation", "share", "query")) + ".", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
