"""The interaction-removal experiment: tables and the registered decision rule from results.json (all ten models, and seeds 1-9 apart).

    .venv/bin/python studies/5_goal_belief_mechanism/interaction_removal/tables.py            # writes tables.md
"""

from __future__ import annotations

import importlib.util, json
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("r32tables", OUT.parent.parent / "5_goal_belief_mechanism" / "direct_belief_edit" / "tables.py")
T32 = importlib.util.module_from_spec(spec); spec.loader.exec_module(T32)
f, row, head, mr, p_gt, fp, _get = T32.f, T32.row, T32.head, T32.mr, T32.p_gt, T32.fp, T32._get
KINDS = (("natural", "nothing removed"), ("mlp_post", "the MLP-depth experiment: posterior-level J subtracted, all four MLPs"), ("mlp_resid", "only the per-history deviation from J, all four MLPs"),
         ("mlp_hist", "per-history interaction, all four MLPs"), ("attn_hist", "per-history interaction, all four attention outputs"),
         ("all_hist", "**per-history interaction, all eight (additive goal + history state)**"), ("shuffled", "control: another history's interaction subtracted, all eight"))
COMPS = ("L0.attn", "L1.attn", "L2.attn", "L3.attn", "L0.mlp", "L1.mlp", "L2.mlp", "L3.mlp")


def main():
    R = json.load(open(OUT / "results.json"))
    runs = R["runs"]
    c = R["cells"]
    L = ["# The interaction-removal experiment tables", "", "Generated by `studies/5_goal_belief_mechanism/interaction_removal/tables.py`. The observation-prediction experiment's ten reward models; the goal token's eight component outputs. "
         f"Cells: goal-matters {c['goal_matters']}, goal-neutral {c['goal_neutral']}. Median (range). Seed 0 was previewed before the plan (see PLAN.md); "
         "seeds 1–9 are shown apart.", ""]
    rule = None
    for label, seeds in (("all ten models", sorted(runs, key=lambda s: int(s[4:]))), ("seeds 1–9 (no preview)", [f"seed{i}" for i in range(1, 10)])):
        v = lambda *p: np.array([_get(runs[s], p) for s in seeds], dtype=float)
        gm = lambda k: v("optimal", "goal_matters", k)
        gn = lambda k: v("optimal", "goal_neutral", k)
        L += [f"## Optimal under g: {label}", ""]
        L += head("removed at the goal token", "goal-matters", "drop", "goal-neutral", "drop")
        for k, kl in KINDS:
            L.append(row(kl, mr(gm(k)), mr(gm("natural") - gm(k)) if k != "natural" else "—", mr(gn(k)), mr(gn("natural") - gn(k)) if k != "natural" else "—"))
        L += ["", "Keep one component live, all others' interaction removed (goal-matters optimal):", ""]
        L += head(*COMPS)
        L.append(row(*[mr(gm(f"keep_{k}")) for k in COMPS]))
        d = lambda k: gm("natural") - gm(k)
        pH, pA = p_gt(d("mlp_hist"), d("mlp_post") + 0.05), p_gt(d("all_hist"), d("mlp_hist") + 0.05)
        best = np.stack([gm(f"keep_{k}") for k in COMPS], 1).max(1)
        Kr = np.median((best - gm("all_hist")) / np.maximum(d("all_hist"), 1e-9))
        yes = lambda b: "**yes**" if b else "no"
        L += ["", f"### Decision rule ({label})", ""]
        L += head("", "criterion", "value", "held")
        L.append(row("**H**", "mlp_hist drop ≥ mlp_post drop + 0.05", f"{f(np.median(d('mlp_hist')))} against {f(np.median(d('mlp_post')))}; p {fp(pH)}", yes(np.median(d("mlp_hist") - d("mlp_post")) >= 0.05 and pH < 0.05)))
        L.append(row("**A**", "all_hist drop ≥ mlp_hist drop + 0.05", f"{f(np.median(d('all_hist')))} against {f(np.median(d('mlp_hist')))}; p {fp(pA)}", yes(np.median(d("all_hist") - d("mlp_hist")) >= 0.05 and pA < 0.05)))
        L.append(row("**F**", "all_hist goal-matters optimal ≤ 0.5", f(np.median(gm("all_hist"))), yes(np.median(gm("all_hist")) <= 0.5)))
        L.append(row("**K**", "best keep-one recovers ≥ 0.75 of the all_hist drop", f"{f(Kr, 2)} (drop {f(np.median(d('all_hist')))}: not assessable when small)", yes(Kr >= 0.75)))
        pR = p_gt(d("mlp_post"), d("mlp_resid"))
        L += ["", f"Diagnostic: mlp_post drop {f(np.median(d('mlp_post')))} against mlp_resid drop {f(np.median(d('mlp_resid')))} (p {fp(pR)}); "
              f"against mlp_hist {f(np.median(d('mlp_hist')))} (p {fp(p_gt(d('mlp_post'), d('mlp_hist')))}).", ""]
    (OUT / "tables.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
